centreon/centreon-plugins

apps/apcupsd/local/mode/libgetdata.pm
the ITEMP information is write " 23 C" not " 23 C internal". correct the bug: 
#/usr/lib/nagios/plugins/Centreon/SNMP/centreon-plugins/centreon_plugins.pl --plugin=apps::apcupsd::local::plugin  --mode=temperature
Use of uninitialized value $valueok in numeric eq (==) at /usr/lib/nagios/plugins/Centreon/SNMP/centreon-plugins/apps/apcupsd/local/mode/libgetdata.pm line 52.
CRITICAL: NO DATA FOUND |
=> bug correction

database/oracle/mode/asmdiskgroupusage.pm
usable_file_mb is not used_mb => SABLE_FILE_MB indicates the amount of free space, adjusted for mirroring, that is available for new files to restore redundancy after a disk failure. (http://docs.oracle.com/cd/B28359_01/server.111/b31107/asmdiskgrps.htm)
used = total - usable_file_mb
=> + fix oracle asmdiskgroupusage mode

cloud/aws/custom/awscli.pm, cloud/aws/mode/cloudwatch.pm, cloud/aws/mode/instancestate.pm, cloud/aws/mode/list.pm, cloud/aws/mode/metrics/ec2instancecpu.pm, cloud/aws/mode/metrics/ec2instancecpucreditbalance.pm, cloud/aws/mode/metrics/ec2instancecpucreditusage.pm, cloud/aws/mode/metrics/ec2instancenetwork.pm, cloud/aws/mode/metrics/rdsinstancecpu.pm, cloud/aws/mode/metrics/s3bucketsize.pm, cloud/aws/plugin.pm
Hello,
please find here the pull-request for the issue #107.
currently, 3 plugins are implemented:
- list => list all EC2 and RDS instances (with disco-show option) and S3 bucket (no perf data)
- instancestate => list all EC2 instances states with count of each state (perf data)
- cloudwatch => extract one metric value from cloudwatch amazon service. A starting list of metrics is already implemented
- all plugins currently use the custom mode 'awscli', a pure perl api will be introduced later.
regards
=> Amazon plugin

os/aix/local/mode/errpt.pm
Useful if we do not want to set a long comma separated list of id, but a more complex pattern
=> +add filter-id like we do for filter-resource

snmp_standard/mode/diskio.pm
Hello,
I made a modification of this plugin in order to have the sum of reads and writes (IO and IOps) on different disks.
Example : 
OK: All devices [Read I/O : 0.00 B/s, Write I/O : 529.63 KB/s, Read IOPs : 0.00, Write IOPs : 19.61] - Server overall [R+W I/O : 529.63 KB/s, R+W IOPs : 19.61] - All devices are ok. | 'total_read'=0B/s;;;0; 'total_write'=542344B/s;;;0; 'total_read_iops'=0.00iops;;;0; 'total_write_iops'=19.61iops;;;0; 'sum_read_write'=542344B/s;;;0; 'sum_read_write_iops'=19.61iops;;;0; 'read_sda'=0B/s;;;0; 'write_sda'=438626B/s;;;0; 'read_iops_sda'=0.00iops;;;0; 'write_iops_sda'=10.45iops;;;0; 'read_sdb'=0B/s;;;0; 'write_sdb'=103718B/s;;;0; 'read_iops_sdb'=0.00iops;;;0; 'write_iops_sdb'=9.16iops;;;0;
In the first part "All devices", we have the sum of reads on all disks and …
=> Update diskio.pm : sum of reads and writes

apps/protocols/x509/mode/validity.pm
Hello,
Small patch to put in conformity with the help description  "--port  Port used by Server (Default: '443')", 
Regards,
Fix
=> Add default 443 port for X509 plugin

database/oracle/mode/tablespaceusage.pm
In the case of a RAC, the correct undo is displayed on the node
=> + fix UNDO

apps/selenium/mode/scenario.pm
This PR adds information in the output in case of "non OK" status (last command + last echo command if provided in the scenario)
Note that the way to use "echo" in scenario is documented in WAA on doc-dev (not yet on documentation.centreon.com)
Output:
```bash
./centreon_plugins.pl  --plugin=apps::selenium::plugin --mode=scenario --selenium-hostname=192.168.56.211 --selenium-port=4444 --directory=/var/lib/centreon_waa --scenario=scenario-local --warning=15 --critical=20
OK: 7/7 steps (6.775s) | 'time'=6.775s;0:15;0:20;0; 'steps'=7;;;0;7 'availability'=100%;;;0;100
./centreon_plugins.pl  --plugin=apps::selenium::plugin --mode=scenario --selenium-hostname=192.168.56.211 --selenium-port=4444 --directory=/var/lib/centreon_waa --scenario=scenario-local --warning=15 --critical=20
CRITICAL: 5/7 …
```
=> Provide user feedback thu echo command

database/postgres/mode/timesync.pm
Bug: on comparait le timestamp avec les seuils alors qu'il faut comparer la différence (timestamp - localtime)
=> Problème avec la gestion des seuils

hardware/ups/apc/snmp/mode/batterystatus.pm
This is to avoid to display remaining time like: Remaining time : 460.366666666667 minutes
NB: i'm not a perl guru, so using sprintf to round a float is perhaps not the right way to do.
jfr
=> Round remaining time to minutes

centreon/common/cisco/standard/snmp/mode/environment.pm, centreon/plugins/misc.pm
Example:
```
'.1.3.6.1.2.1.47.1.1.1.1.2.4954' => 'FixedModule-1 Port-5',
'.1.3.6.1.2.1.47.1.1.1.1.2.21598' => 'PowerSupply-1 Sensor-1
',
'.1.3.6.1.2.1.47.1.1.1.1.2.4953' => 'FixedModule-1 Port-4',
'.1.3.6.1.2.1.47.1.1.1.1.2.149' => 'Nexus5020 Chassis',
```
=> To remove the line breaks in the description.

apps/pacemaker/local/mode/crm.pm
Add 'long_msg' options to extend verbose informations
Add an 'or' on stopped resources regexp test to take into account both unmanaged stop and crm stop as the output is not the same :
centengine (ocf::heartbeat:centengine):    Stopped (unmanaged)
centengine (ocf::heartbeat:centengine):    (target-role:Stopped) Stopped
=> Add verbose and regexp for stopped resources

os/windows/snmp/mode/memory.pm
Rewrite of Windows memory mode to use benefits of counters class.
[SNMP Memory for Windows is still deprecated]
Fix #562
=> Check windows memory as storage - Fix #562

apps/centreon/sql/mode/multiservices.pm
Ref to https://github.com/centreon/centreon-plugins/issues/630 
This mode allow you to concatenate several result of host and/or service check into one check (for example check from a Centreon a bunch of check on an other).
sqlmatching mode sample : 
-- Config file : 
```
{
"selection":{
"ESX":{
"host_name_filter":"%clus-esx-n%",
"service_name_filter":"Esx-Status"
},
"XIVO":{
"host_name_filter":"%xivo%",
"service_name_filter":"Ping"
}
},
"mode":"sqlmatching",
"counters":{
"totalservices":true,
"totalhosts":true,
"groups":true
},
"formatting":{
"groups_global_msg":"Nothing special on groups",
"host_service_separator":"/",
"display_details":true
}
}
```
Command : 
`/usr/lib/nagios/plugins/centreon_plugins.pl --plugin database::mysql::plugin --dyn-mode …
=> [multiservice] first release of dyn-mode multiservice 

apps/varnish/local/mode/clients.pm, apps/varnish/local/mode/sessions.pm, apps/varnish/local/mode/threads.pm, apps/varnish/local/plugin.pm
- Add threads.pm mode (replace workers for varnish4)
- Add clients.pm mode (useful to have number of conn and errors per sec)
- Refactor sessions.pm to be compliant with varnish3 and varnish4 
Notes : connections informations are gone in varnishstat v4 so use clients and sessions mode should help you to recover previous monitored informations in varnishstat v3
=> Add new modes to plugin and refactor sessions.pm

apps/jmeter/mode/scenario.pm
XML output is slightly different when using non HTTP scenarios with JMeter (for instance for a database test plan).
The attributes of the XML nodes are still the sames.
=> Take into account non HTTP samples

centreon/plugins/script_simple.pm
There was no help available while using dyn-mode.
This patch fixes this
=> Fixed --help options no working with --dyn-mode

apps/protocols/http/mode/expectedcontent.pm, apps/protocols/http/mode/jsoncontent.pm, apps/protocols/http/mode/response.pm, apps/protocols/http/mode/soapcontent.pm, centreon/plugins/http.pm, centreon/plugins/useragent.pm
Subclassed _get_basic_credentials_ so it gives back the credentials provided in command line, and doesn't store them in the basic_authentication hash (http://search.cpan.org/~ether/libwww-perl-6.31/lib/LWP/UserAgent.pm#get_basic_credentials). 
This way, requests can be done on web servers asking for Basic, NTLM, NTLMv2 or Digest authentification.
Authen::NTLM > 1.04 is still needed for NTLMv2 authentification (cf @pkriko commits https://github.com/centreon/centreon-plugins/commit/d33a1c217eabc63158cab5e38a3cd56526940dac).
Option _--ntlm_ is now useless but remains for compatibility.
In case of _401_ error, the output will show you the expected authentification type.
=> improve authentification handling

apps/centreon/local/mode/metaservice.pm
Change metric name from 'value' to real metric name.
Ref.: https://github.com/centreon/centreon-plugins/issues/874
=> fix metric name in meta service mode

snmp_standard/mode/processcount.pm
- Add name lookup each time to make long output better. Also add PID.
```
OK: Number of current processes running: 2 | 'nbproc'=2;;;0;
Process 'cbd' [pid: 113682] [status: runnable]
Process 'cbd' [pid: 888] [status: runnable]
```
- Add memory and CPU usage to long output.
```
OK: Number of current processes running: 2 - Total memory usage: 18.23 MB - Average memory usage: 9.12 MB - Total CPU usage: 0.00 % | 'nbproc'=2;;;0; 'mem_total'=19120128B;;;0; 'mem_avg'=9560064.00B;;;0; 'cpu_total'=0.00%;;;0;
Process 'cbd' [pid: 113682] [memory: 13.83 MB] [cpu: 0.00 %] [status: runnable]
Process 'cbd' [pid: 888] [memory: 4.40 MB] [cpu: 0.00 %] [status: runnable]
```
- Add the possibility to put thresholds on memory usage per processes. And show the problem in short output.
```
WARNING: Process 'cbd' …
```
=> improve processcount

network/f5/bigip/snmp/mode/poolstatus.pm, network/f5/bigip/snmp/mode/virtualserverstatus.pm
Fix bad first character in long and short outputs of virtual servers and pools name of F5 BigIP plugin.
=> Fix bad character f5 vs and pool

storage/ibm/fs900/snmp/mode/arraysstatus.pm, storage/ibm/fs900/snmp/mode/arraysusage.pm, storage/ibm/fs900/snmp/mode/components/battery.pm, storage/ibm/fs900/snmp/mode/components/fan.pm, storage/ibm/fs900/snmp/mode/components/fibrechannel.pm, storage/ibm/fs900/snmp/mode/components/flashcard.pm, storage/ibm/fs900/snmp/mode/components/psu.pm, storage/ibm/fs900/snmp/mode/fcusage.pm, storage/ibm/fs900/snmp/mode/hardware.pm, storage/ibm/fs900/snmp/plugin.pm
Checks hardware, arrays usage and status, fibre channels usage.
=> Add IBM FlashSystem 900 plugin

network/stormshield/snmp/mode/hanodes.pm
Fix dead nodes value catching and filter management so we just retreive what we need.
Add role of node.
=> Fix stormshield hanodes mode

network/f5/bigip/snmp/mode/listtrunks.pm, network/f5/bigip/snmp/mode/trunks.pm, network/f5/bigip/snmp/plugin.pm
Add modes trunks and list-trunks to F5 BigIP plugin.
=> add modes trunks and list-trunks

snmp_standard/mode/ntp.pm
Add check of empty value for --ntp-hostname option.
=> Improve ntp mode empty ntp_hostname option

network/riverbed/steelhead/snmp/mode/bwoptimization.pm, network/riverbed/steelhead/snmp/mode/bwpassthrough.pm, network/riverbed/steelhead/snmp/mode/connections.pm, network/riverbed/steelhead/snmp/mode/diskutilization.pm, network/riverbed/steelhead/snmp/mode/health.pm, network/riverbed/steelhead/snmp/mode/loadaverage.pm, network/riverbed/steelhead/snmp/mode/servicestatus.pm, network/riverbed/steelhead/snmp/mode/serviceuptime.pm, network/riverbed/steelhead/snmp/mode/temperature.pm
Refactor Riverbed Steelhead plugin to handle EX series.
Refs: #970
=> refactor riverbed steelhead

apps/protocols/http/mode/expectedcontent.pm, apps/protocols/http/mode/jsoncontent.pm, apps/protocols/http/mode/response.pm, apps/protocols/http/mode/soapcontent.pm, centreon/plugins/http.pm
Kind of roll back https://github.com/centreon/centreon-plugins/pull/860 to get back transparent behaviour we had before when it comes to basic authentication.
By adding --basic option, we can handle hidden basic authentication and also prevent webserver to respond 401 errors for basic authentication.
Digest and NTLM authentication still don't need any options.
=> enhance http lib to handle hidden basic authent

network/hirschmann/standard/snmp/mode/components/psu.pm
Refs: https://github.com/centreon/centreon-plugins/issues/982
=> fix hirschmann psu wrong oid

os/windows/snmp/mode/memory.pm
hi there @maksoy74, I have same scenario, windows servers can reply with either _Physical memory_ or _Physical RAM_
Didn't have time before to create a pr with the fix but now that I saw your issue here it is. fixes #994 
Hope it helps, thanks
=> Cannot find physical memory informations fix #994

storage/qnap/snmp/mode/hardware.pm
Add smartdisk section to allow threshold overload
Fix: https://github.com/centreon/centreon-plugins/issues/1008
=> fix qnap hardware thresholds overload

hardware/server/dell/idrac/snmp/mode/components/processor.pm
Hi,
On a server with some non-installed CPUs, the `processor` component of the idrac plugin returns `UNKNOWN` for the missing CPUs (empty sockets).
This is due to the fact that `processorDeviceStatusTable` contains entries for the non-existing CPUs.
Let's then use `processorDeviceTable` instead.
Thank you :+1: 
```
$ centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=hardware --hostname=1.2.3.4 --component='processor'
UNKNOWN: Processor 'CPU2 Status' state is 'unknown' |
```
```
$ centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=hardware --hostname=1.2.3.4 --component='processor'
OK: All 1 components are ok [1/1 processors]. |
```
```
$ snmpwalk -v2c -c public 1.2.3.4 1.3.6.1.4.1.674.10892.5.4.1100.32 …
```
=> Report idrac installed CPUs only

apps/protocols/radius/mode/login.pm
Correct option '--retry' instead of '--timeout' in help of plugin
=> Correct RADIUS help

os/windows/snmp/mode/swap.pm
For some reason, the virtual memory for windows hosts are not correctly defined in windows machines with SNMP. When you do a request of OID .1.3.6.1.2.1.25.2.3.1.5 instead of gives you the INTEGER for the Virtual memory only, it gives you the sum of all the memory in the System (physycal + virtual)
I've edited the Swap module for windows OS in order to re-calculate the Virtual Memory correctly substracting the physical memory from the virtual memory (.1.3.6.1.2.1.25.2.3.1.5 and .1.3.6.1.2.1.25.2.3.1.6) in order to get the real Virtual Memory.
=> Re-calculating Virtual Memory for Windows machines

os/windows/snmp/mode/swap.pm
Matches https://github.com/centreon/centreon-plugins/issues/994 fix
=> enh windows snmp swap, physical memory name

os/freebsd/snmp/plugin.pm
Hi,
This PR adds time mode to FreeBSD SNMP plugin, as in Linux SNMP plugin.
Tested, and of course it works.
Thank you :+1:
=> Add time mode to FreeBSD plugin

cloud/prometheus/restapi/mode/expression.pm, cloud/prometheus/restapi/plugin.pm
Add an "expression" mode for Prometheus, meaning you can execute PromQL queries as you'd do from the web console.
You can execute several expressions and then compare results in the warning and critical statut thresholds.
Perfdata will be generated for each expressions result.
This mode is meant to be used for simple queries. If it's not enough, it means you need a dedicated mode :)
Examples:
```
--hostname=localhost --port=9090 --query='desired,kube_deployment_spec_replicas'
--query='available,kube_deployment_status_replicas_available' --instance='deployment'
--critical-status='%{available} < %{desired}'
--output='Deployment %{instance} Replicas Desired: %{desired}, Available: %{available}'
--multiple-output='All deployments replicas are ok'
```
```
--hostname=localhost --port=9090 …
```
=> add prometheus expression mode

network/cisco/callmanager/snmp/mode/phoneusage.pm
Use name instead of description as its not always defined.
=> fix cisco callmanager phone name oid

centreon/plugins/snmp.pm
check_oid_up function variables were wrongly assigned, and function was trying to split an hash.
=> fix snmp lib start/end checkup function

apps/protocols/x509/mode/certificate.pm
Hi,
This PR prevents removing `subject` from `alt_subjects` in certificate plugin.
This leads to errors where `alt_subjects` is used for example in a Centreon service template to simply check that certificates at least contain the expected domain.
Thank you :+1:
=> x509, do not remove subject from alt_subjects

snmp_standard/mode/uptime.pm
Hi,
This PR addresses a small bug / typo, where reboot window is in reality twice as `--reboot-window` parameter.
This PR then corrects this so that the window has now the expected correct range.
Thank you :+1:
=> Use true given window range, not twice

network/mikrotik/snmp/mode/environment.pm, network/mikrotik/snmp/plugin.pm
Hi,
This PR adds uptime mode to `network::mikrotik::snmp` plugin.
Thank you :+1:
=> Mikrotik, add uptime mode

network/checkpoint/snmp/mode/hastate.pm
'no_ha_status' or 'no_ha_state' to handle the option no-ha-status? :)
Let's use the first name in the code : 'no_ha_status'
=> Fix no-ha-status option

centreon/plugins/output.pm
Hi,
This PR corrects an issue with `--extend-perfdata-group` option.
If no matching perfdata is found to compute the new perfdata, the new perfdata is added with an empty value.
This PR then solves this, preventing from adding new empty perfdata.
Thank you 👍
=> Add new perfdata only if value is set

apps/protocols/http/mode/expectedcontent.pm
Hi,
Due to the the wide range of tests HTTP expected-content mode is able to perform (content, value, return code, response time, size...), let's update the default OK short message to a more generic one.
Thank you :+1:
=> Update HTTP default message

network/mikrotik/snmp/plugin.pm
Hi,
This mode simply adds time mode to `network::mikrotik::snmp::plugin`.
Thank you :+1:
=> Add time mode to Mikrotik

network/mikrotik/snmp/mode/interfaces.pm, network/mikrotik/snmp/plugin.pm
Hi,
This closes #1485, adding Mikrotik PHY error counters to interface mode.
Just one thing I'm not really sure about, the numeric prefix of each error counter in the `{maps_counters}->{int}` hash.
I then took OID + 100, feel free to tell me if it needs to be updated.
One limitation we see with this mode is that we miss a short way to define a threshold for all error counters at once.
Here we would need 31 x 2options to define warning and critical thresholds on all error counters.
If we set the same threshold on all counters, only 2 global options would be needed (one warning, one critical).
They would eventually be superseded by the specific ones, if used.
Another way would be to be able to define thresholds on `--extend-perfdata-group` option, but perhaps more difficult to achieve. …
=> Support Mikrotik PHY error counters

database/oracle/mode/datafilesstatus.pm
Hi,
This PR updates the default critical-status option for Oracle data files.
See [here](https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_3083.htm#REFRN23049) and [here](https://docs.oracle.com/cd/B28359_01/server.111/b28320/dynviews_3098.htm#REFRN30283) for status possible values.
Thank you 👍
=> Raise Oracle data file crit alert

snmp_standard/mode/stringvalue.pm
Hi,
This PR allows to use `str2time()` in _--convert-custom-values_ option of _string-value_ mode, in _apps::protocols::snmp_ plugin.
For example :
`--convert-custom-values='(time - str2time($value)) / 3600'`
Many thanks 👍
=> Add possiblity to use str2time()

snmp_standard/mode/memory.pm
Hello,
I modified the regex in "--autodetect-redhat" to permit to match Oracle Linux servers (redhat like)
snmpwalk -cpublic -v2c dev
SNMPv2-MIB::sysDescr.0 = STRING: Linux dev 4.14.35-1902.6.6.el7uek.x86_64 #2 SMP Tue Oct 8 07:32:21 PDT 2019 x86_64
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.7 (Maipo)
thanks
Arnaud
=> Added Oracle Linux 7.7 exception in --autodetect-redhat options

snmp_standard/mode/diskusage.pm
Hi,
According to my tests, sounds like all `diskusage` counters are enabled by default ?
Thank you 👍
=> All counters are enabled by default

storage/synology/snmp/mode/components/raid.pm, storage/synology/snmp/mode/hardware.pm
These additional statuses are documented [here](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_DiskStation_MIB_Guide.pdf):
* DataScrubbing (13): RAID is DataScrubbing
* RaidDeploying (14): RAID is deploying Single volume on pool
* RaidUnDeploying (15): RAID is not deploying Single volume on pool
* RaidMountCache (16): RAID is mounting SSD cache
* RaidUnmountCache (17): RAID is not mounting SSD cache
* RaidExpandingUnfinishedSHR (18): RAID continue expanding SHR if interrupted
* RaidConvertSHRToPool (19): RAID is converting Single volume on SHR to multiple volume on SHR
* RaidMigrateSHR1ToSHR2 (20): RAID is migrating SHR1 to SHR2
* RaidUnknownStatus (21): RAID status is not included in the status above
Everything other than …
=> storage::synology::snmp: handle raidStatus values over 12

centreon/plugins/backend/http/curl.pm
If I use `--proxyurl http://user:pass@a.b.c.d:8080` there's a bug in that bit of code:
https://github.com/centreon/centreon-plugins/blob/157eb81cfabf94bb31130697d4bb8ef006f60b77/centreon/plugins/backend/http/curl.pm#L218
It sets `$options{request}->{proxyurl}` to `http:user:pass@a.b.c.d:8080` which makes cURL fail.
```
UNKNOWN: curl perform error : Couldn't resolve proxy name
```
It looks like you do not need that bit of code since [the documentation for `CURLOPT_PROXY`](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html) specifies that
> A proxy host string can also include protocol scheme (http://) and embedded user + password. 
I have tested these changes on my CentOS 7 Centreon Poller and proxy authentication works as expected.
=> Remove useless proxyurl handling from cURL HTTP backend

snmp_standard/mode/inodes.pm
@garnier-quentin As discussed on Slack, this makes it easier to filter special filesystems such as `/proc`.
=> snmp_standard::mode::inodes: allow filtering by device path

database/influxdb/custom/api.pm
Hi,
Let's remove these 3 lines, as they are redefined below ?
```
my $content = $self->{http}->request(
%options,
unknown_status => $self->{unknown_http_status},
warning_status => $self->{warning_http_status},
critical_status => $self->{critical_http_status},
);
```
Thx !
=> [influxdb] Remove 3 redefined lines

apps/voip/3cx/restapi/custom/api.pm, apps/voip/3cx/restapi/mode/system.pm
Hi,
This PR adds HTTP options to the 3CX plugin, as done in the InfluxDB plugin.
While here, simplify the `catalog_status_calc` call.
Thank you 👍
=> 3CX, add HTTP status options

centreon/plugins/alternative/Getopt.pm
Hi,
This PR allows to use parameters with embedded newlines.
This works when using Perl `Getopt` (`$alternative = 0` in `centreon/plugins/options.pm`).
But it was not working with `centreon::plugins::alternative::Getopt`.
This is now fixed thanks to this PR 👍
Thx !
=> Allow newline character in parameters

notification/sirportly/mode/ticket.pm, notification/sirportly/plugin.pm
Hi,
Here is a new notification plugin, for [Sirportly](https://sirportly.com), based on its [API](https://sirportly.com/docs/api-specification/).
It has several features :
- it opens new tickets ;
- it updates existing tickets ;
- it closes tickets if no work has been done on them since opening ;
- it has a cache feature so that non-delivered notifications are retried at next run.
Thank you 👍
=> Add Sirportly notification plugin

network/mikrotik/snmp/mode/components/temperature.pm
Hi,
Sometimes, MikroTik SNMP agent hangs...
And returns -273°C as the temperature.
Let's then return UNKNOWN exit code for this lowest temperature scale value.
Thx 👍
=> MikroTik, return -273°C as UNKNOWN

network/alcatel/omniswitch/snmp/mode/components/resources.pm
Hi,
I fixed the notation of some OIDs in the Alcatel OmniSwitch plugin.
This fixes the hardware mode for newer AOS versions.
Can you please consider merging this PR?
Thanks!
=> Alcatel OmniSwitch: Fix notation of some OIDs

cloud/aws/ec2/mode/network.pm
bad metric name for network out
=> fix problem with metric name in network mode for ec2

network/juniper/common/junos/mode/interfaces.pm
Hi,
This PR corrects the Juniper interfaces mode help, removing non-existing options.
I think this is the result of a copy/paste from the MikroTik interfaces mode.
Thx 👍
=> typo(juniper): wrong help options

snmp_standard/mode/interfaces.pm
Hi,
This PR corrects a typo in perfdata newlabel of `interfaces` mode.
Here's an example of a perfdata newlabel :
- with `--units-errors=absolute` :
`interface.packets.in.alignerror.count`
- with `--units-errors=%` :
`interface.packets.in.alignerrors.percentage`
Issue is with the additional `s` character added before `percentage`.
This PR removes it.
Thx 👍
=> Typo in interfaces perfdata new label

apps/protocols/nrpe/custom/nsclient.pm
Hi,
`--plugin=apps::protocols::nrpe::plugin --custommode=nsclient --mode=query --new-api`
Without this PR, output looks like :
` | 'total 10s'=2%;80;90;0;0`
With :
`OK: CPU load is ok. | 'total 10s'=2%;80;90;0;0`
Thank you 👍
=> Fix nsclient++ new API

network/mikrotik/snmp/mode/disk.pm, network/mikrotik/snmp/plugin.pm
Hi,
This PR adds a proper MikroTik disk mode.
Until now we could use the memory mode to achieve this, but then we had to change the "RAM" prefix into "Disk" in the short output, and this is not possible in the long output.
As it's almost a copy of the `memory` mode, I hesitated to rename `memory` mode to `storage` mode, and to add a sort of `--type` option, which would allow to tune the prefix, `RAM`, `Disk`, or whatever...
Feel free to tell me what's the best method.
Thank you 👍
=> MikroTik, add proper disk mode

hardware/kvm/avocent/acs/8000/snmp/mode/components/psu.pm, hardware/kvm/avocent/acs/8000/snmp/mode/hardware.pm, hardware/kvm/avocent/acs/8000/snmp/plugin.pm
This is mostly a copy of the ACS6000 module with few changes, to support ACS8000 series. Changes are of course the naming (6000 > 8000) and the new OIDs of the power supplys. Tested with all modes against an ACS8000 of course.
=> add support for ACS8000 series (psu oid differs from ACS6000 series)

cloud/aws/custom/awscli.pm, cloud/aws/custom/paws.pm, cloud/aws/ec2/mode/spotactiveinstances.pm, cloud/aws/ec2/plugin.pm
New mode to monitor a spot fleet request: 
```
perl centreon_plugins.pl --plugin=cloud::aws::ec2::plugin --mode=spot-active-instances --custommode=awscli --region='eu-west-1' --spot-fleet-request-id=sfr-6b333-EXAMPLE
OK: Active instances : 50, Healthy instances : 50, Unhealty instances : 0 | 'ec2.spot.active.instance.count'=50;;;0; 'ec2.spot.unhealthy.instance.count'=50;;;0; 'ec2.spot.unhealthy.instance.count'=0;;;0;
```
=> (wip) add ec2 spot fleet instance count ref #172

network/cisco/prime/restapi/custom/api.pm
When testing with a ciscoprime with more than 1000 APs, the function stays in an infinite loop.
This is blocked by the setting "nbi.rateLimit.perUserThreshold" and issues the error:
"NBI Rate limit for user exceeded (More than 5 in 1,000 ms)"
=> Bugfix on infinite loop

network/checkpoint/snmp/mode/connections.pm
Hi,
This PR fixes the `connections` mode of `checkpoint` plugin.
If returns `UNKNOWN` in case it is called with `%` thresholds, but can't compute these thresholds, because of a missing max value.
User then knows he must properly configure max value at device level, before playing with `%` thresholds.
Thx 👍
=> fix(checkpoint) unknown if can't compute thresholds

os/aix/snmp/mode/swap.pm
Hi,
This PR simplifies the buggy swap state detection.
[As per IBM](https://www.ibm.com/support/knowledgecenter/SSATHD_7.7.0/com.ibm.itm.doc_6.3/aglesaix/fac_attributes_descriptions.htm), `1.3.6.1.4.1.2.6.191.2.4.2.1.6` returns 1 when active, 2 when notActive.
This is exactly what I have on AIX 7 here.
Let's then assume 1 == active, and do the contrary with the `--paging-state-buggy` option, whatever the OS version is.
Thanks 👍
=> fix(aix) simplify buggy swap state detection

hardware/devices/cisco/ces/restapi/mode/components.pm
Allowing threshold-overload selection for each components:
- ad.status
- vic.signal_state
- vic.status
- etc.
=> allowing to select right threshold-overload section

apps/java/jboss/jmx/mode/datasourceusage.pm
The datasource mode returned an unknown status because the datasources
were in another mbean. This addition shoud not break anything.
=> add jboss jmx mbean for datasource mode

snmp_standard/mode/storage.pm
Hi,
This PR adds a `--filter-duplicate` option to storage mode.
It filters storages which are equivalent in terms of total size and space used.
Thx 👍
=> enh(storage) Add --filter-duplicate option

network/citrix/netscaler/snmp/mode/vserverstatus.pm
Hi,
I face a strange issue on some Netscaler devices, where some OIDs are returned as `NOSUCHINSTANCE`, whereas they exist for sure, as requesting them with `snmpwalk` works.
In addition, strangely, playing with `--subsetleef` value widely changes the OIDs which are returned as such.
I performed some debug, but can't find any other explanation but a bug at device SNMP agent level.
I found that disabling the 32 bits OIDs (which for sure do not exist on the devices I work with) corrects the issue, at least I was not able to reproduce it, whatever the `--subsetleef` value used.
Let's then add the `--force-counters64` option already seen in other modules now.
Thx 👍
=> fix(netscaler) add --force-counters64 option

hardware/server/dell/idrac/snmp/mode/components/resources.pm, hardware/server/dell/idrac/snmp/mode/hardware.pm
Hi,
This PR fixes idrac hardware thresholds :
- it adds a missing `pdisk` state value ;
- it sets `regexp_threshold_overload_check_section_option` to possible values only ;
- it allows to set  `--threshold-overload` on `pdisk.smartalert`.
Thx 👍
=> fix(idrac) Hardware thresholds

network/fortinet/fortigate/snmp/plugin.pm
Hi,
Let's add some standard modes to Fortigate.
Strangely enough it does not support `time` mode (`.1.3.6.1.2.1.25.1.2` is not available there).
Thx 👍
=> enh(fortigate) Add Standard modes

network/citrix/netscaler/snmp/plugin.pm
Hi,
Let's add some standard modes to Netscaler.
Strangely enough it does not support `time` mode (`.1.3.6.1.2.1.25.1.2` is not available there).
Thx 👍
=> enh(netscaler) Add standard modes

apps/monitoring/loggly/restapi/custom/api.pm, apps/monitoring/loggly/restapi/mode/events.pm, apps/monitoring/loggly/restapi/mode/fields.pm, apps/monitoring/loggly/restapi/plugin.pm
Hi,
Here's a new plugin, for Loggly.
Based on their API :
https://documentation.solarwinds.com/en/Success_Center/loggly/Content/admin/api-retrieving-data.htm
One `events` mode, to count the number of events matching the given query.
One `fields` mode, which allows to count the number of unique fields (for example a number of hosts) matching the query.
Thx 👍
=> Add new Loggly plugin

centreon/plugins/statefile.pm
Hi,
This defaults `statefile-dir` to a Windows directory on Windows systems.
Thx 👍
=> enh(statefile) Use a windir on Windows

centreon/plugins/output.pm
Hi,
Missing pattern new handling style for `max` operation.
Thx :+1:
=> fix(output) max perfdata calc typo

centreon/common/powershell/windows/pendingreboot.pm
Hi,
Strangely enough I have Windows 2008 R2 hosts where OS build number fails to get retrieved.
Let's then simplify the method, we absolutely don't need this.
Thx 👍
=> fix(windows) local rebootpending

cloud/microsoft/office365/custom/graphapi.pm, cloud/microsoft/office365/exchange/mode/emailactivity.pm, cloud/microsoft/office365/exchange/mode/mailboxusage.pm, cloud/microsoft/office365/onedrive/mode/siteusage.pm, cloud/microsoft/office365/onedrive/mode/usage.pm, cloud/microsoft/office365/onedrive/mode/usersactivity.pm, cloud/microsoft/office365/onedrive/plugin.pm, cloud/microsoft/office365/sharepoint/mode/siteusage.pm, cloud/microsoft/office365/sharepoint/mode/usersactivity.pm, cloud/microsoft/office365/skype/mode/devicesusage.pm, cloud/microsoft/office365/skype/mode/usersactivity.pm, cloud/microsoft/office365/teams/mode/devicesusage.pm, cloud/microsoft/office365/teams/mode/usersactivity.pm
Hi,
Here's a rework of Office365 plugins.
- I add some new labels (this helps #1989).
- I rename some counters to better correspond to what the API calls return, and to avoid having identical counters over different modes.
- I add a few new counters.
- I update some instance labels to make things proper / easier.
- I rename `onedrive` `usage` mode to `site-usage` (as it is with `sharepoint`).
- I add the `onedrive` `users-activity` mode (as we have with `sharepoint`).
- I now use daily data to compute the active counters, to have more relevant numbers than the 7-days aggregated ones.
- I add a `perfdate` perfdata counter set to the _Report Refresh Date_, so that it can be used by Stream Connector Scripts to properly set the data timestamp (see …
=> enh(o365) Many enhancements

network/checkpoint/snmp/mode/connections.pm
Hi,
Let's set perfdata max value (so that we can use extend perfdata options to get a percentage metric).
Thx 👍
=> enh(checkpoint) set perfdata max connections number

apps/smartermail/restapi/custom/api.pm, apps/smartermail/restapi/mode/licensenotifications.pm, apps/smartermail/restapi/mode/services.pm, apps/smartermail/restapi/mode/spoolmessagecount.pm, apps/smartermail/restapi/plugin.pm
**Plugin to get information from SmarterMail API**
https://mail.smartertools.com/Documentation/api#/topics/overview
Authentication via username and password to get the JWT. Writes the JWT in a cache file in order to reuse it for later queries up to its expiration date
**mode=services**
https://mail.smartertools.com/Documentation/api#/reference/SmarterMail.Web.Controllers.Api.SystemAdminSettingsController/GetServices
checks if services are in running state
services: 'spool', 'smtp', 'pop', 'xmpp', 'imap', 'ldap', 'popretrieval', 'imapretrieval', 'indexing'
perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::smartermail::restapi::plugin --mode=services --hostname='webmail.example.com' --username=username --password='***password***' 
**filter option**
perl …
=> new plugin for SmarterMail API

apps/graylog/restapi/mode/query.pm
The graylog API consider requests with undef parameters values as 0. So we'd better ensure that the timeframe value is valid when the option is set
=> fix(mode): timeframe value should not be null

hardware/server/dell/idrac/snmp/mode/globalstatus.pm
Hi,
This PR improves iDRAC `global-status` mode adding the `systemModelName` to its output.
It's nice to know that it's an iDRAC card, but it's even better to know which hardware it monitors :)
While here, let's properly assign `CRITICAL` severity to `nonRecoverable` status, and gently clean the regex.
`OK: 'iDRAC9.4.10.10.10@PowerEdge R340' : global status is 'ok', storage status is 'ok'`
Thx 👍
=> enh(idrac) Add systemModelName to status output

storage/synology/snmp/mode/upgrade.pm, storage/synology/snmp/plugin.pm
Hi,
This PR adds a new `upgrade` mode to Synology plugin.
This helps to ensure whether or not devices are properly in sync with their updates' server, and uptodate.
All this thanks to the Synology MIB.
`OK: 'DS415+' : version is 'DSM 6.2-25426', upgrade is 'unavailable'`
Thx 👍
=> enh(synology) add new upgrade mode

network/mikrotik/snmp/mode/firmware.pm, network/mikrotik/snmp/plugin.pm
Hi,
This PR adds a `firmware` mode to MikroTik plugin.
So that we can check that both software and firmware run the same version (which is expected, but could not be the case as both have their separate update process).
`OK: 'RouterOS CRS326-24S+2Q+' : software is '6.47.7', firmware is '6.47.7'`
Thx 👍
=> enh(mikrotik) Add firmware mode

centreon/common/powershell/windows/pendingreboot.pm, os/windows/local/mode/pendingreboot.pm
Hi,
This PR enhances `pending-reboot` mode of `os::windows::local` plugin adding the Windows version in plugin output, which is really convenient.
`WARNING: 'Microsoft Windows Server 2012 Standard': reboot pending is true [Windows Update: false][Component Based Servicing: false][SCCM Client: -][File RenameOperations: true][Computer Name Change: false] |`
Thank you 👍
=> enh(windows) Output Windows version

cloud/aws/vpn/mode/listvpn.pm, cloud/aws/vpn/mode/traffic.pm
* get all the metrics and filter instead of having to specify one specific ID
* give the option to use connection name instead of ID
* remove useless code
* misc cosmetic fixes
Closes https://github.com/centreon/centreon-plugins/issues/2410
=> enh(plugin): AWS VPN enhancements

apps/mulesoft/restapi/mode/messages.pm
just add a check when object is undefined.
this is to avoid error message: UNKNOWN: Can't use an undefined value as an ARRAY reference at /usr/lib/centreon/plugins/centreon-plugins/apps/mulesoft/restapi/mode/messages.pm line 150
and the current check to fail.
=> bug fix when queue has no message

hardware/server/ibm/mgmt_cards/imm/snmp/plugin.pm
Hi,
Let's add `time` standard mode to IMM, so that we can check they are time-synchronised, which is helpful when handling logs etc...
Thx 👍
=> enh(imm) Add some standard modes

cloud/azure/custom/api.pm, cloud/azure/custom/azcli.pm, cloud/azure/management/loganalytics/mode/kustoquery.pm
- Stick to MS documentation on the option name (timespan instead of interval)
- Timespan should not be mandatory because users can filter on time through the query
=> Fix(plugin)loganalytics enhancement

cloud/kubernetes/mode/nodeusage.pm
Keep --units option for compat, but turn all thresholds to percentages.
Get closer to Kubernetes dashboard metrics:
```
perl centreon_plugins.pl --plugin=cloud::kubernetes::plugin --mode=node-usage --custommode='api' --hostname=amzkubernetesapi.int.centreon.com --port='443' --proto='https' --token='abcd' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --verbose --use-new-perfdata
OK: All nodes usage are ok | 'amzkubemaster.int.centreon.com#cpu.requests.percentage'=37.50%;;;0;100 'amzkubemaster.int.centreon.com#cpu.limits.percentage'=5.00%;;;0;100 'amzkubemaster.int.centreon.com#memory.requests.percentage'=3.96%;;;0;100 'amzkubemaster.int.centreon.com#memory.limits.percentage'=1.32%;;;0;100 'amzkubemaster.int.centreon.com#pods.allocation.percentage'=7.27%;;;0;100 …
```
=> enh(cloud/kubernetes): add metrics to node-usage mode

apps/protocols/snmp/mode/collection.pm, apps/protocols/snmp/plugin.pm
Example of config file:
```
{
"mapping": {
"disjoncteur": {
"0": "ferme",
"1": "ferme/defaut",
"10": "ouvert",
"11": "ouvert/defaut"
},
"other": {
"8": "test",
"25": "test2"
}
},
"snmp": {
"cache": {
"enable": true,
"reload": 30
},
"tables": [
{ 
"name": "plcData", 
"oid": ".1.3.6.1.4.1.13576.10.1.100.1.1",
"used_instance": "\\.(\\d+)$",
"entries": [
{ "name": "plcRead", "oid": ".1.3.6.1.4.1.13576.10.1.100.1.1.2", "map": "disjoncteur" },
{ "name": "plcWrite", "oid": ".1.3.6.1.4.1.13576.10.1.100.1.1.3" }
]
},
{
"name": "plcOther",
"oid": ".1.3.6.1.4.1.13576.10.1.100.2.1",
"entries": [
{ "name": "plop", "oid": ".1.3.6.1.4.1.13576.10.1.100.2.1.2" }
]
}
],
"leefs": [
{ "name": "serialNum", "oid": ".1.3.6.1.4.1.13576.10.1.2.0", "map": "other" },
{ "name": "macAddress", "oid": …
```
=> [mode] snmp generic collection first release

apps/monitoring/dynatrace/restapi/custom/api.pm
#./centreon_plugins.pl --mode=problems --plugin=apps::monitoring::dynatrace::restapi::plugin --hostname="live.dynatrace.com" --environment-id="1234-abcd-5678" --api-password=**** --debug
UNKNOWN: 404 Not Found |
======> request send
GET https://1234-abcd-5678.live.dynatrace.com:443/api/v1/problem/feed?relativeTime=min
#./centreon_plugins.pl --mode=problems --plugin=apps::monitoring::dynatrace::restapi::plugin --hostname="dynatrace.test.lan" --environment-id="1234-abcd-5678" --api-password=**** --debug
UNKNOWN: 500 Can't connect to dynatrace.test.lan:443 |
======> request send
GET https://dynatrace.test.lan:443/e/1234-abcd-5678/api/v1/problem/feed?relativeTime=min
=> fix(mode): Dynatrace fix URI for local hostnames

cloud/azure/management/apimanagement/mode/capacity.pm, cloud/azure/management/apimanagement/plugin.pm
gives the percentage of used capacity of the APIM
[root@svzam-cenpol001 apimanagement]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::management::apimanagement::plugin --custommode='api' --mode='capacity' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-capacity-percentage='80' --critical-capacity-percentage='90'
OK: Instance 'xxx' Statistic 'average' Metrics Capacity: 2.46% | 'xxx#apimanagement.capacity.percentage'=2.46%;0:80;0:90;0;
=> new mode "capacity" for Azure APIM

cloud/azure/network/appgateway/mode/backendhealth.pm, cloud/azure/network/appgateway/mode/backendunhealthyhost.pm, cloud/azure/network/appgateway/plugin.pm
adds a mode to get backends unhealthy host count (FYI: existing mode backend-status does ONLY work on App Gateway **v2**, not on v1 which are the most deployed globally on Azure; app gateway v2 is quite new)
=> new mode: --mode='backend-health'

cloud/azure/web/appserviceplan/mode/queue.pm, cloud/azure/web/appserviceplan/plugin.pm
Azure Appserviceplan new mode:
[ appserviceplan]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::web::appserviceplan::plugin --custommode='api' --mode='queue' --subscription='xxx' --tenant='xxx' --client-id='xxx' --client-secret='***' --resource-group='xxx' --resource='xxx' --warning-disk-queue-length='8' --critical-disk-queue-length='9'
OK: Instance 'xxx' Statistic 'average' Metrics Http Queue Length: 0, Disk Queue Length: 0 | 'AEUW-Diorpress-prd-ServicePlan~average#appserviceplan.http.queue.length'=0;;;0; 'AEUW-Diorpress-prd-ServicePlan~average#appserviceplan.disk.queue.length'=0;0:8;0:9;0;
=> enh(plugin): Appserviceplan new mode "queue"

hardware/server/hp/proliant/snmp/mode/components/memory.pm, hardware/server/hp/proliant/snmp/mode/hardware.pm
Hello,
With this I add support for checking memory slots on HPE Proliant servers.
This was tested with a HPE DL385 Gen10 Plus server.
=> Add support for checking memory slots on HPE Proliant servers

storage/netapp/ontap/restapi/mode/cluster.pm, storage/netapp/ontap/restapi/mode/volumes.pm
Enhancement for netapp plugin in order to add 'other' and 'total' metrics for 'volume' and 'cluster' modes.
=> Adds 'other' and 'total' metrics for netapp plugin

storage/qnap/snmp/mode/memory.pm
Hi,
This PR fixes #2860, adding a `--force-counters-legacy` to Qnap `memory` mode, to workaround EX/ES buggy counters.
We'll be able to get rid of it once Qnap will have solved this SNMP counters bug.
Thx 👍
=> enh(qnap) add a --force-counters-legacy

apps/voip/3cx/restapi/mode/system.pm
Hi,
This PR adds a `--filter-category` option to the 3CX `system` plugins.
This allows to choose on which update categories to be alerted, which is useful to filter-out betas &co.
Thx 👍
=> enh(3cx) Add --filter-category option

hardware/server/ibm/mgmt_cards/imm/snmp/mode/components/fan.pm, hardware/server/ibm/mgmt_cards/imm/snmp/mode/components/memory.pm
Fix #2891 
Some of the HealthStatus OIDs are only available with v2.
=> fix(plugin) imm mgmt_cards environment with version < 2.0

apps/backup/commvault/commserve/restapi/custom/api.pm
- One of the user got the following error with the latest version: 
```
UNKNOWN: Can't use an undefined value as an ARRAY reference at /usr/lib/centreon/plugins/centreon_commvault_commserve_restapi.pl line 289.
```
- After some troubleshooting, find out that the data was corrupted - $content scalar value was ')' -
- Adding `last if` allow to avoid Perl unclean exit but not sure it's the correct way to fix that. `next if` results in an infinite loop.
=> fix(plugin)bypass-perl-error-messy-commvault-api

network/dell/os10/snmp/mode/components/temperature.pm
Hi,
For same reasons as given in #2905, let's "properly" rename Dell OS10 temperature newlabel.
Thx 👍
=> enh(os10) temperature new label

hardware/ats/apc/snmp/mode/components/entity.pm
Hi,
Let's enh APC ATS plugin with full list of entities.
Thank you 👍
```
.1.3.6.1.4.1.318.1.1.8.5.1.1.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.2.0 = INTEGER: 1
.1.3.6.1.4.1.318.1.1.8.5.1.3.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.4.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.6.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.7.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.10.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.11.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.12.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.13.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.14.0 = INTEGER: 1
.1.3.6.1.4.1.318.1.1.8.5.1.15.0 = INTEGER: 1
.1.3.6.1.4.1.318.1.1.8.5.1.16.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.17.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.18.0 = INTEGER: 2
.1.3.6.1.4.1.318.1.1.8.5.1.19.0 = INTEGER: 2 …
```
=> enh(ats) Add support for some entities

hardware/pdu/apc/snmp/mode/load.pm
Hi,
Tune some APC labels :
- `bank` instead of `num` for banks (as we have `phase` for phases right above) ;
- shorten `module` to `mod` ;
- avoid spaces if possible.
Thx 👍
=> enh(pdu) Tune some labels

database/elasticsearch/restapi/mode/license.pm
Closes https://github.com/centreon/centreon-plugins/issues/2986
=> fix(plugin):avoid perl error when checking Elastic basic instances

apps/protocols/bgp/4/mode/bgppeerstate.pm
The Filter AS option didn't work because the filter was compare to the instance which is equal to the peer and not AS.
Just fixing the correct variable.
=> Fix Filter AS

network/libraesva/snmp/mode/system.pm
Wrong help for *-cluster-status
=> Libraesva - wrong help description on system.pm for *-cluster-status

cloud/azure/network/cdn/mode/requests.pm
azure-cdn-fix
{"code":"BadRequest","message":"Failed to find metric configuration for provider: Microsoft.Cdn, resource Type: profiles, metric: percentage4xx, Valid metrics: RequestCount,ResponseSize,TotalLatency,ByteHitRatio"}
{"code":"BadRequest","message":"Failed to find metric configuration for provider: Microsoft.Cdn, resource Type: profiles, metric: percentage5xx, Valid metrics: RequestCount,ResponseSize,TotalLatency,ByteHitRatio"}
=> fix(mode): Azure CDN requests deprecated metrics

storage/hp/3par/ssh/mode/components/sensor.pm
New Primera storage based on 3PAR OS commes with new sensors.
Memory voltage sensors label (  DDR40 VDDQ A ) match first block in filter so VDDQ is considered as the value.
Filter must be fixed to match digit instead of non-space characters.
Moreover, there's also FAN sensors which were not handled by filter.
=> fix filter for new sensors (Primera)

apps/nmap/cli/mode/discovery.pm
While Nmap can use Mac addr to guess the vendor, we prefer using this in the first place instead of the os field.  
Tests show that most of the time the Plugin will return a Linux type because the vendor built its system on top of a Linux Kernel.
=> enh(disco)  nmap discovery

cloud/vmware/velocloud/restapi/custom/api.pm
This fix the post request for qoe links where latest versions of Velocloud API won't accept quoted strings as values
=> fix(velocloud): compliant post request for qoe list

apps/pacemaker/local/mode/crm.pm
New format:
```
Cluster Summary:
* Stack: corosync
* Current DC: server2 (version 2.0.5-ba59be7122) - partition with quorum
* Last updated: Mon Dec 27 16:10:53 2021
* Last change:  Sun Dec 26 15:20:00 2021 by root via cibadmin on server1
* 2 nodes configured
* 2 resource instances configured
Node List:
* Online: [ server1 server2 ]
Full List of Resources:
* Resource Group: core_cluster:
* floating_ip       (ocf:heartbeatI.IPaddr2):        Started server1
* http_server       (ocf:heartbeatI.nginx):  Started server1
Migration Summary:
command response: Cluster Summary:
* Stack: corosync
* Current DC: server2 (version 2.0.5-ba59be7122) - partition with quorum
* Last updated: Mon Dec 27 16:10:53 2021
* Last change:  Sun Dec 26 15:20:00 2021 by root via cibadmin on server1
* 2 nodes configured …
```
=> enh(pacemaker/local): mode crm - modify nodes online/offline regexp

cloud/azure/compute/disk/mode/diskio.pm
Adding unit in metrics_mapping to prevent such errors in output : 
```Use of uninitialized value in string eq at /home/centos/centreon-plugins/cloud/azure/custom/mode.pm line 92.
Use of uninitialized value $unit in sprintf at /home/centos/centreon-plugins/cloud/azure/custom/mode.pm line 102.
Use of uninitialized value in string eq at /home/centos/centreon-plugins/cloud/azure/custom/mode.pm line 92.
Use of uninitialized value $unit in sprintf at /home/centos/centreon-plugins/cloud/azure/custom/mode.pm line 102
=> (plugin) cloud::azure::compute::disk - fixing missing unit causing error in output

cloud/azure/compute/disk/mode/diskio.pm
Related to https://github.com/centreon/centreon-plugins/pull/3379
Not B/s but op/s and Output already is 'Disk Read Operations/sec: '
=> (plugin) cloud::azure::compute::disk - fixing wrong type of unit

storage/netapp/ontap/snmp/mode/clusternodes.pm
wrong description: --filter-node-id
correct description: --filter-node-name
=> netapp clusternodes: wrong description

apps/pvx/restapi/custom/api.pm
Sometimes users want to set a default value when no data is returned by PVX (Some kind of --zeroed parameter). 
Here we allow setting any value the user might want to set to identify that PVX didn't return any data back.
=> (plugin) apps::pvx::restapi - add default-value parameter

apps/ipfabric/mode/discovery.pm
Adding loginIp variable missing from disco output
=> (plugins) apps::ipfabric - adding missing var for discovery

cloud/aws/custom/awscli.pm
User can now use authentication through AssumeRole with awscli custom mode. 
Fixes plugin part of https://github.com/centreon/centreon-plugin-packs/issues/964.
=> (custom) cloud::aws::custom::awscli - adding AssumeRole auth for awscli

cloud/aws/elb/network/mode/targetshealth.pm
Wrong namespace fixed and adding new option to specify ELB target-group.
=> (plugin) cloud::aws::elb::network - fix namespace in targetshealth mode and add target-group dimension

network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
It happens if you don't have MX devices on your organization
=> (plugin) network::cisco::meraki::cloudcontroller::restapi - ignore 404 codes for uplinksLossAndLatency api call

hardware/server/hp/proliant/snmp/mode/components/fan.pm, hardware/server/hp/proliant/snmp/mode/components/psu.pm, hardware/server/hp/proliant/snmp/mode/components/temperature.pm, hardware/server/hp/proliant/snmp/mode/hardware.pm
=> (plugin) hardware::server::hp::proliant::snmp mode hardware - force new perfdata

apps/ipfabric/mode/discovery.pm
Adding platform property in host discovery output.
=> (plugin): apps::ipfabric - add platform in host discovery output

cloud/azure/database/mariadb/mode/replication.pm, cloud/azure/database/mariadb/mode/storage.pm
* Fix little typo in counter label resulting in wrong threshold name for storage serverlog. 
May break output if users used --warning-servelog-usage or --critical-servelog-usage.
* Fixing help for replication mode.
=> (plugin) cloud::azure:database::mariadb - fix typo in label

apps/monitoring/kadiska/mode/listtargets.pm, apps/monitoring/kadiska/mode/nettracerstatistics.pm, apps/monitoring/kadiska/mode/tracerstatistics.pm, apps/monitoring/kadiska/mode/watcherstatistics.pm, apps/monitoring/kadiska/plugin.pm
Apply enhancement suggestions :
- use target_name instead of tracer_id for listtargets.pm and nettracerstatistics.pm
- rename tracer-statistics in favor of nettracer-statistics
- add loading page duration for watchers
=> (plugin) apps::monitoring::kadiska - apply suggestions 

apps/protocols/tcp/mode/connectionstatus.pm, apps/protocols/tcp/mode/responsetime.pm, apps/protocols/tcp/plugin.pm
Hi,
This PR adds a proper TCP `responsetime` mode which mimics :
- `check_icmp` binary ;
- `apps::protocols::snmp::mode::responsetime` mode.
The main purpose of this new TCP `responsetime` mode is to be used as a host check, when `check_icmp` can't be used.
Think about for example of a Windows host (with NSClient++) behind a router / firewall.
This new TCP `responsetime` mode will then allow to check the availability of host, computing proper already known `rta` / `rtmin` / `rtmax` / `pl` perfdata.
Current `apps::protocols::tcp::mode::responsetime` mode has then been renamed to a more appropriated `apps::protocols::tcp::mode::connectionstatus` mode.
Many thx 👍
=> (plugin) apps::protocols::tcp - add responsetime mode and rename existing one into connectionstatus

network/cisco/meraki/cloudcontroller/restapi/mode/devices.pm
Add filter-switch-port
Allow to filter swicth port  when add-swicth-port is activated.
=> (plugin) [network::cisco::meraki::cloudcontroller::restapi::plugin] - Add filter option for swicth port

cloud/aws/backup/plugin.pm
Fix AWS backup mode job-status name for compliance.
Adding a '-'.
=> (plugin) cloud::aws::backup - fix mode name for compliance

apps/monitoring/nodeexporter/linux/mode/cpu.pm, apps/monitoring/nodeexporter/linux/mode/listinterfaces.pm, apps/monitoring/nodeexporter/linux/mode/liststorages.pm, apps/monitoring/nodeexporter/linux/mode/load.pm, apps/monitoring/nodeexporter/linux/mode/memory.pm, apps/monitoring/nodeexporter/linux/mode/storage.pm, apps/monitoring/nodeexporter/linux/mode/traffic.pm, apps/monitoring/nodeexporter/linux/plugin.pm
Modifying plugin paths and correcting interface discovery keys names
=> (plugin) apps::monitoring::linux::nodeexporter - correct paths and disco keys name

apps/ceph/restapi/custom/api.pm
Hello this is a quick fix to add header ''Accept: application/vnd.ceph.api.v1.0+json'
=> (plugin) ceph::restapi -- add 'Accept: application/vnd.ceph.api.v1.0+json' header

cloud/microsoft/office365/azuread/mode/directorysizeusage.pm, cloud/microsoft/office365/azuread/plugin.pm, cloud/microsoft/office365/custom/graphapi.pm
New plugin to check Azure AD stuff.
1 mode in included for now but some others may follow in the future
/usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::microsoft::office365::azuread::plugin --custommode='graphapi' --mode='directory-size-usage' --tenant='xxx' --client-id='xxx' --client-secret='xxx'
WARNING: Directory size usage : 264943/309000 (85.74%) | …
=> cloud::microsoft::office365::azuread - add Directory Size usage check (AD Quota)

os/as400/connector/mode/jobs.pm
Allow user to only count jobs with MSGW (or other) state(s).
=> (os::as400::connector::jobs) Add filtering capability on JOB_ACTIVE_STATUS

apps/monitoring/nodeexporter/windows/mode/listinterfaces.pm, apps/monitoring/nodeexporter/windows/mode/listservices.pm, apps/monitoring/nodeexporter/windows/mode/liststorages.pm, apps/monitoring/nodeexporter/windows/plugin.pm
Adding mode to list services on a Windows server based on node exporter metrics.
=> (plugin) apps::monitoring::nodeexporter::windows - adding list services mode

apps/monitoring/nodeexporter/linux/mode/storage.pm, apps/monitoring/nodeexporter/windows/mode/storage.pm
Fixing storage mode output for both windows and linux node exporter plugins
Removing default filter in storage mode for linux node exporter plugin
=> (plugin) apps::monitoring::nodeexporter - fixing storage output and remove default filter

cloud/azure/management/recovery/mode/backupjobsstatus.pm
Modify counter type in backup job status mode to prevent `unknown option` error.
=> (plugin) cloud::azure::management::recovery - modify counter type

network/cisco/umbrella/snmp/mode/appliance.pm
Fixing regex for UNKNOWN default state in appliance.pm mode
=> (plugin) network::cisco::umbrella - Fix regex in appliance.pm mode

cloud/azure/custom/azcli.pm
Adding missing function that was causing error when using --lookback option for backup-jobs-status mode from Azure recovery management plugin.
=> (plugin) cloud::azure::custom::azcli - adding missing function to azcli custom mode

cloud/azure/custom/api.pm, cloud/azure/custom/azcli.pm, cloud/azure/management/recovery/mode/listreplicateditems.pm, cloud/azure/management/recovery/mode/replicationhealth.pm, cloud/azure/management/recovery/plugin.pm
Adding mode to Azure management recovery plugin to monitor replication and failover health.
Closes https://github.com/centreon/centreon-plugins/issues/3726.
=> (plugin) cloud::azure::management::recovery - adding mode to monitor Azure replication health

network/efficientip/snmp/mode/status.pm
Fix non existent mapping state
=> (plugin) network::efficientip::snmp::mode::status - removing testing var

apps/monitoring/openmetrics/mode/scrapemetrics.pm
=> (plugin) apps::monitoring::openmetrics - Getting rid of single quote in instance filter (scrapemetrics.pm)

cloud/azure/management/recovery/mode/backupjobsstatus.pm
Change key word for --loopback option from endTime to startTime to prevent bug when key word doesn't exist.
=> (plugin) cloud::azure::recovery::backupjobstatus - fix bug on loopback option 

centreon/plugins/alternative/Getopt.pm
Now we can use following syntax (option[=[0|1]]):
```
perl centreon_plugins.pl --plugin=os/linux/snmp/plugin.pm --mode=interfaces --hostname=127.0.0.1 --statefile-dir=/tmp  --verbose  --add-duplex-status=1
CRITICAL: Interface 'enp0s31f6' Status : down (admin: up) (duplex: unknown) - Interface 'anbox0' Status : down (admin: up) (duplex: n/a) 
Interface 'lo' Status : up (admin: up) (duplex: n/a)
Interface 'enp0s31f6' Status : down (admin: up) (duplex: unknown)
Interface 'wlp1s0' Status : up (admin: up) (duplex: n/a)
Interface 'anbox0' Status : down (admin: up) (duplex: n/a)
Interface 'tun0' Status : up (admin: up) (duplex: n/a)
```
```
perl centreon_plugins.pl --plugin=os/linux/snmp/plugin.pm --mode=interfaces --hostname=127.0.0.1 --statefile-dir=/tmp  --verbose  --add-duplex-status=0 …
```
=> (core) can use variable to defined unitary options

apps/monitoring/splunk/custom/api.pm, apps/monitoring/splunk/mode/indexupdate.pm, apps/monitoring/splunk/mode/query.pm, apps/monitoring/splunk/mode/splunkdhealth.pm, apps/monitoring/splunk/plugin.pm
New plugin to monitor Splunk.
Checks available: 
- index last update
- result number for a query 
- global splunkd health, by feature
=> (plugin) apps::monitoring::splunk - adding plugin to monitor Splunk

centreon/plugins/nrpe.pm
Fix ssl_opt variable when calling centreon::plugins::misc::eval_ssl_options
Error introduced by https://github.com/centreon/centreon-plugins/commit/71d000525cb1badcbe568a9265bc7da55e74c12f
Actual code failed when using NRPE to check a host when it's required to disable the SSL verification : 
```
./centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --custommode=nrpe --mode=query --hostname=127.0.0.1 --nrpe-version=2 --nrpe-port=5666 --command="check_uptime" --nrpe-use-ipv4 --ssl-opt "SSL_verify_mode => SSL_VERIFY_NONE"
UNKNOWN: No response from remote host. 
```
Because the ssl-opt from command line are not taken correctly.
=> Fix variable for ssl_opt option

snmp_standard/mode/interfaces.pm
Options --warning-total-admin-up and  --critical-total-admin-up are unknown (bad name between global/total)
Extract from the help message of any snmp interfaces plugin:
```
/usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --help
--warning-* --critical-*
Thresholds. Can be: 'total-port', 'total-admin-up',
'total-admin-down', 'total-oper-up', 'total-oper-down',
'in-traffic', 'out-traffic', 'in-error', 'in-discard',
'out-error', 'out-discard', 'in-ucast', 'in-bcast', 'in-mcast',
'out-ucast', 'out-bcast', 'out-mcast', 'speed' (b/s).
```
Command successfull with admin down:
```
/usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces …
```
=> Fix option name in snmp interfaces plugin

apps/monitoring/splunk/mode/splunkdhealth.pm
Should fix https://github.com/centreon/centreon-plugins/issues/4008.
=> (plugin) apps::monitoring::splunk - Fixing blank output for splunkd health mode

storage/huawei/oceanstor/snmp/mode/listluns.pm, storage/huawei/oceanstor/snmp/mode/luns.pm, storage/huawei/oceanstor/snmp/plugin.pm
adding huawei oceanstor "lun" usage and discovery
tested on Huawei storage with dorado v6 and v5 OS on multiple hardware
this will get individual lun disk usage on oceanstor device with block (Lun) allocated
the plugin was initially based on the storage-pool plugin, removing "statuses" and adding a new metric "protection" which correspond to the number of bytes all the snapshots and protection feature on oceanstore uses on a lun
and finally I had to rewrite  everything after the selection, as the filter and philosophy behind a lun is different from the pool
Auto-discover is filtering on an OID "hwInfoLunExposedToInitiator" which tells if the lun is presented (usable) to a host
(all snaphot are Lun not exposed, it makes no sense to discover or list these lun)
I added a …
=> [storage::huawei::oceanstor::snmp::plugin] add lun discover and check usage

cloud/azure/network/expressroute/mode/traffic.pm
Closes https://github.com/centreon/centreon-plugins/issues/4016
=> (plugin) cloud::azure::network::expressroute - fix wrong perfdata name in traffic mode

cloud/azure/custom/api.pm, cloud/azure/management/costs/mode/costsexplorer.pm, cloud/azure/management/costs/mode/querysubscriptions.pm, cloud/azure/management/costs/plugin.pm
Adding mode to check subscriptions costs, per subscription and resource groups. 
It is also possible to filter per tags.
=> (plugin) cloud::azure::management::cost - adding mode to query subscription costs

storage/netapp/ontap/restapi/mode/aggregates.pm, storage/netapp/ontap/restapi/mode/listvolumes.pm
Fixing missing space usage counters as well as missing option to filter on aggregate name for aggregate mode. 
Fixing bug in list-volumes output. 
Should close https://github.com/centreon/centreon-plugins/issues/4025
=> (plugin) storage::netapp:ontap::restapi - fix missing counters for space usage and bug in listvolumes

cloud/aws/cloudwatch/mode/discovery.pm
Commenting both DynamoDB and VPC discovery calls to prevent errors in Centreon autodiscovery because of missing host templates.
=> (plugin) cloud::aws::cloudwatch::discovery - removing VPC and DynamoDB discovery

cloud/azure/database/sqldatabase/mode/health.pm
Change option names to match options defined in cloud/azure/management/monitor/mode/health.pm
**Fixes** MON-16411
=> (plugin) cloud::azure::database::sqldatabase::plugin - fix health options

cloud/azure/database/sqldatabase/mode/deadlocks.pm
Change the metric name from deadlocks to deadlock
Before the change, we had this error message:
> "Failed to find metric configuration for provider: Microsoft.Sql, resource Type: servers/databases, metric: deadlocks, Valid metrics: cpu_percent,physical_data_read_percent,log_write_percent,storage,connection_successful,connection_failed,connection_failed_user_error,blocked_by_firewall,deadlock,storage_percent,xtp_storage_percent,workers_percent,sessions_percent,sessions_count,cpu_limit,cpu_used,sqlserver_process_core_percent,sqlserver_process_memory_percent,tempdb_data_size,tempdb_log_size,tempdb_log_used_percent,app_cpu_billed,app_cpu_percent,app_memory_percent,allocated_data_storage,full_backup_size_bytes,diff_backup_size_bytes,log_backup_size_bytes,ledger_digest_upload_success,ledger_dige …
=> (plugin) cloud::azure::database::sqldatabase::plugin - fix deadlocks metric name

apps/protocols/x509/custom/https.pm
Add --no-follow parameter to ignore http redirects in x509 certificate check
**Fixes** #4130
Setup a https website which produces a 301/302 redirect and check the x509 with --debug to see two requests beeing generated. After this is verified use --no-follow to suppress the second request
=> (enh) apps::protocols::x509::custom::https - add --no-follow

cloud/azure/database/sqldatabase/mode/health.pm
With the old resource type we get this error message:
> The Resource 'Microsoft.Sql/servers/databases' under resource group 'XXXXXXXXX' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
This command works after the fix:
`./centreon_azure_database_sqldatabase_api.pl --plugin=cloud::azure::database::sqldatabase::plugin --mode=health --custommode='api' --resource='xxxx-sql01/databases/Datawarehouse' --resource-group='XXXXXXXXXX' --subscription='xxx' --tenant='xxx' --client-id=’xxx' --client-secret=’xxx' `
**Fixes** MON-16411
=> (plugin) cloud::azure::database::sqldatabase::plugin - fix health resource type

src/centreon/common/airespace/snmp/mode/listaps.pm, src/network/cisco/wlc/snmp/plugin.pm
Add a Service Discovery Rule to discover APs for Cisco WLC controllers
=> Add a Service Discovery Rule to discover APs for Cisco WLC controllers

src/centreon/plugins/passwordmgr/centreonvault.pm
Add Centreon Vault mode
Use by default Centreon Vault Storage configuration from  /etc/centreon-engine/centreonvault.json
If `--pass-manager=centreonvault`is set, find predefined pattern form options value to create map-option list, then get values from vault.
Example of command line:
`/usr/lib/centreon/plugins/centreon_mysql.pl --plugin=database::mysql::plugin --mode=connection-time --host=127.0.0.1 --username='{_HOSTSQLUSER::secret::/centreon_vault/monitoring/hosts/1111-2222-3333-4444-5555}' --password='{_HOSTSQLPASSWORD::secret::/centreon_vault/monitoring/hosts/1111-2222-3333-4444-5555}' --pass-manager=centreonvault`
Linked to #1061
=> enh(passwdmgr): Add Centreon Vault mode

src/cloud/aws/custom/paws.pm
Fixing the following error when using the paws custom mode:
```
perl ../centreon-plugins/src/centreon_plugins.pl --plugin=cloud::aws::lambda::plugin --mode=invocations --custommode=paws
UNKNOWN: Cannot load module --custommode. 
syntax error at /home/itoussies/repos/centreon-plugins/src/cloud/aws/custom/paws.pm line 806, near "}" Missing right curly or square bracket at /home/itoussies/repos/centreon-plugins/src/cloud/aws/custom/paws.pm line 844, at end of line Compilation failed in require at /home/itoussies/repos/centreon-plugins/src/centreon/plugins/misc.pm line 223.
```
=> (plugin) cloud::aws::custom::paws - fix

src/apps/monitoring/kadiska/mode/watcherstatistics.pm
Kadiska API can return values with 8+ decimals, which is not pretty. 
This aims to format *time* metrics perfdatas as .2f instead of s
=> apps::monitoring::kadiska::plugin - fix metric format

src/apps/monitoring/splunk/custom/api.pm
having a fixed 1.5 seconds wait time to let splunk finish its query might be way too short. 
To have a better control of that, it adds two new parameters 
--splunk-wait
--splunk-retries
=> improve splunk api handling

packaging/centreon-plugin-Applications-Protocol-X509/pkg.json
Resolve "UNKNOWN: Cannot load module --custommode." when using the opensslcli custom mode with the packaged plugin.
=> apps::protocol::x509 - opensslcli custom mode - fix usage

.github/workflows/plugin-delivery.yml
do not stop delivery when one job fails
=> enh(ci): do not stop delivery when one job fails

packaging/centreon-plugin-Applications-Sailpoint-Identitynow-Restapi/deb.json, packaging/centreon-plugin-Applications-Sailpoint-Identitynow-Restapi/pkg.json, packaging/centreon-plugin-Applications-Sailpoint-Identitynow-Restapi/rpm.json, src/apps/sailpoint/identitynow/restapi/custom/api.pm, src/apps/sailpoint/identitynow/restapi/mode/listsources.pm, src/apps/sailpoint/identitynow/restapi/mode/searchcount.pm, src/apps/sailpoint/identitynow/restapi/mode/sourcehealth.pm, src/apps/sailpoint/identitynow/restapi/plugin.pm
```
perl centreon_plugins.pl --plugin=apps::sailpoint::identitynow::restapi::plugin --mode=source-health --tenant='mytenant' --client-id='***' --client-secret='***' --source-id='' --filter-name='' --filter-type='' --warning-sources-healthy='' --critical-sources-healthy='' --warning-sources-error='' --critical-sources-error='' --warning-sources-failure='' --critical-sources-failure='' --warning-sources-unchecked='' --critical-sources-unchecked='' --warning-health-status='' --critical-health-status='%{status} ne "SOURCE_STATE_HEALTHY"' --verbose
CRITICAL: Source 'Centreon' health status is 'SOURCE_STATE_FAILURE_SOURCE' | 'sources.status.healthy.count'=4;;;; 'sources.status.error.count'=0;;;; 'sources.status.failure.count'=1;;;; 'sources.status.unchecked.count'=0;;;;
Source 'Toto' health …
```
=> new(plugin): add sailpoint identitynow restapi plugin

.github/workflows/tests-functional.yml
Fix mockoon (use version 3 and not the latest)
=> (fix) Adapt plugins tests from bash to robot framework

packaging/centreon-plugin-Hardware-Sensors-Rittal-Cmc3-Snmp/pkg.json
missing include of uptime module in packaging
=> fix(pkg): missing include of uptime module

src/os/linux/local/mode/process.pm
When using the centreon_linux_ssh.pl probe with the following plugin:
/usr/lib/centreon/plugins/centreon_linux_ssh.pl --plugin=os::linux::local::plugin --mode=process
If I only use --add-cpu then the CPU is always zero. This is because tail output with a single file is not in the same format as when used with several files.
Example with a single file:
user@XXX:/proc/1416$ bash -c 'tail -n +1 /proc/1416/statm'
0 0 0 0 0 0 0
Example with several files:
user@XXX:/proc/1416$ bash -c 'tail -n +1 /proc/1416/{statm,stat}'
==> /proc/1416/statm <==
0 0 0 0 0 0 0
==> /proc/1416/stat <==
1416 (xfs-data/dm-11) S 2 0 0 0 -1 69247072 0 0 0 0 0 0 0 0 0 0 -20 1 0 489 0 0 18446744073709551615 0 0 0 0 0 0 0 0 0 2147483647 0 18446744073709551615 0 0 17 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
However, the …
=> fix(plugin) Always output headers giving file names to avoid issues.

src/network/citrix/netscaler/snmp/mode/components/psu.pm
According to customer tests and to the following article, it seems 0 and 3 values were inverted:
https://support.citrix.com/article/CTX133887/citrix-adc-system-counters
**Fixes** MON-21051
=> Change mapping values for PSU

src/network/mikrotik/snmp/mode/listssids.pm
https://thewatch.centreon.com/data-usage-and-visualization-38/mikrotik-snmp-plugin-2127
A missing dot prevents the plugin SSIDs list from being displayed
=> fix(plugin): network::mikrotik::snmp - fix the SSIDs listing

src/apps/monitoring/kadiska/mode/alerts.pm, src/apps/monitoring/kadiska/mode/listalertrules.pm, src/apps/monitoring/kadiska/mode/listrules.pm, src/apps/monitoring/kadiska/plugin.pm
Retrieve rules alerts from Kadiska with new mode alerts.
New discovery service for rules alerts.
To test this PR you need access to Kadiska credentials (client-id and client-secret)
Also you need to set up alert rules 
Example how to test alerts.pm : (period=120 minutes => 2 hours)
```
perl centreon_plugins.pl     --plugin=apps::monitoring::kadiska::plugin --mode=alerts --client-id=CLIENT_ID --client-secret=CLIENT_SECRET --period=120 --verbose
```
Example how to test listrules.pm : (period=120 minutes => 2 hours)
```
perl centreon_plugins.pl     --plugin=apps::monitoring::kadiska::plugin --mode=list-rules --client-id=CLIENT_ID --client-secret=CLIENT_SECRET --period=120 --verbose
```
=> [Plugins] - MON-16256 Retrieve alerts from kadiska

src/os/linux/local/mode/cpu.pm, src/os/linux/local/mode/cpudetailed.pm, src/os/linux/local/mode/filesdate.pm, src/os/linux/local/mode/filessize.pm, src/os/linux/local/mode/inodes.pm, src/os/linux/local/mode/packeterrors.pm, src/os/linux/local/mode/quota.pm, src/os/linux/local/mode/storage.pm, src/os/linux/local/mode/systemdjournal.pm, src/os/linux/local/mode/traffic.pm, src/os/linux/local/mode/uptime.pm, src/os/linux/local/plugin.pm
Simple mode to read systemd journal and count entries based on unit name and message content.
```
OK: Emails sent: 17 | 'emails.sent.count'=17;;;0;
```
```
OK: Journal entries: 1 | 'journal.entries.count'=1;;;0;
```
```
OK: Centreon Engine reloads over the last hour: 0 | 'centreon.engine.reload.count'=0;;;0;
```
=> (plugin) os::linux::local - add mode systemd-journal

src/apps/protocols/http/mode/collection.pm, src/apps/protocols/snmp/mode/collection.pm, src/centreon/common/protocols/sql/mode/collection.pm
Add a second2human function to translate a duration in seconds to a human readable string:
```
{
"type": "second2human",
"src": "%(duration)",
"save_value": "%(humanDuration)",
"start": "d",
}
```
=> mode collection: add second2human function

src/apps/centreon/local/mode/notsodummy.pm
Add the posibility to fix a duration in second to this plugin execution with a sleep usage.
This duration is randomly chosen in a range set by the user with min and max duration option.
Duration is a float number that can be set with integer or float values.
```perl centreon_plugins.pl --plugin=apps::centreon::local::plugin --mode=not-so-dummy --status-sequence='up,down,down' --host --output='Not so dummy host' --debug  --min-duration=0.5 --max-duration=10```
Duration needs to set min **and** max value
```perl centreon_plugins.pl --plugin=apps::centreon::local::plugin --mode=not-so-dummy --status-sequence='up,down,down' --host --output='Not so dummy host' --debug  --min-duration=0.5 --max-duration=```
min and max can't be string.
```perl …
```
=> [MON-21523] Plugin mode not-so-dummy - Add min and max duration to simulate plugin execution time

src/snmp_standard/mode/uptime.pm
Add 2 decimals to the perfdata
**Fixes** # MON-24355
=> (plugin) snmp_standard::mode::uptime - Add 2 decimals to the perfdata

.github/workflows/perl-openwsman.yml
When libopenwsman-perl is installed on bullseye amd64, the package installed is the one for arm64.
The problem is: the packages for bullseye arm64 and bullseye amd64 have the same name (libopenwsman-perl_2.7.2-2_amd64.deb instead of libopenwsman-perl_2.7.2-2_amd64.deb and libopenwsman-perl_2.7.2-2_arm64.deb)
=> [CTOR-151] Fix for Debian packaging : amd64 and arm64 packages have the same name

.github/workflows/plugin-delivery.yml
Avoid triggering promotes and delivery sources if a workflow dispatch event is sent and branch is stable.
Fixes #MON-30965
=> enh(delivery): no deliver source and promote on dispatch

.github/actions/deb-delivery/action.yml, .github/actions/package-nfpm/action.yml, .github/actions/rpm-delivery/action.yml, .github/workflows/perl-cpan-libraries.yml, .github/workflows/perl-openwsman.yml, dependencies/perl-openwsman/libwsman.yaml, dependencies/perl-openwsman/perl-openwsman.yaml, dependencies/perl-openwsman/sblim-sfcc.yaml
"Hot" release for openwsman dependencies
=> Release openwsman deps

.github/actions/promote-to-stable/action.yml
Use upload instead of copy for promote, as it is more reliable even if generating a bit more traffic.
This should mitigate the metadata issue encountered during promotion of packages (rpm or deb)
Fixes #MON-21835 #MON-32880
=> enh(ci): use upload instead of copy for promote for perl-cpan-libraries

packaging/centreon-plugin-Hardware-Storage-Ibm-Storwize-Ssh/deb.json, src/storage/ibm/storwize/ssh/mode/eventlog.pm
fix: Converting from epoch to normal date, format was not valid for `localtime()`
`/usr/lib/centreon/plugins//centreon_ibm_storwize_ssh.pl --plugin=storage::ibm::storwize::ssh::plugin --mode=eventlog --hostname='SAN_V7000_CE_CED1' --ssh-backend='sshcli' --ssh-username='nagios.adm' --verbose --retention=3600`
=> MON-21973-date-problem-on-storage-ibm-storwize-ssh-plugin-eventlog

src/centreon/plugins/output.pm
=> Add single quote in change-perfdata help

src/apps/backup/rubrik/restapi/mode/listjobs.pm
In rubrik Plugin, mode list-jobs, there can be results without id or other fields, leading to "use of uninitialized values" errors in sprintf output and XML errors in disco show output.
EDIT by @omercier 
REFS: CTOR-96
=> enh(mode): Rubrik RestAPI manage disco empty entries

src/apps/backup/rubrik/restapi/custom/api.pm, src/apps/backup/rubrik/restapi/mode/cache.pm, src/apps/backup/rubrik/restapi/mode/jobs.pm
- Added --filter-job-type option to cache mode to filter job type in query.
- Added --filter-object-type option to jobs mode to filter object type on selection.
- Added "locationName" and "objectType" fields to the jobs mode long output.
- Ignore jobs with status "Canceled", "Canceling", ou "CancelingScheduled"
- Take the last completed job status instead of the first one of the list
close https://github.com/centreon/centreon-plugins/issues/4646
=> [CTOR-96] Rubrik - Enhance jobs and cache modes

.github/workflows/spellchecker.yml
Correct the label use to disable the spell check action
`do-not-spell-check` convert in `do-not-spellcheck`
=> [CTOR-346] Change the label name to avoid checking the spelling in the github actions

src/apps/protocols/http/mode/jsoncontent.pm
`--data can get directly the request on the command line. But the info is not given in the help.`
just run : 
~/centreon-plugins/src/centreon_plugins.pl --plugin=apps::protocols::http::plugin  --mode=json-content --help
=> more info on --data

packaging/centreon-plugin-Hardware-Storage-DataCore-Sansymphony-Restapi/pkg.json
FIX:CTOR-439
fatpack configuration didn't include the datacore code
=> CTOR-439-datacore-plugin-bad-path-in-pkg-json-source-code-is-not-properly-fatpacked

src/snmp_standard/mode/stringvalue.pm
use case is the following
`SNMPv2-SMI::enterprises.1248.4.1.1.1.9.0 = STRING: "03 0000 0000 T1"`
i want to extract 03 because this is the status code of my projector
therefore, I use the following option in the string-value of the snmp protocol plugin
`--convert-custom-values='my @tanguy = split(/ /, $value); $value=$tanguy[0];'`
03 is a nice value,
`OK: value(s): 03`
but, I want to have a mapping and that's where the problem is
` --map-values='03=>normal'`
this will not work
that's because the mapping is done before the custom values mecanism
therefore, to have it work, I need to put
`--map-values='03 0000 0000 T1=>normal'`
But may be the 0000 0000 T1 is a dynamic value and therefore my mapping won’t work if they change. That’s why I need to be able to do the mapping on the custom value …
=> better compat between map-values and convert-custom-values options

src/os/linux/local/mode/storage.pm, tests/resources/spellcheck/stopwords.t
To display the real used space, we need to take into account the reserved space.
If we use the formula `Total = Used + Available` the reserved space is taken into account.
**Fixes** # CTOR-441
=> take into account reserved space

src/apps/protocols/cifs/mode/filescount.pm, src/apps/protocols/ftp/mode/filescount.pm, src/apps/protocols/sftp/mode/filescount.pm
allow files-count mode to use filter-file and max-depth together.
Before this patch when filter-file was used the max-depth was always 1.
REF:CTOR-258
See jira.
=> CTOR-258-cifs,sftp,ftp plugin now check recursively folders

.github/docker/packaging/Dockerfile.packaging-plugins-alma8, .github/docker/packaging/Dockerfile.packaging-plugins-alma9, .github/docker/packaging/Dockerfile.packaging-plugins-bookworm, .github/docker/packaging/Dockerfile.packaging-plugins-bullseye, .github/docker/packaging/Dockerfile.packaging-plugins-centos7, .github/docker/packaging/Dockerfile.packaging-plugins-jammy, .github/docker/testing/Dockerfile.testing-plugins-alma8, .github/docker/testing/Dockerfile.testing-plugins-alma9, .github/docker/testing/Dockerfile.testing-plugins-bookworm, .github/docker/testing/Dockerfile.testing-plugins-bullseye, .github/docker/testing/Dockerfile.testing-plugins-jammy, .github/workflows/perl-cpan-libraries.yml, .github/workflows/perl-json-path.yml
update JSON::Path library on alma8 to take same version as other OS.
This is a follow up of https://github.com/centreon/centreon-plugins/issues/4540, the root problem was in Exporter::Shiny, updating it to the same version as debian11/alma9 make everything work.
**Fixes** # CTOR-525
install the new library version and launch the plugin 
`/usr/lib/centreon/plugins/centreon_protocol_http.pl  --plugin='apps::protocols::http::plugin' --mode='json-content'`
the plugin should compile correctly.
=> CTOR-525-escalation-package-perl-json-path-wrong-version-missing-perl-exporter-easy-for-centreon-repo-23-04-23-10-el-8

.github/workflows/perl-cpan-libraries.yml
Package PAWS cpan library in our repository.
We saw that PAWS is a cpan library we don’t package, each client have to install it with cpan or cpanm.
This is blocking the test industrialisation, as we want  to test plugins by only installing the deb/rpm package, we do not want to add any un necessary library.
Must have of this ticket : PAWS library should be packaged by centreon as other perl dependancy that don’t have package.
**Fixes** CTOR-472
=> Adding Paws

.github/workflows/perl-cpan-libraries.yml
This PR add Mojo::IOLoop::Signal library to be built from cpan to a deb/rpm installable packet.
This lib will be required by gorgone pullwss module to correctly handle unix signal (sigterm/sighup).
as centreon-plugins release every month and gorgone twice a year the lib will be available for gorgone next release (24.10).
**Fixes** # (MON-34540)
The Mojo::IOLoop::Signal library should be installable from centreon repository in all OS version currenctly supported by centreon.
=> fix(gorgone) correctly handle gorgone pullwss module shutdown

.github/workflows/perl-cpan-libraries.yml
REFS: CTOR-376
Attempt to fix the fact that dnf installs the older standard perl-Exporter-Tiny rpm on Alma 8
=> fix(packaging): advertise that perl-Exporter-Shiny also provides *Tiny

.github/workflows/perl-cpan-libraries.yml
REF:MON-539
libzmq-4 is not available for arm architecture. This PR aim to build dependancy created with fpm from cpan in arm architecture
The next PR will add test of plugins on arm architecture, we can't make it on the same pr as lib are pushed to unstable only when merging to develop.
try to install centreon-plugin-virtualization-vmware2-connector-plugin, libzmq-libzmq4-perl should be installable (it's a dependancy of this plugin)
=> fix(cpan-libs) build cpan library for arm64 architecture

.github/PULL_REQUEST_TEMPLATE.md
Change pull request template (it's a PRseption).
Feel free to ask changed.
=> CTOR-174 Change Pull request template

.github/scripts/pod_spell_check.t, src/apps/microsoft/hyperv/2012/local/mode/nodeintegrationservice.pm, src/apps/trendmicro/iwsva/snmp/plugin.pm, src/centreon/common/powershell/hyperv/2012/nodeintegrationservice.pm, tests/resources/spellcheck/stopwords.t, tests/robot/apps/microsoft/hyperv/2012/local/nodeintegrationservice-2022.json, tests/robot/apps/microsoft/hyperv/2012/local/nodeintegrationservice.robot
REFS: CTOR-146
- Modified the powershell script and the perl code to adapt nodeintegrationservices to Hyperv2022
- Added tests with the result of the powershell script converted to JSON 
**Presumably** fixes #4603 (to be confirmed)
The provided tests make the perl processing work with the obtained data without the need to have an actual environment.
=> Ctor 146 escalation microsoft hyperv 2012 add option for powershell module version in node integration service mode

src/database/mysql/mode/databasessize.pm
REFS: CTOR-264
Enhanced the way the fragmentation is calculated.
**Fixes** #4761 
On a Centreon server:
```bash
/usr/lib/centreon/plugins//centreon_mysql.pl --plugin=database::mysql::plugin  --host=127.0.0.1 --username='centreon' --password='centreon' --port=''  --mode=databases-size --filter-database='^(?!(information_schema|performance_schema|test))' --filter-perfdata='database' --verbose --warning-table-frag=1
```
=> Ctor 264 plugin database mysql mode databasesize change the way we calculate the fragmentation rate

.github/workflows/perl-cpan-libraries.yml
Add missing dependencies for Paws (el8 & el9)
Build deb package with dh-make-perl instead of fpm
**Fixes** CTOR-472
=> fix(library and packaging): package dependencies for paws cpan library for el8/el9 and package paws without using fpm for debian

.github/workflows/perl-cpan-libraries.yml
Fix again perl Mojo::IOLoop::Signal library to be installable on alma8.
**Fixes** # Refs:MON-34540
once this lib is in unstable, try to install centreon-gorgone from this pr https://github.com/centreon/centreon/pull/4178
installation should work without error
=> MON-34540-gorgone-fix-perl-mojo-ioloop-signal-v3

packaging/centreon-plugin-Network-Aruba-Cppm-Snmp/pkg.json
this patch adds the missing snmp_standard::mode::swap dependency for aruba cppm
=> add missing swap dependency for aruba cppm

.github/actions/package-nfpm/action.yml, src/notification/microsoft/office365/teams/custom/workflowapi.pm, src/notification/microsoft/office365/teams/mode/alert.pm, src/notification/microsoft/office365/teams/plugin.pm
Add the ability to send notifications to Microsoft Teams using workflow.
Just use the option `--teams-workflow` instead of `--teams-webhook`.
**Fixes** #5100 
CTOR-758
=> enh(plugin): notification::microsoft::office365::teams::mode::alert - add workflow

src/apps/voip/3cx/restapi/custom/api.pm, src/apps/voip/3cx/restapi/plugin.pm, tests/resources/spellcheck/stopwords.t
REFS: CTOR-360
Attempt to take advantage of PR #4757 and keep compatibility with older versions.
**Fixes**: #4083 #4608 
As usual:
```bash
perl src/centreon_plugins.pl --plugin=apps::voip::3cx::restapi::plugin --mode system  --hostname=XXXXX --api-username=XXXXX --api-password=XXXXX
```
or with the version of your 3CX:
```bash
perl src/centreon_plugins.pl --plugin=apps::voip::3cx::restapi::plugin --mode system  --hostname=XXXXX --api-username=XXXXX --api-password=XXXXX --3cx-version 18.0.9.20
```
Specify your 3CX version:
```bash
perl src/centreon_plugins.pl --plugin=apps::voip::3cx::restapi::plugin --mode system  --hostname=XXXXX --api-username=XXXXX --api-password=XXXXX --3cx-version 18.0.4.1
```
Provide …
=> enh(custommode): add support of 3CX v18 and higher

src/storage/hp/primera/restapi/custom/api.pm
The custom API options (like --hostname or --api-username) are not shown during --help on a mode of the plugin.
This happens because the section name in add_help function must be case sensitive.
=> HPE Primera API OPTIONS not shown in --help

src/network/3com/snmp/mode/hardware.pm
On 3com network devices, a fan or psu is reported as "active" when working properly, and "deactive" when failed. The threshold regex for the "OK" status is configured too vaguely: a "deactive" status was considered "active" / "OK" as the string "active" is contained in "deactive". This fix ensures that the "OK" status starts (and ends) with "active".
Before this patch, a "deactive" fan is considered "OK" (Debug output is redacted for brevity) : 
```
`OK: All 12 components are ok [12/12 fans]. | 'count_fan'=12;;;;
.1.3.6.1.4.1.43.45.1.2.23.1.9.1.1.1.1.65536 = 65536
.1.3.6.1.4.1.43.45.1.2.23.1.9.1.1.1.1.196611 = 196611
.1.3.6.1.4.1.43.45.1.2.23.1.9.1.1.1.2.65536 = 1
.1.3.6.1.4.1.43.45.1.2.23.1.9.1.1.1.2.196611 = 2
Checking fans
Fan '65536' status is 'active' [instance: 65536]
Fan '196611' …
```
=> Fix 3com snmp fan/psu check

src/network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
Add partner key to Meraki API calls
**Fixes** CTOR-864
=> enh(plugin): add Centreon header for Meraki api calls

connectors/vmware/changelog, connectors/vmware/src/centreon/script/centreon_vmware.pm, connectors/vmware/src/centreon/vmware/common.pm
Increment version `3.2.6` ➡️  `3.3.0` for next release.
* Enhancement: add ability to read configuration from JSON file
* Enhancement: add ability to get the VMware credentials from a Centreon flavoured Hashicorp vault
=> enh(vmware-daemon): prepare release of version 3.3.0 with 24.10 connector release

packaging/centreon-plugin-Applications-Rubrik-Restapi/deb.json, packaging/centreon-plugin-Applications-Rubrik-Restapi/rpm.json, src/apps/backup/rubrik/restapi/mode/jobs.pm, tests/apps/backup/rubrik/restapi/applications-rubrik-restapi.json, tests/apps/backup/rubrik/restapi/cache.robot, tests/apps/backup/rubrik/restapi/jobs.robot
* Add objectType and locationName to the retention file to fix the following error message:
`Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/centreon_rubrik_restapi.pl line 1218.`
* Add new option to check the presence of job execution in the retention file (not cache file)
* Add tests
=> [CTOR-775] - Fix apps::backup::rubrik::restapi::mode::jobs long output

.github/workflows/as400.yml, as400/changelog, as400/connector.as400/pom.xml, as400/packaging/centreon-as400-daemon.yaml
* fix java dependencies (java 17 is now the standard target)
* fix packaged files issues with leftover macros
**Fixes** #CTOR-1013
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk`) or [SNMP …
=> fix(packaging): fix packaged files and java dependencies

packaging/centreon-plugin-Applications-Monitoring-Speedtest/deb.json, packaging/centreon-plugin-Applications-Monitoring-Speedtest/rpm.json
speedtest-cli isn't used by the plugin.
It only needs speedtest and we ask to download it from the official website.
By the way, speedtest-cli from debian repositories is in conflict with speedtest-cli from the official website.
**Fixes** # CTOR-952
=> Ctor 952 plugin deb only centreon plugin applications monitoring speedtest conflict with speedtest and speedtest cli binaries

src/cloud/aws/custom/awscli.pm, tests/resources/spellcheck/stopwords.txt
CTOR-958
enh(plugin): add cloudtrail in awscli custom command option
Community contribution https://github.com/centreon/centreon-plugins/pull/5086
//
=> Plugin(cloud::aws) - Custom(Awscli): Missing cloudtrail command in event lookup mode

src/database/mysql/mode/replication.pm
use the proper mariadb message when checking mysql replication state
- have a sql replication running
- on your master do some stupid shit such as 
```sql
CHANGE MASTER TO MASTER_HOST='debian-ha-2', MASTER_USER='wrong_user', MASTER_PASSWORD='centreon', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=328;
START SLAVE;
```
you'll now a failed slave replication thread running on your master server check it with your monitoring plugin and you'll get the following result
```bash
/usr/lib/centreon/plugins/centreon_mysql.pl --plugin=database::mysql::plugin --mode=replication --host=192.168.0.100 --port='3306' --username='centreon_repl' --password='centreon' --multiple --host='192.168.0.101' --port='3306' --username='centreon_repl' --password='centreon'  --unknown-connection-status='' …
```
=> use proper error message

src/storage/hp/primera/restapi/custom/api.pm
**Source** #5256 
Refs: CTOR-1032
PS: Thanks @rmorandell-pgum!
Robot tests still working.
=> fix(primera-restapi): retry authentication when the token is invalid

src/apps/eclipse/mosquitto/mqtt/mode/stringvalue.pm
Problème avec les options warning-regrexp et critical-regexp dans le mode string-value
**Fixes** CTOR-789
=> fix(eclipse-mosquitto-mqtt): fix stringvalue mode regexp threshold

.github/workflows/perl-cpan-libraries.yml
fix(packaging): do not package rpm for perl dependency common::sense
already available on crb and powertools repositories
**Fixes** MON-152660
=> fix(packaging): do not package rpm for perl dependency common::sense

connectors/vmware/changelog, connectors/vmware/packaging/centreon-plugin-virtualization-vmware-daemon.yaml, connectors/vmware/packaging/debian/centreon_vmware-default, connectors/vmware/packaging/debian/centreon_vmware-systemd, connectors/vmware/packaging/redhat/centreon_vmware-sysconfig, connectors/vmware/packaging/redhat/centreon_vmware-systemd, connectors/vmware/packaging/scripts/postinstall.sh, connectors/vmware/src/centreon/script/centreon_vmware.pm, connectors/vmware/src/centreon/script/centreon_vmware_convert_config_file, connectors/vmware/src/centreon/vmware/common.pm
- missing dependency on AlmaLinux
- /etc/(default|sysconfig)/centreon_vmware was ignored
- migrate the config file from .pm to .json
Refs: CTOR-1079
Try:
- a fresh install 
- an upgrade from a version using the legacy .pm config file
- an upgrade from a version using the .json config file
In every scenario, the result must be centroen_vmware running on the .json file and no .pm file must remain.
=> fix(packaging): various issues + migration to JSON config file

.github/workflows/perl-cpan-libraries.yml
Adding 2 missing perl libraries for Debian Bookworm : `Device::Modbus::RTU::Client` and `Device::Modbus::TCP::Client`
**Fixes** CTOR-1230
=> fix(library-and-packaging): adding missing libraries for bookworm

.github/workflows/as400.yml, .github/workflows/connector-vmware.yml, .github/workflows/docker-builder-packaging-plugins.yml, .github/workflows/docker-builder-testing-plugins.yml, .github/workflows/docker-builder-unit-tests.yml, .github/workflows/get-environment.yml, .github/workflows/nrpe.yml, .github/workflows/perl-cpan-libraries.yml, .github/workflows/perl-crypt-argon2.yml, .github/workflows/perl-filesys-smbclient.yml, .github/workflows/perl-json-path.yml, .github/workflows/perl-keepass-reader.yml, .github/workflows/perl-libssh-session.yml, .github/workflows/perl-net-curl.yml, .github/workflows/perl-openwsman.yml, .github/workflows/perl-vmware-vsphere.yml, .github/workflows/plink.yml, .github/workflows/plugins-selinux.yml, .github/workflows/plugins.yml, .github/workflows/set-pull-request-skip-label.yml
enh(ci): skip workflow when no change on PR
**Fixes** MON-152664
=> enh(ci): skip workflow when no change on PR

src/hardware/devices/video/axis/snmp/mode/components/fan.pm
The fan status mapping is not correct. Correct working cameras shows wrong fan status failed.
status 1 should be OK and not failed. Here is the MIB file description
[AXIS-ROOT-MIB.txt](https://github.com/user-attachments/files/18153766/AXIS-ROOT-MIB.txt)
[AXIS-VIDEO-MIB.txt](https://github.com/user-attachments/files/18153767/AXIS-VIDEO-MIB.txt)
Attached the MIB files
=>  hardware::devices::video::axis::snmp::mode::components::fan - Fix map fan status - false positive

src/hardware/devices/video/axis/snmp/mode/components/fan.pm, src/hardware/devices/video/axis/snmp/mode/components/psu.pm
OID duplicate in axis video SNMP plugin : 
[.1.3.6.1.4.1.368.4.1.2.1.3](https://github.com/search?q=repo%3Acentreon%2Fcentreon-plugins+path%3A%2F%5Esrc%5C%2Fhardware%5C%2Fdevices%5C%2Fvideo%5C%2Faxis%5C%2Fsnmp%5C%2Fmode%5C%2Fcomponents%5C%2F%2F+.1.3.6.1.4.1.368.4.1.2.1.3&type=code) 
The rights OIDs and mappings seems to be this ones : 
[1.3.6.1.4.1.368.4.1.2.1.3](https://oid-rep.orange-labs.fr/get/1.3.6.1.4.1.368.4.1.2.1.3  )
```
1.3.6.1.4.1.368.4.1.2.1.3
fanStatus OBJECT-TYPE
SYNTAX INTEGER { ok(1), failure(2) }
MAX-ACCESS read-only
STATUS current
DESCRIPTION
"The status of a fan."
```
[1.3.6.1.4.1.368.4.1.1.1.3](https://oid-rep.orange-labs.fr/get/1.3.6.1.4.1.368.4.1.1.1.3  )
```
1.3.6.1.4.1.368.4.1.1.1.3
powerSupplyStatus OBJECT-TYPE
SYNTAX INTEGER { ok(1), failure(2) }
MAX-ACCESS …
```
=> fix(Plugin(video::axis): wrong psu status oid

src/network/cisco/meraki/cloudcontroller/restapi/mode/discovery.pm
Based on #5228 
Refs: CTOR-1010
No tests provided.
=> enh(meraki-cloudcontroller-restapi): add --filter-model to discovery mode

src/apps/salesforce/restapi/custom/api.pm, src/hardware/server/sun/mgmt_cards/mode/showfaults.pm, src/hardware/server/sun/mgmt_cards/mode/showfaulty.pm, tests/resources/spellcheck/stopwords.txt
It made tests fail on connectors worflow.
Refs: CTOR-1197
=> fix(sun-mgmt): the default plink command was not applied

src/apps/protocols/smtp/lib/smtp.pm
Fixed errors popping in automated tests:
```
1) Failed on template: App-Protocol-SMTP-Message - command_name: App-Protocol-SMTP-Message - command_line: /usr/lib/centreon/plugins/centreon_protocol_smtp.pl --plugin=apps::protocols::smtp::plugin --mode=message --hostname= --username='' --password=''  --smtp-from='' --smtp-to='' --warning='' --critical=''  - stderr: Use of uninitialized value $stdout in scalar chomp at /usr/lib/centreon/plugins/centreon_protocol_smtp.pl line 138. - stdout: UNKNOWN: Unable to connect to SMTP: Connection refused 
2) Failed on template: App-Protocol-SMTP-Login - command_name: App-Protocol-SMTP-Login - command_line: /usr/lib/centreon/plugins/centreon_protocol_smtp.pl --plugin=apps::protocols::smtp::plugin --mode=login --hostname= --username='' --password='' …
```
=> fix(protocol-smtp): fixed chomp on undefined variable

src/network/colubris/snmp/mode/load.pm
Fixed the counter label for 15 minutes average load.
The wrong label caused the plugin to refuse --warning-15min options.
Refs: CTOR-1197
=> fix(colubris-snmp): fix labels to manage 15 minutes average thresholds

src/network/stormshield/api/mode/interfaces.pm
Currently values mapped are: 
```
my $map_state = { 0 => 'disabled', 1 => 'enabled' };
my $map_plugged = { 0 => 'unplugged', 1 => 'plugged' };
```
It should be:
```
my $map_state = { 0 => 'down', 1 => 'up' };
my $map_plugged = { 0 => 'passive', 1 => 'active' };
```
https://documentation.stormshield.eu/SNS/v4/en/Content/CLI_Serverd_Commands_reference_Guide_v4/Commands/serverd/MONITOR.INTERFACE.htm
CTOR-743
=> fix(stormshield/api): mode interfaces wrong mapped values'

src/centreon/plugins/output.pm, tests/os/linux/snmp/load.robot
Includes PR #5155 by @garnier-quentin and tests
Refs: CTOR-820
Tests provided in `tests/os/linux/snmp/load.robot`.
=> feat(option): added an option to alter output and exit code (#5155)

src/network/cisco/umbrella/snmp/mode/connectivity.pm
in the plugin the variable is "*-status" and not "connectivity"
=> Fix cisco umbrella connections threshold name in --help output

src/apps/monitoring/iplabel/ekara/restapi/mode/scenarios.pm, tests/resources/spellcheck/stopwords.txt
CTOR-1387
- Change status match
- Change timeframe option default value
Using internal datas
=> enh(apps::monitoring::iplabel::ekara::restapi): change status match and timeframe option default value CTOR-1387

src/os/as400/connector/custom/api.pm, src/os/as400/connector/mode/disks.pm, src/os/as400/connector/mode/jobs.pm, src/os/as400/connector/mode/listdisks.pm, src/os/as400/connector/mode/listsubsystems.pm, src/os/as400/connector/mode/subsystems.pm
We have the following error:
```
[1735910404] [7068] SERVICE ALERT: VICLOUD-AS400-A1;Job QALERT;UNKNOWN;SOFT;1;UNKNOWN: Previous request pending (started 1013 ms ago). Increase your check interval, and nagios check tyour bandwidth availability
````
There is a mechanism in as400 to avoid the stacking of the same request. I can be useful but there is a bug. So we need to patch it.
To have the error, you need to execute very quickly the following two requests (example):
```
centreon_plugins.pl --plugin=os::as400::connector::plugin ... --as400-hostname=10.30.2.2 --as400-username=user --as400-password=pass --mode=jobs --filter-name="job1"
centreon_plugins.pl --plugin=os::as400::connector::plugin ... --as400-hostname=10.30.2.2 --as400-username=user --as400-password=pass --mode=jobs …
```
=> fix(as400): fix previous pending request

src/storage/purestorage/flasharray/v2/restapi/mode/arrays.pm, src/storage/purestorage/flasharray/v2/restapi/mode/volumes.pm
Quick fixes in options for arrays and volumes modes
CTOR-1218
```
perl centreon_plugins.pl --plugin=storage::purestorage::flasharray::v2::restapi::plugin --mode=arrays --hostname=localhost --api-token=toto --perf-resolution='5m'
UNKNOWN: curl perform error : Couldn't connect to server 
```
```
ldubrunfaut@CNTR-PORT-A198:~/centreon-plugins/src$ perl centreon_plugins.pl --plugin=storage::purestorage::flasharray::v2::restapi::plugin --mode=arrays --hostname=localhost --api-token=toto --filter-resolution='5m'
Unknown option: filter-resolution at /home/ldubrunfaut/centreon-plugins/src/centreon/plugins/alternative/Getopt.pm line 81. 
```
- [x ] I have **rebased** my development branch on the base branch (develop).
=> fix(storage::purestorage::flasharray::v2::restapi): fixed wrong option filter-resolution in arrays and volumes mode CTOR-1218

src/hardware/server/cisco/ucs/snmp/mode/components/memory.pm, src/hardware/server/cisco/ucs/snmp/mode/equipment.pm, tests/resources/spellcheck/stopwords.txt
change count of memory unit behaviour
=> CTOR-1294-plugin-hardware-server-cisco-ucs-snmp-mode-equipment-wrong-count-when-using-threshold-overload-option

.github/docker/packaging/Dockerfile.packaging-plugins-java-alma8, .github/docker/packaging/Dockerfile.packaging-plugins-java-alma9, .github/docker/packaging/Dockerfile.packaging-plugins-java-bookworm, .github/docker/packaging/Dockerfile.packaging-plugins-java-bullseye, .github/docker/packaging/Dockerfile.packaging-plugins-java-jammy, .github/workflows/as400.yml, .github/workflows/get-environment.yml, as400/connector.as400/.gitignore, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/AbstractHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/CommandHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/DiskHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/JobHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/JobQueueHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/SubSystemHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/SystemHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/impl/disk/QyaspolYasp0300PcmlHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/msgqueue/CachedMessageQueueHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/msgqueue/MessageQueueHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/check/handler/wrkprb/WorkWithProblemHandler.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/client/IClient.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/client/impl/AbstractClient.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/dispatcher/check/CheckDispatcher.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/dispatcher/check/InputData.java, as400/connector.as400/src/main/java/com/centreon/connector/as400/dispatcher/client/impl/ClientDispatcherImpl.java, as400/connector.as400/src/test/java/com/centreon/connector/as400/check/handler/impl/SystemHandlerTest.java, src/os/as400/connector/custom/api.pm, tests/resources/spellcheck/stopwords.txt
Includes PR #5383 by @garnier-quentin
Add capability to use AS400 SSL connection.
The plugin has a new option: ```--ssl```.
For the SSL connection, the port 9475 must be opened from the poller. If you check it, you surely have the error:
```
UNKNOWN: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
You need to import the target AS400 certificate on your poller. How could do that ?
Get the certificate (change the IP with your AS400 IP):
```
openssl s_client -showcerts -connect 192.168.23.13:9475
....
-----BEGIN CERTIFICATE-----
MIIBzTCCAXKgAwIBAgIHZ2AwVwa86DAKBggqhkjOPQQDAjBBMQswCQYDVQQGEwJJ
VDEMMAoGA1UECBMDSVRBMQswCQYDVQQKEwJBNDEXMBUGA1UEAxMOYTQuaG9yc2Eu …
```
=> enh(as400): add ssl connection option

src/storage/ibm/fs900/snmp/mode/hardware.pm, tests/resources/spellcheck/stopwords.txt
Remove wrong default value
CTOR-544
```
perl centreon_plugins.pl --plugin=storage::ibm::fs900::snmp::plugin --hostname=localhost --snmp-version=2c --snmp-community=local/fs900-test --snmp-port=2024 --mode=hardware --debug --component=all
UNKNOWN: Wrong option. Cannot find component 'all'. 
```
and
```
perl centreon_plugins.pl --plugin=storage::ibm::fs900::snmp::plugin --hostname=localhost --snmp-version=2c --snmp-community=local/fs900-test --snmp-port=2024 --mode=hardware --debug --component=.*
OK: All 0 components are ok []. 
Checking batteries
Checking fan modules
Checking fibre channels
Checking flashcards
Checking psu
```
=> fix(storage::ibm::fs900::snmp): remove wrong default value all CTOR-544

src/apps/eclipse/mosquitto/mqtt/mode/clients.pm, src/apps/eclipse/mosquitto/mqtt/mode/messages.pm, src/apps/eclipse/mosquitto/mqtt/mode/numericvalue.pm, src/apps/eclipse/mosquitto/mqtt/mode/uptime.pm, tests/apps/eclipse/mosquitto/mqtt/clients.robot, tests/apps/eclipse/mosquitto/mqtt/messages.robot, tests/apps/eclipse/mosquitto/mqtt/numeric-value.robot, tests/apps/eclipse/mosquitto/mqtt/string-value.robot, tests/apps/eclipse/mosquitto/mqtt/uptime.robot
Fix Mosquitto MQTT numeric-value mode.
**Fixes** CTOR-1447
=> fix(apps::eclipse::mosquitto::mqtt): mode numeric-value

.github/workflows/check-status.yml, .github/workflows/get-environment.yml, .github/workflows/gitleaks.yml, .github/workflows/set-pull-request-external-label.yml, .github/workflows/set-pull-request-skip-label.yml
Remove secret in order to allow dependabot and external PR to be able to run the gitleaks mandatory workflow
=> ci(secu): replace gitleaks secret and remove PRT

src/cloud/azure/storage/storagesync/mode/filessync.pm, src/cloud/azure/storage/storagesync/mode/recalls.pm, src/cloud/azure/storage/storagesync/mode/serverstatus.pm
Remove the metric storagesyncrecalliototalsizebytes because it's not supported:
https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-storagesync-storagesyncservices-metrics
**Fixes** # CTOR-1614
=> fix(cloud::azure::storage::storagesync): fixed recalls mode by removing deprecated StorageSyncRecallIOTotalSizeBytes metric CTOR-1614

packaging/centreon-plugin-Applications-Ibmmq-Mqi/deb.json, packaging/centreon-plugin-Applications-Ibmmq-Mqi/rpm.json
The perl mqseries library is going to be removed from centreon repository, so we need to remove the dependency.
**Fixes** CTOR-1639
=> enh(apps::mq::ibmmq::mqi): remove perl lib msqseries dependency

connectors/vmware/packaging/centreon-plugin-virtualization-vmware-daemon.yaml, connectors/vmware/packaging/config/logrotate/centreon_vmware
Add a logrotate file with:
- force rotate if size > 50M
- rotate weekly
- max 3 months
Refs: CTOR-1532
- Install the package
- run `logrotate /etc/logrotate.d/centreon_vmware`
=> enh(vmware-daemon): add missing logrotate file

packaging/centreon-plugin-Network-Firewalls-Fortinet-Fortigate-Snmp/pkg.json
Enhance plugin packaging by adding uptime 
CTOR-1662
[Possible bug in centreon_fortinet_fortigate.pl for mode=uptime option?](https://thewatch.centreon.com/data-collection-6/possible-bug-in-centreon-fortinet-fortigate-pl-for-mode-uptime-option-4695)
In a fresh env install the packaging: 
```
dnf install centreon-plugin-Network-Firewalls-Fortinet-Fortigate-Snmp
```
And try to run the `uptime` mode:
```
centreon_fortinet_fortigate.pl  --plugin=network::fortinet::fortigate::snmp::plugin --mode=uptime --hostname=localhost --snmp-version=2c --snmp-community='toto'
UNKNOWN: Cannot load module --mode.
Can't locate snmp_standard/mode/uptime.pm in @INC (you may need to install the snmp_standard::mode::uptime module) (@INC contains: /usr/lib/centreon/plugins …
```
=> enh(network::fortinet::fortigate::snmp): enhance plugin packaging to handle uptime CTOR-1662

src/database/mysql/dbi.pm, src/database/mysql/mysqlcmd.pm
Refs:CTOR-1562
The regex doesn't work for strings like '11.4.4-2-MariaDB-enterprise-log'. This PR adapts the regex to handle this case. 
The regex seems more complicated, `([0-9\.\-]*?)-MariaDB` would be sufficient but it doesn't return the same result as before. For example for `5.5.5-10.1.36-MariaDB`, the group 1 would be `5.5.5-10.1.36` instead of `10.1.36`. It's working fine so you tell me which one you prefer.
=> Plugin(database::mysql::plugin) - Mode(dbi,mysqlcmd): Error when retrieving the server version

src/storage/emc/datadomain/snmp/mode/cleaning.pm
Fixed issue when default value for timezone is empty leading to unknown
CTOR-1700
USing data available in the test repo
=> fix(storage::emc::datadomain::snmp): fixed issue in cleaning mode when default value for timezone is empty leading to unknown CTOR-1700

.github/workflows/centreon-plugins-sudoers.yml
* backport of https://github.com/centreon/centreon-plugins/pull/5663
* do not run delivery job for plugins-sudoers if packaging is not run
**Fixes** #MON-175664
=> fix(ci): run plugins-suoders delivery only if packaging is triggered

src/centreon/common/redfish/restapi/mode/components/chassis.pm
With the type of chassis "Enclosure", we don't have the status/health values.
We should exclude this type of chassis.
**Fixes** # CTOR-1798
=> fix(plugin) hardware::server::hp::ilo::restapi - Exclude enclosure

src/notification/email/mode/alert.pm
Add pathname variable to allow a custom pathname instead of http[s]://FQDN/centreon -> http[s]://FQDN/custom
Add pathname variable to allow a custom pathname instead of:
http[s]://FQDN/centreon -> http[s]://FQDN/custom
- set a new custom `centreon_pathname`
- set a custom `centreon_pathname`
- links should point to this new pathname
- default is `centreon`
=> enh(notification::email): Allow a custom pathname in alert mode

src/cloud/docker/restapi/mode/containerusage.pm, tests/cloud/docker/restapi/container.robot, tests/cloud/docker/restapi/docker.json
Refs:CTOR-1853
As reported on the[ Docker documention](https://docs.docker.com/reference/cli/docker/container/stats/):
> On Linux, the Docker CLI reports memory usage by subtracting cache usage from the total memory usage. The API does not perform such a calculation but rather provides the total memory usage and the amount from the cache so that clients can use the data as needed. The cache usage is defined as the value of total_inactive_file field in the memory.stat file on cgroup v1 hosts.
=> CTOR-1853 Plugin(cloud::docker::restapi) - Mode(container): fix memory usage calculation

src/apps/vmware/vsphere8/esx/mode.pm
In complement to #5772, an optimization that regards only ESX monitoring.
Refs: CTOR-1513
=> enh(vmware8::esx):  use statefiles to retain esx_id
