centreon/centreon-plugins

- hardware/server/dell/openmanage/mode/components/physicaldisk.pm
Add DiskSmartAlertIndication  to Dell physical disk control
> Extend Dell server openmanage to add DiskSmartAlertIndication check

- hardware/ups/mge/mode/environment.pm
In MG-SNMP-UPS-MIB file, the humidity measurement is in unit 0.1 % (upsmgEnvironmentHumidity) and the temperature measurement is in unit 0.1 Cel (upsmgEnvironmentTemperature).
> fix bug with unit for temperature and humidity (0.1 unit)

- apps/centreon/mysql/mode/pollerdelay.pm
Add "WHERE deleted=0" in the request
> Ignore deleted poller

- hardware/server/dell/idrac/snmp/mode/globalstatus.pm
bugfix https://github.com/centreon/centreon-plugins/commit/aeb31bbc3355ad0e0a667500acb2e5370537e96e
> + bugfix iDrac > 6 

- apps/kayako/mode/listdepartment.pm
- apps/kayako/mode/listpriority.pm
- apps/kayako/mode/liststaff.pm
- apps/kayako/mode/liststatus.pm
- apps/kayako/mode/ticketcount.pm
- apps/kayako/plugin.pm
> Plugin Kayako

- storage/synology/plugin.pm
> Change diskusage by storage mode

- apps/tomcat/jmx/plugin.pm
- centreon/common/jvm/mode/classcount.pm
- centreon/common/jvm/mode/cpuload.pm
- centreon/common/jvm/mode/fdusage.pm
- centreon/common/jvm/mode/loadaverage.pm
- centreon/common/jvm/mode/memory.pm
- centreon/common/jvm/mode/memorydetailed.pm
- centreon/common/jvm/mode/threadcount.pm
Add several modes for standard JVM, successfully tested on Tomcat - will add plugin.pm soon
> Common JVM

- storage/emc/vplex/restapi/custom/vplexapi.pm
- storage/emc/vplex/restapi/mode/clustercommunication.pm
- storage/emc/vplex/restapi/mode/clusterdevices
- storage/emc/vplex/restapi/mode/directors.pm
- storage/emc/vplex/restapi/mode/distribueddevices.pm
- storage/emc/vplex/restapi/mode/fans.pm
- storage/emc/vplex/restapi/mode/psus.pm
- storage/emc/vplex/restapi/mode/storagevolumes.pm
- storage/emc/vplex/restapi/plugin.pm
Will be subject to some enhancement in the near futur, to merge fans, psus, and probably management modules in a global hardware unified mode.
> EMC Vplex Monitoring through rest API

- database/oracle/mode/asmdiskgroupusage.pm
- database/oracle/plugin.pm
[root@###]# ./centreon_plugins.pl --plugin=database::oracle::plugin --mode=asm-diskgroup-usage --warning=90 --critical=95 --connect-options='ora_session_mode=32768' --hostname=##### --datasource="Oracle://#####:1521/+ASM" --username=### --password=###
OK: All diskgroup are ok. | 'dg_data_fc_usage'=606982897664B;0:628138967040;0:663035576320;0;697932185600 'dg_fra_sata_usage'=15384707072B;0:96636764160;0:102005473280;0;107374182400
> Check Oracle ASM diskgroup usage and statut

- network/alcatel/oxe/snmp/mode/pbxrole.pm
- network/alcatel/oxe/snmp/plugin.pm
Usefull for master-slave to detect a role turn main-standby
> Add pbx-role mode

- storage/emc/xtremio/restapi/custom/xtremioapi.pm
- storage/emc/xtremio/restapi/mode/clusterhealth.pm
- storage/emc/xtremio/restapi/mode/ssdendurance.pm
- storage/emc/xtremio/restapi/mode/ssdiops.pm
- storage/emc/xtremio/restapi/mode/xenvscpu.pm
- storage/emc/xtremio/restapi/mode/xenvsstate.pm
- storage/emc/xtremio/restapi/plugin.pm
Add first checks for EMC/Xtremio storage tech
> Add EMC/Xtremio first checks

- network/alcatel/common/mode/hardware.pm
Wrong display of components skip/count
> Fix minor bug on short output

- network/citrix/netscaler/common/mode/connections.pm
- network/citrix/netscaler/mpx8000/plugin.pm
- network/juniper/common/screenos/mode/sessions.pm
Add failed sessions monitoring https://github.com/centreon/centreon-plugins/issues/158
> Update sessions.pm https://github.com/centreon/centreon-plugins/issues/158

- storage/ibm/TS3100/mode/globalstatus.pm
- storage/ibm/TS3200/mode/globalstatus.pm
Adding two oids and display values with verbose mode for globalstatus.pm
> Add error description in verbose mode for IBM Storage DS3XXX

- os/aix/local/mode/errpt.pm
Tested and approved on AIX 6, now we can include or exclude some error code identifier
Thx
> Enhance os::aix::local::mode::errpt mode and fix minor bug

- apps/github/mode/stats.pm
- apps/github/plugin.pm
New mode "stats" for Github.
Retrieve : 
- Number of forks
- Number of watchs
- Number of stars
> Github: Add new mode to retreive repository information

- apps/protocols/x509/mode/validity.pm
#241 - Add SNI support (IO::Socket::SSL v1.56+ needed)
> SNI Support - closed #241

- hardware/server/cisco/ucs/mode/components/iocard.pm
- storage/netapp/snmp/plugin.pm
+ create cacheage.pm
+ update plugin.pm
> + Add cache age for Netapp 

- network/juniper/trapeze/snmp/mode/apstatus.pm
- network/juniper/trapeze/snmp/mode/apusers.pm
- network/juniper/trapeze/snmp/mode/cpu.pm
- network/juniper/trapeze/snmp/mode/memory.pm
- network/juniper/trapeze/snmp/plugin.pm
Issue
https://github.com/centreon/centreon-plugins/issues/284
> Add plugin for Juniper/Trapeze WLC

- database/oracle/mode/tablespaceusage.pm
Add a spesific sql request for Oracle >= 11
The new sql request used Oracle View DBA_TABLESPACE_USAGE_METRICS
Reduces the time of the request by the 20 large database
> + Update request for oracle >= 11

- centreon/common/powershell/exchange/2010/replicationhealth.pm
Fix typo s/replicatin/replication/
> MSExchange 2010 - Fix typo

- src/check_meta_service
> Fix sql request for sql matching meta_service

- apps/lync/2013/mssql/mode/appsharingqoe.pm
- apps/lync/2013/mssql/mode/audioqoe.pm
- apps/lync/2013/mssql/mode/sessionstypes.pm
- apps/lync/2013/mssql/mode/videoqoe.pm
Some enhanced and corrected modes for MS Lync 2013. 
Use the mssql dyn-mode. 
Thanks
> Lync 2013 MSSQL Monitoring

- hardware/sensors/temperhum/local/mode/environment.pm
- hardware/sensors/temperhum/local/plugin.pm
> + Add TemPerHum sensor monitoring

- hardware/sensors/temperhum/local/mode/environment.pm
> + Enhance code portability - fix mistypes

- apps/lync/2013/mssql/mode/lyncusers.pm
- apps/lync/2013/mssql/mode/poorcalls.pm
+ Poor calls count
+ Lync user count
> Add 2 modes for MS Lync 2013

- apps/github/mode/issues.pm
> Get only issue type ticket

- apps/pacemaker/local/mode/constraints.pm
- apps/pacemaker/local/plugin.pm
https://github.com/centreon/centreon-plugins/issues/29
> Check if resource need unmigrate #29

- centreon/common/fortinet/fortigate/mode/vpn.pm
- network/fortinet/fortigate/plugin.pm
https://github.com/centreon/centreon-plugins/issues/261
> Add Fortigate common VPN mode #261

- network/aerohive/snmp/mode/connectedusers.pm
- network/aerohive/snmp/plugin.pm
Ref https://github.com/centreon/centreon-plugins/issues/445
> [plugin] [aerohive] add plugin and connected user mode 

- docs/fr/developer/guide.rst
http://git.centreon.com/centreon-plugins.git do not exist
> Update git url

- cloud/docker/custom/dockerapi.pm
- cloud/docker/mode/blockio.pm
- cloud/docker/mode/containerstate.pm
- cloud/docker/mode/cpu.pm
- cloud/docker/mode/image.pm
- cloud/docker/mode/info.pm
- cloud/docker/mode/listcontainers.pm
- cloud/docker/mode/listnodes.pm
- cloud/docker/mode/memory.pm
- cloud/docker/mode/nodestate.pm
- cloud/docker/mode/traffic.pm
- cloud/docker/plugin.pm
> Docker mode

- apps/protocols/http/mode/jsoncontent.pm
- apps/protocols/http/mode/soapcontent.pm
- centreon/common/bluearc/snmp/mode/clusterstatus.pm
- network/juniper/trapeze/snmp/mode/apusers.pm
> Fixed found translation.

- apps/protocols/bgp/4/mode/bgppeerstate.pm
> + fix mistype on bgp options

- network/checkpoint/mode/hastate.pm
+ more flexibility on triggers
+ choose exit status when ha doesn't work or not installed
+ ref https://github.com/centreon/centreon-plugins/issues/373
> Enhance checkpoint hastate mode

- network/checkpoint/mode/memory.pm
Closed https://github.com/centreon/centreon-plugins/issues/337
> Enhance checkpoint memory mode

- apps/backup/netbackup/local/mode/jobstatus.pm
cf commit, may be command is not the right option to use in cache name, in this case I let you do the change, just close it ;)
> Fix netbackup/jobstatus little perl unitialized value

- centreon/common/fortinet/fortigate/mode/signatures.pm
- network/fortinet/fortigate/plugin.pm
+ check av / ips signature update
+ tested successfully by @jframeau  on Forti OS 4.x and 5.x
+ tested by me on Fortigate 1000C
+ Closed https://github.com/centreon/centreon-plugins/issues/512
> Add mode to check signatures on fortigate

- database/sybase/mode/databasessize.pm
See http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc31644.1550/html/sag2/sag2175.htm
> Take into account "data and log" segments to avoid negative values for log usage

- apps/protocols/bgp/4/mode/bgppeerstate.pm
Ref https://github.com/centreon/centreon-plugins/issues/639
> enhance behaviour when no peer matching filter

- notification/highsms/mode/alert.pm
- notification/highsms/plugin.pm
> add plugin HighSMS

- storage/dell/fluidfs/snmp/mode/hardware.pm
Ref https://github.com/centreon/centreon-plugins/issues/664
> Fix fluidfs ad component state

- os/linux/local/mode/process.pm
Fix https://github.com/centreon/centreon-plugins/issues/666
> Process local enhancement

- apps/jmeter/mode/scenario.pm
- apps/jmeter/plugin.pm
Inspired by the Selenium plugin, a new plugin to execute JMeter scenarios locally or by SSH.
Use the JMeter log file in XML format: http://jmeter.apache.org/usermanual/listeners.html
> + add plugin to execute JMeter scenario

- apps/pacemaker/local/mode/clustat.pm
- apps/pacemaker/local/plugin.pm
Ref https://github.com/centreon/centreon-plugins/issues/671
> Add possibility to monitor rhec cluster using clustat

- apps/lync/2013/mssql/mode/poorcalls.pm
> Total threshold doesn't exist

- apps/centreon/map/jmx/mode/gates.pm
The mode gate was not working anymore due to some changes in Map server
> Fix Map 4 plugin

- notification/foxbox/mode/alert.pm
- notification/foxbox/plugin.pm
usage : 
perl  ./centreon_plugins.pl --plugin=notification::foxbox::plugin --mode='alert' --from='centreon' --hostname '10.40.1.124' --username 'admin' --password 'centreon' --phonenumber '33612345678' --testo 'Service Alert: Central/proc-ntpd \nService State: CRITICAL \nDate/Time: Thu Jul 6 18:58:48 CEST 2017'
> sms with foxbox modem

- apps/redis/restapi/custom/api.pm
- apps/redis/restapi/mode/clusterstats.pm
- apps/redis/restapi/mode/databasesstats.pm
- apps/redis/restapi/mode/nodesstats.pm
- apps/redis/restapi/mode/shardsstats.pm
- Add more counters,
- Add interval option to select the interval from which to retreive the statistics,
- Remove statefile as it is not used.
> improve redis restapi

- database/mssql/mode/logssize.pm
- database/mssql/plugin.pm
- Add logs-size mode to monitor databases logs size using _DBCC SQLPERF(LOGSPACE)_ request,
- Reorganize mode list.
> add mssql logssize mode

- database/oracle/mode/eventwaitsusage.pm
- Thresholds are *-event-count, not *-count,
- Useless custom function.
> fix oracle eventwaitsusage

- snmp_standard/mode/spanningtree.pm
Closes https://github.com/centreon/centreon-plugins/issues/780
> Refactor and enhance spanning tree common mode #780

- hardware/ups/apc/snmp/mode/sensors.pm
Display temperature and humidity in long output.
> Improve apc sensors mode

- apps/kaspersky/snmp/mode/deployment.pm
- apps/kaspersky/snmp/mode/events.pm
- apps/kaspersky/snmp/mode/fullscan.pm
- apps/kaspersky/snmp/mode/logicalnetwork.pm
- apps/kaspersky/snmp/mode/protection.pm
- apps/kaspersky/snmp/mode/updates.pm
- apps/kaspersky/snmp/plugin.pm
Add plugin to monitor Kaspersky Security Center through SNMP.
> Add kaspersky plugin

- storage/netapp/restapi/custom/restapi.pm
- storage/netapp/restapi/mode/aggregateraidstatus.pm
- storage/netapp/restapi/mode/aggregatestatus.pm
- storage/netapp/restapi/mode/aggregateusage.pm
- storage/netapp/restapi/mode/clusterio.pm
- storage/netapp/restapi/mode/clusterstatus.pm
- storage/netapp/restapi/mode/clusterusage.pm
- storage/netapp/restapi/mode/diskfailed.pm
- storage/netapp/restapi/mode/diskspare.pm
- storage/netapp/restapi/mode/fcportstatus.pm
- storage/netapp/restapi/mode/listaggregates.pm
- storage/netapp/restapi/mode/listclusters.pm
- storage/netapp/restapi/mode/listfcports.pm
- storage/netapp/restapi/mode/listluns.pm
- storage/netapp/restapi/mode/listnodes.pm
- storage/netapp/restapi/mode/listsnapmirrors.pm
- storage/netapp/restapi/mode/listvolumes.pm
- storage/netapp/restapi/mode/lunalignment.pm
- storage/netapp/restapi/mode/lunonline.pm
- storage/netapp/restapi/mode/lunusage.pm
- storage/netapp/restapi/mode/nodefailoverstatus.pm
- storage/netapp/restapi/mode/nodehardwarestatus.pm
- storage/netapp/restapi/mode/qtreestatus.pm
- storage/netapp/restapi/mode/snapmirrorstatus.pm
- storage/netapp/restapi/mode/snapmirrorusage.pm
- storage/netapp/restapi/mode/volumeio.pm
- storage/netapp/restapi/mode/volumestatus.pm
- storage/netapp/restapi/mode/volumeusage.pm
- storage/netapp/restapi/plugin.pm
Built for OnCommand API 4.0, might work with 3.0, 2.0 and 1.0.
> Add netapp restapi plugin

- storage/netapp/restapi/custom/restapi.pm
Fix uri uninitialized option in restapi custom mode of NetApp plugin.
> Fix uri uninitialized option

- storage/netapp/restapi/mode/snapmirrorstatus.pm
- storage/netapp/restapi/mode/snapmirrorusage.pm
Bad key used in long output messages.
> Fix snapmirror modes debug output

- cloud/aws/ec2/mode/status.pm
Closes https://github.com/centreon/centreon-plugins/issues/945
> + AWS plugin el6 / perl 5.10 compatibilty

- network/sonicwall/snmp/mode/connections.pm
- network/sonicwall/snmp/mode/cpu.pm
- network/sonicwall/snmp/mode/memory.pm
- network/sonicwall/snmp/mode/vpn.pm
- network/sonicwall/snmp/plugin.pm
- snmp_standard/mode/spanningtree.pm
Closes https://github.com/centreon/centreon-plugins/issues/914
Waiting for @oasisck to test it before merge. 
Thanks
> Sonicwall plugin

- network/f5/bigip/snmp/mode/failover.pm
> fix f5 bigip failover warning thresholds

- network/f5/bigip/snmp/mode/trunks.pm
It fixes thresholds management.
> fix f5 bigip trunks

- snmp_standard/mode/interfaces.pm
Add interface speed check.
To check if my 'ens33' interface is a 10Gbits/s : 
```
CRITICAL: Interface 'ens33' Speed : 1.00Gb/s | 'speed'=1000000000b/s;;10000000000:;0;
```
Refs: #762, #954
> add snmp_standard interfaces speed check

- storage/netapp/snmp/mode/qtreeusage.pm
Refactor to use counter template.
Add --not-kbytes option for some cases where used and total values are not expressed in kilobytes but in bytes in oids.
Fix: https://github.com/centreon/centreon-plugins/issues/1006
> refacto netapp qtreeusage and add not-kbytes option

- cloud/cloudfoundry/restapi/custom/api.pm
- cloud/cloudfoundry/restapi/mode/appsstate.pm
- cloud/cloudfoundry/restapi/mode/instancesstate.pm
- cloud/cloudfoundry/restapi/mode/listapps.pm
- cloud/cloudfoundry/restapi/mode/listorganizations.pm
- cloud/cloudfoundry/restapi/mode/listspaces.pm
- cloud/cloudfoundry/restapi/plugin.pm
Add Cloud Foundry plugin.
Tested on API v2, not sure about v3.
> add cloudfoundry plugin (wip)

- apps/selenium/mode/scenariokatalon.pm
- apps/selenium/plugin.pm
Add new selenium-katalon mode allowing users to create scenarii from the Katalon Automation Recorder plugin (XML export).
Firefox : https://addons.mozilla.org/fr/firefox/user/katalon/
Google Chrome : https://chrome.google.com/webstore/detail/katalon-recorder-selenium/ljdobmomdgdljniojadhoplhkpialdid?hl=fr
> enh selenium plugin

- network/silverpeak/snmp/mode/alarms.pm
- network/silverpeak/snmp/mode/status.pm
- network/silverpeak/snmp/mode/uptime.pm
- network/silverpeak/snmp/plugin.pm
No sure about the alarms mode.
> Add silverpeak plugin

- network/peplink/balance/snmp/mode/cpu.pm
- network/peplink/balance/snmp/mode/memory.pm
- network/peplink/balance/snmp/plugin.pm
Couldn't do much since the loadbalancer wasn't running in prod or dev. I've asked my customer to let me know when it goes live to go further, maybe...
> Starting peplink loadbalancer monitoring

- network/arista/snmp/mode/memory.pm
Ref: https://github.com/centreon/centreon-plugins/issues/1018
> fix arista memory output

- network/h3c/snmp/mode/hardware.pm
Ref: https://github.com/centreon/centreon-plugins/issues/1005
> enh h3c hardware cache

- centreon/common/dell/fastpath/snmp/mode/components/temperature.pm
Fixes https://github.com/centreon/centreon-plugins/issues/1026
> fix dell fastpath temperature

- network/hirschmann/standard/snmp/mode/memory.pm
Fixes https://github.com/centreon/centreon-plugins/issues/999
> fix hirschmann memory

- apps/tomcat/web/mode/sessions.pm
Fixes https://github.com/centreon/centreon-plugins/issues/864
> fix tomcat web sessions

- network/paloalto/snmp/mode/clusterstatus.pm
Fixes https://github.com/centreon/centreon-plugins/issues/734
> enh paloalto cluster output

- database/mssql/mode/blockedprocesses.pm
Fixes https://github.com/centreon/centreon-plugins/issues/1062
> fix mssql blocked processes trim

- database/mssql/mode/transactions.pm
Fixes https://github.com/centreon/centreon-plugins/issues/1059
> fix mssql transactions case

- database/mssql/mode/databasessize.pm
- database/mssql/mode/listdatabases.pm
- database/mssql/mode/logssize.pm
- database/mssql/plugin.pm
- Enhance databases-size mode, metrics will be "used" instead of "db\_\<dbname\>\_used", and "used\_\<dbname\>" instead of "db\_\<dbname\>\_used\_\<dbname\>",
- Remove low case on output,
- Add list-databases mode.
> enh mssql plugin database, add list-database mode

- apps/activedirectory/local/mode/dfsrbacklog.pm
add receiving-member option
issue #1088
> add receiving-member option

- network/h3c/snmp/mode/components/default.pm
- network/h3c/snmp/mode/components/fan.pm
- network/h3c/snmp/mode/components/psu.pm
- network/h3c/snmp/mode/components/sensor.pm
- network/h3c/snmp/mode/hardware.pm
- Fix $self->{components_module}
- Add --short-name to make it more readable
> enh h3c hardware mode to allow count thresholds

- network/watchguard/snmp/mode/cpu.pm
> fix watchguard cpu usage calcul

- snmp_standard/mode/cpu.pm
+ Replace PR https://github.com/centreon/centreon-plugins/pull/1100 from @CPbN 
[!] Break option declaration (--(critical[warning)-average instead of --(warning|critical)
> close-339-cpu-per-core

- hardware/server/huawei/hmm/snmp/mode/components/blade.pm
- hardware/server/huawei/hmm/snmp/mode/components/cpu.pm
- hardware/server/huawei/hmm/snmp/mode/components/disk.pm
- hardware/server/huawei/hmm/snmp/mode/components/fan.pm
- hardware/server/huawei/hmm/snmp/mode/components/memory.pm
- hardware/server/huawei/hmm/snmp/mode/components/mezz.pm
- hardware/server/huawei/hmm/snmp/mode/components/psu.pm
- hardware/server/huawei/hmm/snmp/mode/components/raid.pm
- hardware/server/huawei/hmm/snmp/mode/components/shelf.pm
- hardware/server/huawei/hmm/snmp/mode/components/smm.pm
- hardware/server/huawei/hmm/snmp/mode/components/switch.pm
- hardware/server/huawei/hmm/snmp/mode/components/system.pm
- hardware/server/huawei/hmm/snmp/mode/hardwares.pm
- hardware/server/huawei/hmm/snmp/plugin.pm
- hardware/server/huawei/ibmc/snmp/mode/components/cpu.pm
- hardware/server/huawei/ibmc/snmp/mode/components/disk.pm
- hardware/server/huawei/ibmc/snmp/mode/components/fan.pm
- hardware/server/huawei/ibmc/snmp/mode/components/memory.pm
- hardware/server/huawei/ibmc/snmp/mode/components/psu.pm
- hardware/server/huawei/ibmc/snmp/mode/components/raid.pm
- hardware/server/huawei/ibmc/snmp/mode/components/system.pm
- hardware/server/huawei/ibmc/snmp/mode/hardwares.pm
- hardware/server/huawei/ibmc/snmp/plugin.pm
> Add new plugin

- network/barracuda/cloudgen/snmp/mode/boxservice.pm
- network/barracuda/cloudgen/snmp/mode/components/fan.pm
- network/barracuda/cloudgen/snmp/mode/components/psu.pm
- network/barracuda/cloudgen/snmp/mode/components/temperature.pm
- network/barracuda/cloudgen/snmp/mode/components/voltage.pm
- network/barracuda/cloudgen/snmp/mode/hardware.pm
- network/barracuda/cloudgen/snmp/mode/listvpns.pm
- network/barracuda/cloudgen/snmp/mode/serverservice.pm
- network/barracuda/cloudgen/snmp/mode/vpnstatus.pm
- network/barracuda/cloudgen/snmp/plugin.pm
> add barracuda cloudgen plugin

- snmp_standard/mode/interfaces.pm
Add --add-volume option to collect raw data volume in and out between two checks.
Those metrics are not supposed to be graphed, but used for weekly or monthly BI reporting.
> add --add-volume option

- cloud/prometheus/exporters/nodeexporter/mode/cpu.pm
- cloud/prometheus/exporters/nodeexporter/mode/cpudetailed.pm
- cloud/prometheus/exporters/nodeexporter/mode/load.pm
- cloud/prometheus/exporters/nodeexporter/mode/memory.pm
- cloud/prometheus/exporters/nodeexporter/plugin.pm
- cloud/prometheus/restapi/custom/api.pm
- cloud/prometheus/restapi/mode/targetstatus.pm
- cloud/prometheus/restapi/plugin.pm
Add promethus plugin.
Add node_exporter plugin as part of prometheus tree.
WIP!
> add prometheus plugin with node_exporter

- apps/hyperv/2012/local/mode/nodesnapshot.pm
Sometime timestamp can be negative... we ignoring it.
> fix hyperv2012 local nodesnapshot negative timestamp

- cloud/prometheus/exporters/nodeexporter/mode/cpu.pm
- cloud/prometheus/exporters/nodeexporter/mode/cpudetailed.pm
- cloud/prometheus/exporters/nodeexporter/mode/load.pm
- cloud/prometheus/exporters/nodeexporter/mode/memory.pm
- cloud/prometheus/restapi/custom/api.pm
Move step and timeframe to individual modes as it is not used for every cases.
Also allow to put default values.
Change load and memory modes so only last values are retreived.
> fix prometheus api

- cloud/azure/custom/azcli.pm
Add --subscription option if connected to several subscriptions
> enh azure custom mode

- centreon/common/cisco/standard/snmp/mode/stack.pm
Refactoring of the stack mode to allow thresholds.
Also handle https://github.com/centreon/centreon-plugins/issues/193 request.
> enh cisco standard stack mode

- snmp_standard/mode/diskusage.pm
Refactor snmp_standard plugin diskusage mode to use template counter.
Add a global counter to count the number of partitions for defined filters.
> enh snmp_standard diskusage mode

- centreon/common/fortinet/fortigate/mode/clusterstatus.pm
> enh fortinet fortigate cluster status

- cloud/prometheus/exporters/cadvisor/mode/memory.pm
Allow using % for working memory.
> enh prometheus cadvisor memory

- centreon/common/cisco/standard/snmp/mode/configuration.pm
- network/cisco/standard/snmp/plugin.pm
Refs: https://github.com/centreon/centreon-plugins/issues/1102
> add cisco standard plugin configuration mode

- cloud/aws/custom/awscli.pm
Add proxy handlin', and endpoint url overridin'.
> Enh aws plugin awscli custom mode

- apps/centreon/local/mode/dummy.pm
- apps/centreon/local/plugin.pm
Closes https://github.com/centreon/centreon-plugins/issues/1254
> add dummy mode

- apps/proxmox/ve/restapi/custom/api.pm
- apps/proxmox/ve/restapi/mode/listnodes.pm
- apps/proxmox/ve/restapi/mode/liststorages.pm
- apps/proxmox/ve/restapi/mode/listvms.pm
- apps/proxmox/ve/restapi/mode/nodeusage.pm
- apps/proxmox/ve/restapi/mode/storageusage.pm
- apps/proxmox/ve/restapi/mode/version.pm
- apps/proxmox/ve/restapi/mode/vmusage.pm
- apps/proxmox/ve/restapi/plugin.pm
Based on @ypilpre branch from PR https://github.com/centreon/centreon-plugins/pull/1267 but without last commit.
> add proxmox ve plugin

- cloud/azure/custom/api.pm
- cloud/azure/custom/azcli.pm
> add azure api options to azcli custommode

- centreon/common/fortinet/fortigate/mode/vdomcpu.pm
- centreon/common/fortinet/fortigate/mode/vdommemory.pm
- centreon/common/fortinet/fortigate/mode/vdomsession.pm
- centreon/common/fortinet/fortigate/mode/vdomstate.pm
- centreon/common/fortinet/fortigate/mode/vdomusage.pm
- network/fortinet/fortigate/plugin.pm
> enh fortinet fortigate plugin, add vdom modes

- centreon/plugins/templates/counter.pm
Better handling of cases where counter filtering causes no instances to be displayed.
> enhance template counter output

- apps/protocols/x509/mode/certificate.pm
- apps/protocols/x509/mode/validity.pm
- apps/protocols/x509/plugin.pm
Will cover https://github.com/centreon/centreon-plugins/issues/991 and https://github.com/centreon/centreon-plugins/pull/1035
> add new mode for protocols x509 plugin

- centreon/plugins/misc.pm
- centreon/plugins/output.pm
- centreon/plugins/perfdata.pm
> Enhance perfdata system

- storage/netgear/readynas/snmp/mode/components/disk.pm
- storage/netgear/readynas/snmp/mode/components/fan.pm
- storage/netgear/readynas/snmp/mode/components/psu.pm
- storage/netgear/readynas/snmp/mode/components/temperature.pm
- storage/netgear/readynas/snmp/mode/components/volume.pm
- storage/netgear/readynas/snmp/mode/hardware.pm
- storage/netgear/readynas/snmp/plugin.pm
To monitor Netgear ReadyNas with SNMP
> Add new netgear readynas plugin #1164

- centreon/plugins/snmp.pm
Hi,
This follows https://github.com/centreon/centreon-plugins/commit/3c48822071cecaf60a1357885e17fa5c86d442a4, hardening SNMP request one step further, we never know...
Thank you :+1:
> Harden SNMP request even more

- os/mac/snmp/mode/memory.pm
- os/mac/snmp/plugin.pm
> feat(plugin): add new os mac plugin

- storage/netapp/snmp/mode/filesys.pm
Hi,
Related to what we discussed in #1332 (thank you for your answer @garnier-quentin), here is a rework of Netapp `filesys` mode to make it more efficient.
Thank you :+1:
> Netapp, make filesys more efficient

- storage/netapp/snmp/mode/filesys.pm
Typo, follows #1343.
Sorry for this, and thank you.
> Netapp, typo

- snmp_standard/mode/listspanningtrees.pm
Add interface op and admin status.
> enh spanningtree mode, add listspanningtrees

- apps/protocols/http/mode/jsoncontent.pm
Add support for unknown-string, format-unknown
> Add Threshold unkown for the string

- apps/proxmox/ve/restapi/mode/storageusage.pm
- apps/proxmox/ve/restapi/mode/vmusage.pm
Hi,
I added vm swap usage monitoring inside proxmox plugin.
And I fixed alert issue with storage usage mode because of a wrong subroutine name.
Thank you.
> [apps::proxmox::ve::restapi::plugin] Add vm swap usage monitoring

- database/oracle/plugin.pm
- database/oracle/sqlpluscmd.pm
Hi,
I added the command line mode to oracle database plugin.
Based on mysqlcmd.pm.
> Add the sqlplus command line mode to oracle database plugin

- apps/protocols/snmp/mode/responsetime.pm
Small improvement @garnier-quentin after https://github.com/centreon/centreon-plugins/commit/8f33251a6bc6df4715669bc97036cd6666143ce3.
Thank you :+1:
> Small response-time snmp mode hardening

- os/linux/local/mode/ntp.pm
Hi,
This solve a small issue in local NTP mode where chronyc maps were used instead of the ntpq ones.
Thank you 👍
> Local NTP, use correct maps

- network/mikrotik/snmp/mode/environment.pm
> Mikrotik small typo

- network/mikrotik/snmp/mode/components/psu.pm
Hi,
As with temperatures, power consumption is /10 (verified through router GUI).
Thx 👍
> Mikrotik, adjust power value

- centreon/plugins/output.pm
> Small typo

- database/mysql/mode/queries.pm
- database/mysql/mode/tablessize.pm
- network/3com/snmp/mode/cpu.pm
- network/3com/snmp/mode/memory.pm
- network/a10/ax/snmp/mode/cpu.pm
- network/a10/ax/snmp/mode/disk.pm
- network/a10/ax/snmp/mode/globalstats.pm
- network/a10/ax/snmp/mode/memory.pm
- network/a10/ax/snmp/mode/vserverusage.pm
- network/acmepacket/snmp/mode/realmusage.pm
- network/acmepacket/snmp/mode/sipusage.pm
- network/acmepacket/snmp/mode/systemusage.pm
- network/aerohive/snmp/mode/connectedusers.pm
- network/alcatel/isam/snmp/mode/cpu.pm
- network/alcatel/isam/snmp/mode/hubsapusage.pm
- network/alcatel/isam/snmp/mode/memory.pm
- network/alcatel/omniswitch/snmp/mode/flashmemory.pm
- network/alvarion/breezeaccess/snmp/mode/radiostatus.pm
- network/arista/snmp/mode/memory.pm
- network/audiocodes/snmp/mode/cpu.pm
- network/audiocodes/snmp/mode/memory.pm
- network/beeware/snmp/mode/reverseproxyusage.pm
- os/aix/snmp/mode/swap.pm
- network/a* metric new system 
- database/mysql/tablesize database/mysql/queries
- network/beeware 
- os/aix
> Centreon.plugins.metrics.network.a

- apps/keepalived/snmp/mode/vrrpstatus.pm
- apps/keepalived/snmp/plugin.pm
Hi,
This follows #1499 and adds a new Keepalived plugin.
Thank you :+1:
> Add new Keepalived plugin

- apps/voip/3cx/restapi/custom/api.pm
- apps/voip/3cx/restapi/mode/system.pm
Hi,
This PR enhances 3CX plugin checking for internal software updates.
Thank you 👍
> 3CX check for updates

- apps/voip/3cx/restapi/mode/system.pm
Hi,
This PR adds monitoring of unregistered trunks to the 3CX plugin.
Thank you 👍
> 3CX, monitor unregistered trunks

- network/cisco/fabric/aci/restapi/custom/api.pm
- network/cisco/fabric/aci/restapi/mode/fabric.pm
- network/cisco/fabric/aci/restapi/mode/node.pm
- network/cisco/fabric/aci/restapi/mode/tenant.pm
- network/cisco/fabric/aci/restapi/plugin.pm
+ new cisco aci plugin, "pushing day" :)
> add cisco fabric aci plugin

- network/mikrotik/snmp/mode/interfaces.pm
- snmp_standard/mode/interfaces.pm
Hi,
Here's an alternate method for #1544.
It's better from my point of view as it gives any other interface mode the opportunity to do the same easily.
Thank you 👍
> Mikrotik, improve error label

- network/checkpoint/snmp/plugin.pm
Hi,
This PR simply adds uptime mode to Checkpoint plugin.
Thank you again :+1:
> Checkpoint, add uptime mode

- network/acmepacket/snmp/mode/realmusage.pm
Hi,
An error has slipped into the definition of perfdata.
Regards
> Perfdata: Value error

- apps/voip/3cx/restapi/custom/api.pm
- apps/voip/3cx/restapi/mode/system.pm
Hi,
3CX changed answer to one of the API requests in the last 3CX software update.
This PR then handles this.
While here, I redefined `health` to `error` and `display` to `service`, which seems more understandable.
I also slightly redefined short output, also to a more understandable version.
Thank you 👍
> 3CX update

- cloud/google/gcp/compute/computeengine/mode/cpu.pm
- cloud/google/gcp/compute/computeengine/mode/diskio.pm
- cloud/google/gcp/compute/computeengine/mode/network.pm
- cloud/google/gcp/custom/api.pm
- cloud/google/gcp/management/stackdriver/mode/getmetrics.pm
First commit to handle monitoring of k8s components parts of the google gke products. 
Related to https://github.com/centreon/centreon-plugins/issues/1601
> enh(gcp) add dimension option

- network/mikrotik/snmp/mode/components/temperature.pm
Hi,
This PR simply correctly defines "system" temperature.
Thank you 👍
> Mikrotik, define system temperature

- database/mssql/mode/pagelifeexpectancy.pm
Reverts centreon/centreon-plugins#1698
> Revert "enh(mssql): pagelifeexpectancy instance counters"

- os/linux/snmp/plugin.pm
- snmp_standard/mode/udpcon.pm
> Add snmpstandard mode udpcon

- database/oracle/mode/redologusage.pm
Hi,
This PR corrects a Oracle man typo.
Thx 👍
> Oracle man typo

- snmp_standard/mode/diskusage.pm
- snmp_standard/mode/storage.pm
Hi,
This PR adds partitions count in `storage` mode.
And corrects a typo (I think) in `diskusage` mode.
Thank you 👍
> Add count to storage mode

- os/aix/local/mode/cmdreturn.pm
- os/aix/local/plugin.pm
- os/linux/local/mode/cmdreturn.pm
add cmd-return mode for AIX.
It's just the cmd-return for Linux that I put for AIX
> add cmd-return for AIX (taken from linux)

- apps/voip/3cx/restapi/custom/api.pm
Hi,
Small PR for a small typo.
Thx 👍
> 3CX help typo

- storage/quantum/dxi/ssh/mode/dedupnas.pm
- storage/quantum/dxi/ssh/mode/dedupvtl.pm
dedupvtl was failing when fatpacked because of spaces in the help. 
epoch method couldn't be used when the day was between 1 and 9 because we the regex wasn't matching the additionnal space
> fix compilation when fatpacked and date regex issue

- apps/voip/3cx/restapi/custom/api.pm
- apps/voip/3cx/restapi/mode/extension.pm
- apps/voip/3cx/restapi/plugin.pm
Hi,
Here's a PR to add extension mode to the 3CX plugin.
Thank you for your review 👍
> Add 3CX extensions mode

- apps/dynatrace/restapi/custom/api.pm
- apps/dynatrace/restapi/mode/problem.pm
- apps/dynatrace/restapi/plugin.pm
Hi,
Here is a [Dynatrace](https://www.dynatrace.com) plugin.
It checks for problems ([API ref](https://www.dynatrace.com/support/help/extend-dynatrace/dynatrace-api/environment-api/problems/problems/get-feed/)) thanks to the counter template.
Thank you 👍
> Add Dynatrace plugin

- notification/prowl/mode/alert.pm
- notification/prowl/plugin.pm
Hi,
Here's a new notification plugin based on [Prowl](https://www.prowlapp.com/) API.
Thank you 👍
> Add Prowl notification plugin

- centreon/plugins/http.pm
Hi,
Let's allow new lines in HTTP GET/POST data, which will then be urlencoded into `%0A`.
Thank you 👍
> Allow new line in HTTP data

- notification/prowl/mode/alert.pm
> Prowl help typo

- notification/sirportly/mode/ticket.pm
Hi,
Some bugs in the Sirportly plugin (who wrote this ?! 😄)
And some comments to keep track of the logic.
Thx 👍
> Sirportly bugs, enh & comments

- cloud/azure/custom/api.pm
- cloud/azure/management/monitor/mode/alert.pm
- cloud/azure/management/monitor/plugin.pm
adding Azure monitor alerts summary
> azure alert summary

- cloud/azure/management/recovery/mode/backupitemsstatus.pm
Add the possibility to filter the backup items by virtualMachineId as returned by the Json in azcli
> enh(plugin): Azure backupitemstatus vm_id filter

- network/ibm/bladecenter/snmp/mode/components/faultled.pm
- network/ibm/bladecenter/snmp/mode/components/temperature.pm
- network/ibm/bladecenter/snmp/mode/cpu.pm
- network/ibm/bladecenter/snmp/mode/disk.pm
- network/ibm/bladecenter/snmp/mode/environment.pm
- network/ibm/bladecenter/snmp/mode/memory.pm
- network/ibm/bladecenter/snmp/plugin.pm
Hi,
Here's a new plugin, `network::ibm::bladecenter`, to directly monitor IBM BladeCenter embedded network switches.
Thx 👍
> network::ibm::bladecenter new plugin

- network/lenovo/flexsystem/snmp/mode/components/faultled.pm
- network/lenovo/flexsystem/snmp/mode/components/temperature.pm
- network/lenovo/flexsystem/snmp/mode/cpu.pm
- network/lenovo/flexsystem/snmp/mode/disk.pm
- network/lenovo/flexsystem/snmp/mode/environment.pm
- network/lenovo/flexsystem/snmp/mode/memory.pm
- network/lenovo/flexsystem/snmp/plugin.pm
Hi,
Here's a new plugin, `network::lenovo::flexsystem`, to directly monitor Lenovo Flex System embedded network switches.
Thx 👍
> network::lenovo::flexsystem new plugin

- centreon/common/ibm/nos/snmp/mode/cpu.pm
Hi,
This adds the average 5m CPU metric to the IBM NOS CPU mode.
Thx 👍
> Add IBM NOS 5m CPU

- centreon/common/ibm/nos/snmp/mode/components/temperature.pm
- network/lenovo/flexsystem/snmp/mode/components/temperature.pm
Hi,
Strange case, but just faced it.
Thx 👍
> Better handle Blade/Flex temp thresholds

- apps/voip/3cx/restapi/custom/api.pm
Hi,
Here's a patch to make 3CX plugin compatible with last PBX version.
Thx 👍
> 3CX, new version compat

- snmp_standard/mode/interfaces.pm
Hi,
This patch fixes interfaces `in_discard` percentage sometimes seen >100%.
Clue was in the RFC :)
Thx 👍
> fix interfaces discard counter

- apps/protocols/snmp/mode/responsetime.pm
Hi,
This PR fixes UDP ping rta calculation in case of packet loss.
Thank you 👍
> Fix UDP ping

- cloud/aws/custom/awscli.pm
- cloud/aws/custom/paws.pm
- cloud/aws/ec2/mode/discoveryspotfleetrequests.pm
- cloud/aws/ec2/mode/listspotfleetrequests.pm
- cloud/aws/ec2/plugin.pm
- add discovery mode to get spot fleet requests
> enh(plugin)add ec2 spot fleet discovery

- network/atrica/snmp/mode/connections.pm
Hi,
This follows #1960, so that we have same metric name everywhere.
Thank you 👍
> Interfaces typo

- hardware/devices/timelinkmicro/tms6001/snmp/mode/alarm.pm
- hardware/devices/timelinkmicro/tms6001/snmp/mode/antenna.pm
- hardware/devices/timelinkmicro/tms6001/snmp/mode/frequency.pm
- hardware/devices/timelinkmicro/tms6001/snmp/mode/gnss.pm
- hardware/devices/timelinkmicro/tms6001/snmp/mode/satellites.pm
- hardware/devices/timelinkmicro/tms6001/snmp/mode/time.pm
- hardware/devices/timelinkmicro/tms6001/snmp/plugin.pm
Hello,
this is my first plugin for centreon. This plugin checks Timelink microsystems TMS6001 time server using SNMP.
Antenna status
GNSS state
Quality of time generation
Quality of frequency generation
Number of satellites seen
Number of alarms.
Thank you,
Lenkoda
> New plugin for Timelink microsystems TMS6001 time server

- cloud/aws/custom/awscli.pm
- cloud/aws/custom/paws.pm
- cloud/aws/ebs/mode/discovery.pm
- cloud/aws/ebs/mode/listvolumes.pm
- cloud/aws/ebs/mode/volumedata.pm
- cloud/aws/ebs/mode/volumeio.pm
- cloud/aws/ebs/mode/volumeiops.pm
- cloud/aws/ebs/mode/volumetime.pm
- cloud/aws/ebs/plugin.pm
Amazon EBS volumes monitoring through Cloudwatch.
> add(plugin): Amazon EBS

- os/aix/snmp/plugin.pm
Hi,
Very simple enhancement.
Thx 👍
> enh(aix) Add uptime mode

- hardware/server/sun/snmp/plugin.pm
Hello, It seems to be already there (as of documentation and common code) but the plugin was hardware::server::sun::snmp::plugin still missing. I've simply added the plugin part.
> Added hardware::server::sun::snmp::plugin

- cloud/aws/ebs/mode/volumeio.pm
- cloud/aws/ebs/mode/volumeiops.pm
- cloud/aws/ebs/mode/volumetime.pm
fix for https://github.com/centreon/centreon-plugins/issues/2032
> fix(mode): naming typos

- storage/synology/snmp/plugin.pm
Hi,
Let's add some standard modes to `Synology` plugin.
Thx 👍
> enh(synology) Add standard modes

- storage/synology/snmp/mode/components/system.pm
Hi,
Synology `system` component is not about the _system_ (hardware) itself, but about the _system partition_.
Let's then precise this.
Thx 👍
> Synology wording

- hardware/server/dell/idrac/snmp/mode/hardware.pm
Hi,
Let's fix a missing idrac status.
Thx 👍
> fix(idrac) Missing status

- apps/monitoring/netdata/restapi/custom/api.pm
- apps/monitoring/netdata/restapi/mode/alarms.pm
- apps/monitoring/netdata/restapi/mode/cpu.pm
- apps/monitoring/netdata/restapi/mode/diskusage.pm
- apps/monitoring/netdata/restapi/mode/getchart.pm
- apps/monitoring/netdata/restapi/mode/inodes.pm
- apps/monitoring/netdata/restapi/mode/listcharts.pm
- apps/monitoring/netdata/restapi/mode/loadaverage.pm
- apps/monitoring/netdata/restapi/mode/memory.pm
- apps/monitoring/netdata/restapi/mode/swap.pm
- apps/monitoring/netdata/restapi/mode/traffic.pm
- apps/monitoring/netdata/restapi/plugin.pm
Initial plugin commit, includes the following modes:
- alarms
- cpu
- load
- memory
- swap
- disk usage
- inodes
- traffic
- list charts
- get charts
More modes and improvements to come...
> add(plugin): Netdata RestAPI

- network/citrix/netscaler/snmp/mode/storage.pm
Hi,
This corrects a Netscaler typo.
Thx 👍
> fix(netscaler) Typo

- hardware/server/dell/idrac/snmp/mode/components/systembattery.pm
Hi,
Solves #2097 (tested).
Thx !
> fix(idrac) Typo preventing system batteries to work

- storage/synology/snmp/mode/components/system.pm
Hi,
This follows #2048, with a remaining wording issue.
Thx 👍
> fix(Synology) remaining partition wording

- apps/nsclient/restapi/mode/query.pm
- apps/protocols/nrpe/custom/nsclient.pm
Hi,
Just to clarify API used...
Thx 👍
> Clarify NSClient API versions

- network/watchguard/snmp/mode/policyusage.pm
Hi,
Just faced this Watchguard bug, which leads to messy graphs...
Let's workaround it...
Thx 👍
> fix(whatchguard) maxint issue

- network/citrix/netscaler/snmp/mode/vserverstatus.pm
In the deepest top range ^^
Thx 👍
> fix(netscaler) vserver accounting bug

- network/checkpoint/snmp/mode/cpu.pm
Hi,
This PR enhances Checkpoint CPU mode.
It's a simple copy of `snmp_standard::mode::cpu`, but using dedicated Checkpoint OIDs `.1.3.6.1.4.1.2620.1.6.7.5.1.5`.
So no difficulty here.
Thank you 👍
> Enhance Checkpoint CPU mode

- apps/citrix/local/mode/license.pm
Hi,
This PR allows to get Citrix licenses usage by license (`PLD` in Citrix wording).
Thx 👍
> enh(citrix) Get licenses by name/PLD

- cloud/aws/custom/awscli.pm
- cloud/aws/custom/paws.pm
- cloud/aws/sqs/mode/listqueues.pm
- cloud/aws/sqs/mode/queues.pm
- cloud/aws/sqs/plugin.pm
New AWS plugin for SQS.
Mode:
- queues
> add(plugin): Amazon SQS

- apps/citrix/local/mode/license.pm
> fix(citrix) licenses typo

- network/cisco/meraki/cloudcontroller/restapi/mode/discovery.pm
Like versa network discovery.
Add new option resource-type for the host discovery rules
> (enh): meraki cloud discovery add resource-type option

- centreon/common/cisco/standard/snmp/mode/ipsectunnel.pm
Fix https://github.com/centreon/centreon/issues/8910
> fix(mode): typo in cisco ipsectunnel mode

- hardware/devices/polycom/hdx/snmp/mode/viewstationstats.pm
- hardware/devices/polycom/hdx/snmp/plugin.pm
> new(plugin)Polycom HDX ViewStation statistics

- hardware/devices/video/axis/snmp/mode/environment.pm
Fixes https://github.com/centreon/centreon-plugins/issues/2161
> fix(mode): fix Axis environment mode

- centreon/common/dell/fastpath/snmp/mode/cpu.pm
Small fix for warning and critical thresholds on Dell CPU 5sec. Thanks !
> fix dell fastpath cpu 5sec thresholds

- storage/exagrid/snmp/mode/serverusage.pm
Sometimes systems are retention only servers, so landing space is equal to zero.
> fix(exagrid/snmp): handle division by zero

- apps/protocols/nrpe/custom/nsclient.pm
Hi,
I faced some issue with `nsclient` plugin not properly decoding JSON containing special characters.
This PR solves this.
Thx 👍
> fix(nsclient) properly decode JSON

- apps/citrix/local/mode/folder.pm
Hi,
Let's fix a Citrix typo.
Thx 👍
> Citrix typo

- apps/voip/3cx/restapi/mode/extension.pm
Hi,
3CX made some changes into the API with 3CX >= 16.0.6.641.
Let's then support it.
Thx 👍
> fix(3CX) API updates

- apps/voip/3cx/restapi/mode/extension.pm
Hi,
Let's add a 3CX global counter.
Feel free to modify if ever I did not use the proper method to add this.
Thx 👍
> enh(3cx) Add a global counter

- centreon/common/fortinet/fortigate/snmp/mode/vdomusage.pm
> fix(fortinet) typo

- snmp_standard/mode/interfaces.pm
> fix(interfaces) typo

- os/freebsd/snmp/mode/memory.pm
Hi,
Let's add some new labels.
Thx 👍
> enh(freebsd) Add new labels

- network/versa/director/restapi/mode/devices.pm
Add capability to set threshold per health metrics
> enh(plugin)counter refacto for new threshold

- apps/centreon/sql/mode/multiservices.pm
Let's get rid of some debug.
Thx 👍
> debug typo

- network/versa/director/restapi/mode/devices.pm
I forgot this one last time I commited ...
> fix(plugin) Versa Director => add monitor in perfdata name

- apps/centreon/sql/mode/multiservices.pm
Hi,
This PR fixes `multiservices` mode initially written by @Sims24.
It fixes the `--json-data` option, so that we can now properly provide inline JSON.
~It adds a `services_maxage` property so that we can be sure to look for services checked in the past X seconds (as `centreon_storage` could contain very old entries).~
Thank you 👍
> fix multiservices

- .github/issue_template.md
I think it will make requirement for a new plugin request more visible.
> enh(issuetemplate)cosmetic, no scroll to reach/read the important part

- cloud/microsoft/office365/onedrive/mode/listsites.pm
- cloud/microsoft/office365/sharepoint/mode/listsites.pm
Hi,
This should fix #2305.
This issue is related to the whole office365 plugins rework, I did not pay attention to the `list-` modes.
Thx 👍
> fix(o365) list modes

- network/mikrotik/snmp/mode/components/current.pm
- network/mikrotik/snmp/mode/components/psu.pm
Hi,
Let's fix some MikroTik units.
Thx 👍
> fix(mikrotik) units

- apps/monitoring/alyvix/restapi/mode/listtestcases.pm
> fix(plugin) alyvix restapi

- storage/dell/compellent/snmp/plugin.pm
Hi,
Let's add some standard modes to Compellent.
Thx 👍
> enh(compellent) add some standard modes

- apps/bind9/web/mode/serverusage.pm
- apps/bind9/web/mode/zoneusage.pm
- apps/kingdee/eas/mode/handlers.pm
- centreon/common/cisco/standard/snmp/mode/memoryflash.pm
- cloud/aws/elasticache/mode/cpu.pm
- cloud/azure/storage/storageaccount/mode/blobcontainercount.pm
- cloud/azure/storage/storageaccount/mode/filecapacity.pm
- cloud/azure/storage/storageaccount/mode/filecount.pm
- cloud/azure/storage/storageaccount/mode/filesharecount.pm
- cloud/azure/storage/storageaccount/mode/queuecapacity.pm
- cloud/azure/storage/storageaccount/mode/queuecount.pm
- cloud/azure/storage/storageaccount/mode/queuemessagecount.pm
- cloud/azure/storage/storageaccount/mode/tablecapacity.pm
- cloud/azure/storage/storageaccount/mode/tablecount.pm
- cloud/azure/storage/storageaccount/mode/tableentitycount.pm
- cloud/azure/storage/storageaccount/mode/transactionsavailability.pm
- database/oracle/mode/rmanbackupage.pm
- database/postgres/mode/statistics.pm
- hardware/devices/camera/hikvision/snmp/mode/cpu.pm
- hardware/devices/camera/hikvision/snmp/mode/memory.pm
- hardware/pdu/apc/snmp/mode/load.pm
- hardware/pdu/cyberpower/snmp/mode/load.pm
- storage/dell/equallogic/snmp/mode/arrayusage.pm
- storage/dell/equallogic/snmp/mode/diskusage.pm
Hello,
I develop a script allowing me to automatically generate host templates based on Centreon plugins.
During this development, I noticed errors or blocking points in the help of the modules.
I fixed them for me and submit them to you.
Nribault
> Help Correction

- storage/emc/unisphere/restapi/mode/components/resources.pm
- storage/emc/unisphere/restapi/mode/listreplications.pm
- storage/emc/unisphere/restapi/mode/pools.pm
- storage/emc/unisphere/restapi/mode/replications.pm
- storage/emc/unisphere/restapi/mode/storageresources.pm
- storage/emc/unisphere/restapi/plugin.pm
- add new replication session monitoring 
- fix some typos
> enh(plugin)new replication mode unisphere

- os/windows/local/mode/pendingreboot.pm
Thix fixes a typo in #2399.
Thx 👍
> fix(windows) Typo in Windows version output

- cloud/cadvisor/restapi/mode/containerusage.pm
- cloud/cadvisor/restapi/mode/diskio.pm
- cloud/cadvisor/restapi/mode/nodestatus.pm
- cloud/cadvisor/restapi/mode/traffic.pm
- cloud/cadvisor/restapi/plugin.pm
- cloud/cloudfoundry/restapi/mode/appsstate.pm
- cloud/cloudfoundry/restapi/mode/instancesstate.pm
- cloud/cloudfoundry/restapi/plugin.pm
- cloud/docker/restapi/mode/containerusage.pm
- cloud/docker/restapi/mode/nodestatus.pm
- cloud/ibm/softlayer/mode/events.pm
- cloud/ibm/softlayer/mode/opentickets.pm
- cloud/ibm/softlayer/plugin.pm
Refactoring metrics to v2. Sample commits to show to @itoussies what he can do to help ;)
> enh(plugin)metrics-v2-sample-pr

- hardware/server/ibm/mgmt_cards/imm/snmp/mode/components/cpu.pm
- hardware/server/ibm/mgmt_cards/imm/snmp/mode/components/disk.pm
- hardware/server/ibm/mgmt_cards/imm/snmp/mode/components/fan.pm
- hardware/server/ibm/mgmt_cards/imm/snmp/mode/components/memory.pm
- hardware/server/ibm/mgmt_cards/imm/snmp/mode/components/power.pm
- hardware/server/ibm/mgmt_cards/imm/snmp/mode/environment.pm
Hi,
Let's add some modes to the `IMM` plugin.
Thx 👍
> enh(imm) Add some modes

- apps/centreon/sql/mode/virtualservice.pm
Example of file:
```
{
"selection":{
"traffic_in1":{
"host_name":"test-poller1_9_2",
"service_name":"Traffic-ens160",
"metric_name":"traffic_in",
"display": false
},
"traffic_in2":{
"host_name":"test-poller1_9_9",
"service_name":"Traffic-ens160",
"metric_name":"traffic_in",
"display": false
},
"traffic_out1":{
"host_name":"test-poller1_9_2",
"service_name":"Traffic-ens160",
"metric_name":"traffic_out",
"display": false
},
"traffic_out2":{
"host_name":"test-poller1_9_9",
"service_name":"Traffic-ens160",
"metric_name":"traffic_out",
"display": false
}
},
"virtualcurve":{
"sum_traffic_in":{
"unit":"b",
"pattern":"traffic_in",
"min":0,
"aggregation":"sum"
},
"sum_traffic_out":{
"unit":"b",
"pattern":"traffic_out",
"min":0,
"aggregation":"sum"
}
},
"formatting":{
"printf_msg":"Metric %s value …
```
> enhance virtual-service

- cloud/prometheus/direct/kubernetes/mode/containerstatus.pm
- cloud/prometheus/direct/kubernetes/mode/daemonsetstatus.pm
- cloud/prometheus/direct/kubernetes/mode/deploymentstatus.pm
- cloud/prometheus/restapi/mode/expression.pm
+fix instance on the Prometheus plugin
+add the namespace information in *status modes
> (enh/fix)Prometheus

- database/postgres/mode/querytime.pm
Hello,
There was a missing ! meaning the plugin will never generate another status besides 'ok'
> Fix postgres query-time

- database/mssql/mode/databasessize.pm
Hi,
This PR enhances `mssql` plugin, `databases-size` mode.
It still checks and considers underlying disk space  for unlimited autogrowth data and log files, but now also for those set with a limit greater than the remaining disk space.
So that we properly get alerted in such situation.
Thank you 👍
> enh(mssql) Better check of underlying disk space

- network/arista/snmp/mode/memory.pm
Correct memory calculation for Arista with EOS > 4.22.0F
https://eos.arista.com/memory-utilization-of-eos-devices/
> Correct memory calculation

- apps/pfsense/snmp/mode/packetstats.pm
> fix(plugin)apps-pfsens-snmp

- os/windows/local/mode/sessions.pm
Hi,
This should solve #2505 (not tested though).
Thx 👍
> fix(win) Sessions mode run manually

- cloud/azure/custom/mode.pm
- cloud/azure/network/loadbalancer/mode/datapath.pm
- cloud/azure/network/loadbalancer/mode/discovery.pm
- cloud/azure/network/loadbalancer/mode/healthprobe.pm
- cloud/azure/network/loadbalancer/mode/snat.pm
- cloud/azure/network/loadbalancer/mode/throughput.pm
- cloud/azure/network/loadbalancer/plugin.pm
Using a custom "mode" class for code factoring
> add(plugin): Azure Load Balancer

- os/linux/local/mode/discoverysnmp.pm
> Add a new lookup type

- cloud/vmware/velocloud/restapi/mode/applicationusage.pm
- cloud/vmware/velocloud/restapi/mode/categoryusage.pm
- cloud/vmware/velocloud/restapi/mode/edgeqoe.pm
- cloud/vmware/velocloud/restapi/mode/linkstatus.pm
- cloud/vmware/velocloud/restapi/mode/linkusage.pm
This avoids the  "OK:  | " output for the modes when the edge is offline or unavailable
> fix(mode): Fix Velocloud modes when edge offline

- cloud/azure/custom/api.pm
- cloud/azure/custom/azcli.pm
- cloud/azure/custom/mode.pm
- cloud/azure/network/firewall/mode/discovery.pm
- cloud/azure/network/firewall/mode/health.pm
- cloud/azure/network/firewall/mode/hits.pm
- cloud/azure/network/firewall/mode/throughput.pm
- cloud/azure/network/firewall/plugin.pm
- cloud/azure/network/publicip/mode/ddostraffic.pm
- cloud/azure/network/publicip/mode/discovery.pm
- cloud/azure/network/publicip/mode/status.pm
- cloud/azure/network/publicip/plugin.pm
- cloud/azure/security/keyvault/mode/discovery.pm
- cloud/azure/security/keyvault/mode/serviceapi.pm
- cloud/azure/security/keyvault/mode/vaultavailability.pm
- cloud/azure/security/keyvault/mode/vaultcapacity.pm
- cloud/azure/security/keyvault/modes.txt
- cloud/azure/security/keyvault/plugin.pm
- Azure Firewalls
- Azure Key Vaults
- Azure Public IPs
> add(plugin): new Azure Plugins

- apps/protocols/snmp/mode/collection.pm
```
{
"mapping": {
"disjoncteur": {
"0": "ferme",
"1": "ferme/defaut",
"10": "ouvert",
"11": "ouvert/defaut"
},
"other": {
"8": "test",
"25": "test2"
}
},
"snmp": {
"cache": {
"enable": true,
"reload": 30
},
"tables": [
{ 
"name": "plcData", 
"oid": ".1.3.6.1.4.1.13576.10.1.100.1.1",
"used_instance": "\\.(\\d+)$",
"entries": [
{ "name": "plcRead", "oid": ".1.3.6.1.4.1.13576.10.1.100.1.1.2", "map": "disjoncteur" },
{ "name": "plcWrite", "oid": ".1.3.6.1.4.1.13576.10.1.100.1.1.3" }
]
},
{
"name": "plcOther",
"oid": ".1.3.6.1.4.1.13576.10.1.100.2.1",
"entries": [
{ "name": "plop", "oid": ".1.3.6.1.4.1.13576.10.1.100.2.1.2" }
]
}
],
"leefs": [
{ "name": "serialNum", "oid": ".1.3.6.1.4.1.13576.10.1.2.0", "map": "other" },
{ "name": "macAddress", "oid": ".1.3.6.1.4.1.13576.10.1.3.0" }
]
}, …
```
> [mode] snmp generic collection enh

- cloud/azure/custom/api.pm
- cloud/azure/custom/azcli.pm
- cloud/azure/management/monitor/mode/getmetrics.pm
Added metricnamespace as parameter to the Azure Metrics script
Fixes #2248
> enh(plugin) add metricnamespace option to Azure Monitor get-metric mode

- cloud/azure/compute/functions/mode/executions.pm
> fix(plugin)azure-functions

- storage/qnap/snmp/plugin.pm
Hi,
Let's add some standard modes to Qnap.
Thx 👍
> Add some standard modes to Qnap

- network/acmepacket/snmp/mode/components/fan.pm
- network/acmepacket/snmp/mode/components/psu.pm
- network/acmepacket/snmp/mode/components/temperature.pm
- network/acmepacket/snmp/mode/components/voltage.pm
- network/acmepacket/snmp/mode/hardware.pm
- network/acmepacket/snmp/mode/realmusage.pm
- network/acmepacket/snmp/mode/sipusage.pm
- network/acmepacket/snmp/mode/systemusage.pm
- network/acmepacket/snmp/plugin.pm
- storage/overland/neo/snmp/mode/components/drive.pm
- storage/overland/neo/snmp/mode/components/library.pm
- storage/overland/neo/snmp/mode/hardware.pm
- storage/overland/neo/snmp/plugin.pm
also some indent on overland neo snmp.
> enh(acmepacket/snmp): force new perfdata

- cloud/azure/management/discover/plugin.pm
meta Plugin to be used with Centreon IT-edition for Host auto discovery
> add(plugin): Azure Discover meta Plugin

- database/mssql/mode/backupage.pm
Hi,
Let's exclude snapshots from MSSQL backups.
https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-databases-transact-sql?view=sql-server-ver15
Thx 👍
> enh(mssql) Exclude snapshots from backups

- apps/antivirus/clamav/local/mode/updatestatus.pm
> fix(clamav): delimiter typo which break the plugin

- cloud/azure/security/keyvault/mode/vaultcapacity.pm
missing "-percentage" in examples.
> fix(keyvault) vaultcapacity.pm help 

- cloud/azure/management/apimanagement/plugin.pm
Closes https://github.com/centreon/centreon-plugins/issues/2791
> fix(plugin): Azure API Management

- cloud/azure/database/mysql/mode/storage.pm
Intervall fix written by @matoy (https://github.com/centreon/centreon-plugins/pull/2802). The rest of the PR need to be investigated.
> fix(plugin): Azure DB for MySQL

- cloud/azure/common/appservice/mode/status.pm
> fix(mode): Azure App Service fix interval on mode status

- cloud/azure/web/appserviceplan/mode/tcpconnections.pm
> fix(mode): App Svc Plan remove inoperative metrics

- storage/dell/equallogic/snmp/plugin.pm
Hi,
Let's add standard `time` mode to Equallogic plugin.
Thx 👍
> enh(equallogic) add time mode

- apps/pvx/restapi/mode/httphits.pm
- apps/pvx/restapi/mode/networkconnection.pm
- apps/pvx/restapi/mode/networktraffic.pm
- apps/pvx/restapi/mode/networkuserexperience.pm
- apps/pvx/restapi/plugin.pm
> enh(plugin): PVX Rest API metricsv2

- apps/slack/restapi/mode/countchannels.pm
- apps/slack/restapi/mode/countmembers.pm
- apps/slack/restapi/plugin.pm
> enh(plugin): Slack REST API metricsv2

- storage/synology/snmp/mode/components/disk.pm
Hi,
Let's use Synology disk name, rather than its SNMP ID, for better handling.
```
Checking disk
disk 'Drive 1' status is Normal [instance: 0]
disk 'Drive 2' status is Normal [instance: 1]
disk 'Drive 3' status is Normal [instance: 2]
disk 'Drive 4' status is Normal [instance: 3]
disk 'Drive 5' status is Normal [instance: 4]
disk 'Drive 6' status is Normal [instance: 5]
disk 'Drive 7' status is Normal [instance: 6]
disk 'Drive 8' status is Normal [instance: 7]
disk 'Drive 9' status is Normal [instance: 8]
disk 'Drive 10' status is Normal [instance: 9]
disk 'Drive 11' status is Initialized [instance: 10]
disk 'Drive 12' status is Initialized [instance: 11]
```
Thx 👍
> enh(Synology) Use disk name rather than its ID

- apps/sahipro/restapi/mode/scenario.pm
- apps/sahipro/restapi/plugin.pm
> enh(plugin): SAHI Pro REST API metricsv2

- apps/squid/snmp/mode/cacheusage.pm
- apps/squid/snmp/mode/protocolstats.pm
- apps/squid/snmp/plugin.pm
> Apps squid snmp metricsv2

- cloud/azure/network/cdn/mode/discovery.pm
- cloud/azure/network/cdn/mode/hitratio.pm
- cloud/azure/network/cdn/mode/latency.pm
- cloud/azure/network/cdn/mode/request.pm
- cloud/azure/network/cdn/mode/requests.pm
- cloud/azure/network/cdn/mode/response.pm
- cloud/azure/network/cdn/plugin.pm
[xxxcdn]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::network::cdn::plugin --custommode='api' --list-mode
Plugin Description:
Check Microsoft Azure CDP profile service.
Global Options:
--mode Choose a mode.
--dyn-mode
Specify a mode with the path (separated by '::').
--list-mode
List available modes.
--mode-version
Check minimal version of mode. If not, unknown error.
--version
Display plugin version.
--custommode
Choose a custom mode.
--list-custommode
List available custom modes.
--multiple
Multiple custom mode objects (required by some specific modes)
--pass-manager
Use a password manager.
Modes Meta:
multi
Modes Available:
discovery
hit-ratio
latency
request
response
[xxxcdn]# /usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl …
> new(plugin): Azure CDN with 4 modes + discovery

- cloud/azure/storage/storagesync/mode/filessync.pm
- cloud/azure/storage/storagesync/mode/recalls.pm
- cloud/azure/storage/storagesync/mode/serverstatus.pm
> fix(plugin): Azure Storage Sync

- cloud/cadvisor/restapi/mode/diskio.pm
Avoid undefined array error when no diskio stats available
> fix(plugin): cadvisor-manage-unavailable-diskio-stats

- storage/qnap/snmp/mode/upgrade.pm
- storage/qnap/snmp/plugin.pm
Hi,
Just for ref, here's the `upgrade` mode for the Qnap plugin.
Up to you whether or not you're willing to merge it, but at least here it is for ref :)
Many thx 👍
> enh(qnap) Add upgrade mode

- apps/voip/3cx/restapi/mode/system.pm
> fix(3cx) Typo

- hardware/server/hp/bladechassis/snmp/mode/components/blade.pm
Problems with cpqRackServerBladeStatus & cpqRackServerBladeSparePartNumber
> fix(plugin)bladechassis-oid-mixed-up

- cloud/azure/network/cdn/mode/requests.pm
Default aggregation change 'Count' -> 'Total' ('Average' is valid too).
> fix(plugin): Azure CDN

- network/netgear/mseries/snmp/mode/components/temperature.pm
Fix: https://github.com/centreon/centreon-plugins/issues/2896
> fix(plugin): netgear mseries snmp

- network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
avoid 404 error when calling this mode
> fix(plugin): Meraki Cloud Controller - Avoid 404 error with networks monitoring. 

- cloud/aws/health/mode/events.pm
> fix(plugin): AWS Health 

- network/dell/os10/snmp/plugin.pm
Hi,
Let's add `time` standard mode to `os10` Dell plugin.
Thx 👍
> enh(os10) add time standard mode

- apps/voip/3cx/restapi/mode/system.pm
Hi,
Let's add 3CX max simultaneous calls to perfdata.
Thx 👍
> enh(3cx) add max sim calls value

- Jenkinsfile
remove CI's timeout workaround
> enh(chore): remove CI's timeout workaround

- apps/grafana/restapi/custom/api.pm
- apps/grafana/restapi/mode/health.pm
- apps/grafana/restapi/plugin.pm
Init Grafana plugin.
Not much to collect from the RestAPI doc:
[https://grafana.com/docs/grafana/latest/http_api/other/#health-api](url)
> init grafana

- storage/synology/snmp/mode/components/system.pm
Hi,
Some useful comment from Synology support which may help others (like me) wondering about this OID behavior.
Thx 👍
> enh(synology) Some useful comment from support

- cloud/azure/storage/acr/mode/storageused.pm
- cloud/azure/storage/acr/plugin.pm
New plugin ACR (Azure Container Registry)
> New plugin ACR (Azure Container Registry)

- centreon/common/airespace/snmp/mode/discovery.pm
- network/cisco/wlc/snmp/plugin.pm
Add Host Discovery mode for access points.
> enh(plugin)discovery cisco wlc access points

- apps/voip/3cx/restapi/custom/api.pm
Hi,
Let's support 3CX v18, about to be released (RC for now).
Thank you 👍
> enh(3cx) Support v18

- apps/monitoring/mip/restapi/mode/scenarios.pm
MIP replace label with alias in the latest API.
> enh(plugin) MIP Scenario - API fix

- storage/qnap/snmp/mode/memory.pm
Hi,
Memory counters finally fixed in Qnap QTS 4.5.4.1741, let's then clarify the Qnap memory mode.
Thx 👍
> enh(qnap) Memory bugs fixed in QTS 4.5.4.1741

- centreon/plugins/nrpe.pm
Hi,
This PR to add management of NRPE v4.
> Update nrpe.pm for management of NRPE v4

- hardware/pdu/apc/snmp/mode/components/temperature.pm
Hi,
Missing /10 for PDU temperature.
Thx 👍
> fix(pdu) temperature /10

- cloud/azure/database/sqldatabase/mode/databasesize.pm
This fix until the Plugin is fully refactored
before:
counter list: storage_percent-minimum storage_percent-maximum storage_percent-average
after:
counter list: storage-percent-minimum storage-percent-maximum storage-percent-average
> fix(mode): Azure SQL DB counters case: snake to kebab

- hardware/pdu/apc/snmp/mode/load.pm
Closes https://github.com/centreon/centreon-plugins/issues/3115
> + fix device power calculation

- apps/grafana/api/custom/api.pm
- apps/grafana/api/mode/health.pm
- apps/grafana/api/plugin.pm
Rename file from restapi to api
> enh(grafana): Rename restapi to api

- cloud/azure/management/automation/mode/health.pm
> fix(plugin): Azure automation health mode fix

- cloud/azure/custom/api.pm
loop through next links URL when more than 1000 results
> enh(custom): Azure handle large results in list resources for discovery

- os/linux/local/mode/liststorages.pm
Add size in liststorages disco format
> Add size in liststorages disco format

- apps/vtom/restapi/mode/jobstatus.pm
- apps/vtom/restapi/plugin.pm
> enh(plugin): VTOM REST API metricsv2

- apps/voip/asterisk/ami/mode/channelusage.pm
- apps/voip/asterisk/ami/mode/dahdistatus.pm
- apps/voip/asterisk/ami/mode/sippeersusage.pm
- apps/voip/asterisk/ami/plugin.pm
- apps/voip/asterisk/snmp/mode/channelusage.pm
- apps/voip/asterisk/snmp/plugin.pm
Updating the plugins (AMI & SNMP) with the new metric naming format.
> enh(plugin): Asterisk AMI & SNMP MetricsV2

- apps/backup/netbackup/local/mode/dedupstatus.pm
- apps/backup/netbackup/local/mode/drivecleaning.pm
- apps/backup/netbackup/local/mode/jobstatus.pm
- apps/backup/netbackup/local/mode/tapeusage.pm
- apps/backup/netbackup/local/plugin.pm
> enh(plugin): Netbackup MetricsV2

- apps/backup/veeam/local/mode/tapejobs.pm
Fix https://github.com/centreon/centreon-plugins/issues/3277
> (plugin) patch edge case on empty JSON with Veeam tape-jobs mode

- cloud/azure/custom/api.pm
- cloud/azure/custom/azcli.pm
- cloud/azure/network/virtualnetwork/mode/listvirtualnetworks.pm
- cloud/azure/network/virtualnetwork/mode/peeringsstatus.pm
💥 Breaking change. 
Align Azure Network Vnet with latest dev guidelines.
> (plugin)refactoring-azure-virtual-networks

- README.md
- doc/en/user/guide.rst
i != I
add link to further documentation
> enh(doc) spelling ux

- database/informix/sql/plugin.pm
> fix(plugin) syntax error informix sql plugin

- cloud/aws/fsx/mode/datausage.pm
- cloud/aws/fsx/mode/discovery.pm
- cloud/aws/fsx/mode/freespace.pm
- cloud/aws/fsx/plugin.pm
Closes https://github.com/centreon/centreon-plugins/issues/2613
> (plugin): cloud::aws::fsx - add AWS/FSx shared filesystems monitoring 

- cloud/azure/compute/aks/mode/health.pm
- cloud/azure/compute/aks/plugin.pm
Adding health mode for Azure Kubernetes Service
> (plugin) add azure/aks health mode

- cloud/azure/compute/vmscalesets/mode/cpu.pm
- cloud/azure/compute/vmscalesets/mode/discovery.pm
- cloud/azure/compute/vmscalesets/mode/diskio.pm
- cloud/azure/compute/vmscalesets/mode/health.pm
- cloud/azure/compute/vmscalesets/mode/memory.pm
- cloud/azure/compute/vmscalesets/mode/traffic.pm
- cloud/azure/compute/vmscalesets/plugin.pm
Adding plugin to monitor Azure Virtual Machine Scale Sets (VMSS)
> (plugin): cloud::azure::compute::vmscalesets

- apps/protocols/http/mode/collection.pm
- apps/protocols/http/plugin.pm
Text example:
```
joe = 125
bob = 130
```
Json example:
```
{
"store": {
"book": [ 
{ "category" :  "reference",
"author"   :  "Nigel Rees",
"title"    :  "Sayings of the Century",
"price"    :  8.95
},
{ "category" :  "fiction",
"author"   :  "Evelyn Waugh",
"title"    :  "Sword of Honour",
"price"    :  12.99
},
{ "category" :  "fiction",
"author"   :  "Herman Melville",
"title"    :  "Moby Dick",
"isbn"     :  "0-553-21311-3",
"price"    :  8.99
},
{ "category" :  "fiction",
"author"   :  "J. R. R. Tolkien",
"title"    :  "The Lord of the Rings",
"isbn"     :  "0-395-19395-8",
"price"    :  22.99
}
],
"bicycle": [
{ "color": "red",
"price": 19.95
}
]
}
}
```
The json config:
```
{
"mapping": {},
"http": {
"cache": {
"enable": false,
"reload": 5
},
"requests": [
{
"name": "users", …
```
> (plugin) apps::protocols::http - add collection mode

- apps/protocols/http/mode/collection.pm
First you need to add the content-type in header. For example:
```
{
"http": {
"requests": [
{
"name": "users",
"hostname": "10.25.5.178",
"headers": ["Accept:application/json", "Content-Type:application/json"],
...
}
```
You have 3 types of payload.
```
{
"http": {
"requests": [
{
"name": "users",
"hostname": "10.25.5.178",
"headers": ["Accept:application/json", "Content-Type:application/json"],
"payload": {
"type": "data",
"value": "{ \"test\": 1 }"
},
...
}
```
```
{
"http": {
"requests": [
{
"name": "users",
"hostname": "10.25.5.178",
"headers": ["Accept:application/json", "Content-Type:application/json"],
"payload": {
"type": "json",
"value": { "test": 1 }
},
...
}
```
```
"http": {
"requests": [
{
"name": "users",
"hostname": "10.25.5.178",
"headers": ["Accept:application/json", …
```
> (plugin) apps::protocols::http - add payload options for collection

- centreon/plugins/snmp.pm
> enh(spelling)whe2when

- network/watchguard/snmp/mode/cluster.pm
> network:watchguard:snmp_cluster - wrong help

- os/windows/wsman/mode/sessions.pm
- os/windows/wsman/plugin.pm
> (plugin) os::windows::wsman - add new sessions mode

- network/citrix/netscaler/snmp/mode/connections.pm
Closes https://github.com/centreon/centreon-plugins/issues/3562
> (plugin) network::citrix::netscaler::snmp::mode::connections - add established counter

- cloud/azure/database/mariadb/mode/connections.pm
- cloud/azure/database/mariadb/mode/cpu.pm
- cloud/azure/database/mariadb/mode/discovery.pm
- cloud/azure/database/mariadb/mode/ioconsumption.pm
- cloud/azure/database/mariadb/mode/memory.pm
- cloud/azure/database/mariadb/mode/queries.pm
- cloud/azure/database/mariadb/mode/replication.pm
- cloud/azure/database/mariadb/mode/storage.pm
- cloud/azure/database/mariadb/mode/traffic.pm
- cloud/azure/database/mariadb/plugin.pm
Hi there,
since Azure also provides MariaDB as managed service, this pull requests adds the monitoring checks to provide the same checks as for MySQL.
Please check and merge.
BR,
Anonjo
> (plugin) cloud::azure::database::mariadb - add new plugin 

- cloud/aws/fsx/mode/discovery.pm
> (plugin) cloud::aws::fsx - Fix discovery mode

- apps/ipfabric/mode/discovery.pm
> (plugin) apps:ipfabric - fix disco output format

- cloud/nutanix/snmp/mode/storagepoolusage.pm
Closes https://github.com/centreon/centreon-plugins/issues/3596
> (plugin) virtualization-nutanix-snmp - fix typo in storagepools.pm 

- cloud/aws/elb/application/mode/connections.pm
- cloud/aws/elb/application/mode/discovery.pm
- cloud/aws/elb/application/mode/httpcodes.pm
- cloud/aws/elb/application/mode/targetshealth.pm
- cloud/aws/elb/network/mode/discovery.pm
Adding ELB ARN in host disco output for Application and Network discovery modes.
Add missing entries in ELB application --help
> (plugin) cloud::aws::elb - add ARN in host disco output for ELB app and network

- os/windows/wsman/mode/liststorages.pm
Add transformation option for discovery
> (plugin) os::windows::wsman::mode::liststorages - adding transformation options

- cloud/aws/elb/network/mode/listhealthtargetgroups.pm
Renaming variables for service health discovery
> (plugin) cloud::aws::elb:network - health service disco output format

- doc/en/developer/guide.md
> doc(update) convert to MD

- apps/monitoring/kadiska/custom/api.pm
- apps/monitoring/kadiska/mode/discovery.pm
- apps/monitoring/kadiska/mode/liststations.pm
- apps/monitoring/kadiska/mode/listtargets.pm
- apps/monitoring/kadiska/mode/listwatchers.pm
- apps/monitoring/kadiska/mode/tracerstatistics.pm
- apps/monitoring/kadiska/mode/watcherstatistics.pm
- apps/monitoring/kadiska/plugin.pm
Adding a new plugin for Kadiska monitoring application that helps you retrieve information from Kadiska Platform.
> (plugin) apps::monitoring::kadiska - add new plugin for Kadiska

- centreon/common/protocols/sql/mode/collection.pm
```
{
"sql": {
"connectHandleError": 1,
"tables": [
{ 
"name": "dual",
"query": "SELECT 1"
}
]
},
"selection": [
{
"name": "connection",
"critical": "%(builtin.connectMessage) =~ /ORA-01017/",
"formatting": {
"printf_msg":"connection status: %s [message: %s]",
"printf_var":[
"%(builtin.connectStatus)",
"%(builtin.connectMessage)"
],
"display_ok": true
}
}
],
"formatting":{
"custom_message_global": "All selections are OK",
"separator": "-"
}
}
```
> (collection) can handle connection error for sql collection

- apps/mulesoft/restapi/custom/api.pm
The Mulesoft plugin uses username and password by default for authentication,
using the `--api-username` and `--api-password` arguments.
This PR adds the support for OAuth2 authentication, and for that adds 2 new
arguments `--client-id` and `--client-secret`. Only one set of authentication
arguments can be used.
The desired authentication mechanism is thus inferred from the arguments used,
and the endpoint and payload is determined accordingly.
Cf [Access Management API documentation](https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/access-management-api/minor/1.0/pages/Authentication/)
for the overview, and https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-pl …
> (plugin) apps::mulesoft::restapi - adding OAuth2 authentication

- apps/ipfabric/custom/api.pm
- apps/ipfabric/mode/discovery.pm
- apps/ipfabric/mode/pathverification.pm
Adding snapshot-id parameter to let user choose on which snapshot monitoring will be based.
> (plugin) apps::ipfabric - add snapshot id param

- cloud/azure/network/trafficmanager/mode/endpointstatus.pm
- cloud/azure/network/trafficmanager/mode/queries.pm
Fixing help and metric label according to Microsoft documentation.
> (plugin) cloud::azure::network::trafficmanager - fix help and metric label

- storage/netapp/ontap/restapi/mode/aggregates.pm
- storage/netapp/ontap/restapi/plugin.pm
Creation of Netapp plugins to observe aggregate status and latency.
Freely inspired by volumes plugins
> (plugin) storage::netapp::ontap - add aggregates mode 

- cloud/nutanix/snmp/mode/clusterusage.pm
- cloud/nutanix/snmp/mode/containerusage.pm
- cloud/nutanix/snmp/mode/diskusage.pm
- cloud/nutanix/snmp/mode/hypervisorusage.pm
- cloud/nutanix/snmp/mode/storagepoolusage.pm
- cloud/nutanix/snmp/mode/vmusage.pm
Prefix output fix for all modes.
> (plugin) cloud::nutanix::snmp::monitor - Prefix output fix

- Jenkinsfile
> hotfix(ci): bad jenkinsfile

- cloud/aws/billing/mode/discovery.pm
- cloud/aws/billing/plugin.pm
Adding discovery mode to discover AWS billed services.
> (plugin) aws::billing::plugin - adding discovery mode

- apps/monitoring/kadiska/custom/api.pm
- apps/monitoring/kadiska/mode/watcherstatistics.pm
Update credential storage and update api path. 
Protect dividing value in mode.
> (plugin) apps::monitoring::kadiska - update credential storage

- cloud/aws/ec2/mode/discovery.pm
Adding platform details in EC2 discovery output.
> (plugin) cloud::aws::ec2::plugin - adding platform details in discovery output

- cloud/prometheus/restapi/mode/discovery.pm
- cloud/prometheus/restapi/plugin.pm
Adding discovery mode for Prometheus targets.
> (plugin) cloud::prometheus::restapi - adding discovery mode for Prometheus targets

- cloud/prometheus/restapi/mode/discovery.pm
- cloud/prometheus/restapi/plugin.pm
Adding discovery mode to discover Prometheus targets.
> (plugin) cloud::prometheus::plugin - adding discovery mode

- apps/monitoring/nodeexporter/windows/mode/cpu.pm
- apps/monitoring/nodeexporter/windows/mode/listinterfaces.pm
- apps/monitoring/nodeexporter/windows/mode/liststorages.pm
- apps/monitoring/nodeexporter/windows/mode/memory.pm
- apps/monitoring/nodeexporter/windows/mode/services.pm
- apps/monitoring/nodeexporter/windows/mode/storage.pm
- apps/monitoring/nodeexporter/windows/mode/traffic.pm
- apps/monitoring/nodeexporter/windows/plugin.pm
Adding Windows node exporter plugin to check Windows server through metrics exported by node exporter.
> (plugin) apps::monitoring::nodeexporter::windows - adding windows node exporter plugin

- apps/monitoring/nodeexporter/linux/mode/cpu.pm
- apps/monitoring/nodeexporter/linux/mode/load.pm
- apps/monitoring/nodeexporter/linux/mode/memory.pm
- apps/monitoring/nodeexporter/linux/mode/storage.pm
- apps/monitoring/nodeexporter/linux/mode/traffic.pm
Adding opt exit if no keys in counters in all modes.
Adding filter on storage for storage mode. 
Modify interface filter name.
> (plugin) apps::monitoring::nodeexporter::linux - enhancements on options

- cloud/aws/cloudwatch/mode/discovery.pm
> (plugin) cloud::aws::cloudwatch - Merge conflit fix

- cloud/azure/custom/api.pm
- cloud/azure/management/recovery/mode/backupjobsstatus.pm
Adding option to filter on timeframe for backup job status mode.
> (plugin) cloud::azure::management::recovery - adding filter on timeframe for backup job status

- cloud/azure/compute/virtualmachine/mode/cpu.pm
- cloud/azure/compute/virtualmachine/mode/diskio.pm
- cloud/azure/compute/virtualmachine/mode/memory.pm
- cloud/azure/compute/virtualmachine/mode/network.pm
- cloud/azure/compute/virtualmachine/mode/vmsstate.pm
- cloud/azure/custom/mode.pm
- cloud/azure/network/expressroute/mode/circuitstatus.pm
- cloud/azure/network/expressroute/mode/traffic.pm
- cloud/azure/network/vpngateway/mode/sitetraffic.pm
- cloud/azure/network/vpngateway/mode/tunneltraffic.pm
- cloud/azure/network/vpngateway/mode/vpngatewaystatus.pm
mode.pm edited to fix a bug when using --per-sec option with a mode having a mix between absolute and per second values.
> (plugin) cloud::azure::* Migrate from the legacy codebase to the new one

- apps/protocols/http/mode/collection.pm
```
{
"mapping": {},
"http": {
"requests": [
{
"name": "auth",
"hostname": "%(constants.hostname)",
"proto": "http",
"port": "80",
"endpoint": "/auth",
"headers": ["Accept:application/json", "Content-Type:application/json"],
"insecure": 1,
"timeout": 30,
"payload": {
"type": "json",
"value": {
"username": "%(constants.username)",
"password": "%(constants.password)"
}
},
"cache_file": "http_auth_%(constants.hostname).cache",
"cache_reload": 60,
"scenario_stopped": "%(builtin.httpCode.auth) != 200",
"backend": "curl",
"rtype": "json",
"parse": [
{
"name": "token",
"path": "$.token",
"entries": [
{ "id": "value" }
]
}
],
"requests": [
{
"name": "users",
"hostname": "%(constants.hostname)",
"proto": "http",
"port": "80",
"endpoint": "/test",
"headers": ["Accept:application/json", "x-auth-id: …
```
> (plugin) apps::protocols::http - mode collection add authentication system

- cloud/aws/cloudwatch/mode/discovery.pm
- cloud/aws/custom/awscli.pm
> Fix missing condition in AWS Unified disco

- Jenkinsfile
Tentative to optimize build time
> (ci/cd) Enhance sh to make curl use the same connection

- Jenkinsfile
> (JenkinsFile) Fix var in loop

- Jenkinsfile
> (wip) Replace CI with REFERENCE

- apps/microsoft/sccm/local/mode/databasereplicationstatus.pm
Add missing string counter type causing unknown thresholds error.
> (plugin) apps::microsoft::sccm::local::mode::databasereplicationstatus - fix unknown thresholds error

- notification/microsoft/office365/teams/mode/alert.pm
Adding redirection to newer resource status pages when using --action-links option.
> (plugin) notification::microsoft::office365::teams::plugin - adding redirection to newer resource status pages

- network/efficientip/snmp/mode/status.pm
- network/efficientip/snmp/plugin.pm
Adding mode to check role and status for Efficient IP.
Closes https://github.com/centreon/centreon-plugins/issues/3662.
> (plugin) network::efficientip::snmp - adding status mode

- apps/vmware/connector/mode/cpuvm.pm
Add example for --filter option, that avoid using it like --filter='REGEX'
> (plugin) apps::vmware::connector::mode::cpuvm - enhance help 

- cloud/azure/custom/api.pm
- cloud/azure/management/costs/mode/budgets.pm
- cloud/azure/management/costs/mode/listbudgets.pm
- cloud/azure/management/costs/plugin.pm
> (plugin) cloud::azure::management::costs - add list-budget mode

- cloud/azure/management/monitor/mode/discoverytenant.pm
Fixing issue with subscription ID parsing 
Adding option to filter on resource types
Adding tags[ ] when it doesn't exist
> (plugin) cloud::azure::management::monitor - fixing discovery tenant issues

- cloud/azure/management/costs/mode/listbudgets.pm
> (plugin) cloud::azure::management::costs - Fix disco_* subs

- os/linux/local/mode/pendingupdates.pm
Adding new metric displaying how many security updates are available.
> (plugin) os::linux::local::mode::pendingupdates - adding pending security updates metric 

- cloud/azure/management/costs/mode/listbudgets.pm
- contrib/tutorial/apps/myawesomeapp/api/mode/appmetrics.pm
- contrib/tutorial/apps/myawesomeapp/api/plugin.pm
Commented version of a basic mode.
> (contrib) Everything your grandma needs to know to write a plugin and a mode

- apps/monitoring/kadiska/custom/api.pm
- apps/monitoring/kadiska/mode/listwatchers.pm
- apps/monitoring/kadiska/mode/watcherstatistics.pm
Adding new metrics and filters for country, isp and work from anywhere users.
> (plugin) apps::monitoring::kadiska - adding new metrics and filters

- cloud/azure/common/storageaccount/filesharequota.pm
Modify output to make it human friendlier
Adding option to later be able to specify fileshare name
> (plugin) cloud::azure::storageaccount - Change output for human friendly output

- cloud/azure/classicstorage/storageaccount/plugin.pm
- cloud/azure/common/storageaccount/filesharequota.pm
- cloud/azure/common/storageaccount/listfileshares.pm
- cloud/azure/custom/api.pm
- cloud/azure/storage/storageaccount/plugin.pm
Enhancing fileshares monitoring and adding mode to list fileshares.
> (plugin) cloud::azure::storageaccount - enhancing fileshare monitoring mode, addi list fileshare

- apps/monitoring/kadiska/mode/watcherstatistics.pm
> (plugin) apps::monitoring::kadiska::watcherstatistics - fixing function name

- hardware/server/xfusion/ibmc/snmp/mode/components/component.pm
- hardware/server/xfusion/ibmc/snmp/mode/components/cpu.pm
- hardware/server/xfusion/ibmc/snmp/mode/components/fan.pm
- hardware/server/xfusion/ibmc/snmp/mode/components/harddisk.pm
- hardware/server/xfusion/ibmc/snmp/mode/components/logicaldrive.pm
- hardware/server/xfusion/ibmc/snmp/mode/components/memory.pm
- hardware/server/xfusion/ibmc/snmp/mode/components/pcie.pm
- hardware/server/xfusion/ibmc/snmp/mode/components/psu.pm
- hardware/server/xfusion/ibmc/snmp/mode/components/raidcontroller.pm
- hardware/server/xfusion/ibmc/snmp/mode/components/temperature.pm
- hardware/server/xfusion/ibmc/snmp/mode/hardware.pm
- hardware/server/xfusion/ibmc/snmp/plugin.pm
this pull request is to address the OID change in xFusion servers V6 (firmware v3+) the OID went from 1.3.6.1.4.1.2011 to 1.3.6.1.4.1.58132 (but the subtree is identical)
I basically just replaced "huawei" by "xfusion" and the oid root from the current huawei iBMC plugin.
without this change, the ibmc check from huawei that is working on v5 servers return "OK 0 components"
if possible, can you include a new "plugin pack" for xFusion server, the logo is there : https://www.xfusion.com/
- [X ] 22.04.x 
(haven't tested with another centreon version)
./centreon_plugins.pl --plugin=hardware::server::xfusion::ibmc::snmp::plugin --mode=hardware --hostname=xxxx --snmp-version='2c' --snmp-community='xxxxx'  --component='.*' --verbose
`example …
> (plugin) hardware::server::xfusion::ibmc::snmp::plugin - Add xFusion iBMC snmp monitoring

- cloud/aws/elasticache/mode/discovery.pm
- cloud/aws/elasticache/plugin.pm
> (plugin) cloud::aws::elasticache - Add Host Discovery rules to AWS Elasticache

- network/patton/smartnode/snmp/mode/call.pm
- network/patton/smartnode/snmp/mode/system.pm
- network/patton/smartnode/snmp/plugin.pm
Adding Patton SmartNode plugin
> (plugin) network::patton::smartnode::snmp - new

- apps/monitoring/kadiska/mode/listtargets.pm
> MON-16509-issues-on-kadiska-plugin-pack

- .github/workflows/plugins.yml
fix changes detection
package plugins only when needed
> fix(ci): fix changes detection

- .github/workflows/get-environment.yml
> fix(ci): fix environment parsing

- .github/packaging/debian/copyright
- .github/packaging/rpm/plugin.spectemplate
> chore(license): update package licenses

- src/contrib/collection/README.md
- src/contrib/collection/snmp/moxa-iologik-collection.json
Adding a new folder to share files for the collection mode.
new file:   src/contrib/collection/README.md
new file:   src/contrib/collection/snmp/moxa-iologik-collection.json
> Adding new collection folder

- .github/actions/package/action.yml
- .github/actions/runner-docker/action.yml
- .github/docker/Dockerfile.packaging-plugins-alma8
- .github/docker/Dockerfile.packaging-plugins-alma9
- .github/docker/Dockerfile.packaging-plugins-bullseye
- .github/docker/Dockerfile.packaging-plugins-centos7
- .github/workflows/docker-builder-packaging-plugins.yml
- .github/workflows/plugin-package.yml
- .github/workflows/plugins.yml
- src/centreon/common/adic/tape/snmp/mode/hardware.pm
chore(ci): move to harbor docker registry
> chore(ci): move to harbor docker registry

- .github/issue_template.md
> update(doc) emails

- src/apps/centreon/sql/mode/multiservices.pm
> (plugin) apps::centreon::sql::mode::multiservices - allow host arrays in config file

- .github/scripts/process-plugins.py
- src/apps/protocols/dns/lib/dns.pm
fix(ci): detect properly plugin changes in lib directory
> fix(ci): detect properly plugin changes in lib directory

- src/os/windows/wsman/mode/cpu.pm
cpu manage data reset and negative results
> (plugin) os::windows::wsman - mode cpu fixes

- src/os/linux/local/mode/pendingupdates.pm
brackets were missing
**Fixes** MON-18151
> (plugin) os::linux::local - mode pending-updates - add brackets

- src/centreon/common/protocols/actuator/custom/centreonmap.pm
> Mon 17054 plugin jvm actuator dont works with centreon map engine endpoint

- src/cloud/azure/custom/api.pm
add header param
**Fixes** MON-18478
> (plugin) add header in azure_list_resources_set_url function (api custommode)

- .github/actions/package/action.yml
- .github/packaging/debian/control.body.template
- .github/scripts/plugin-packaging-deb.sh
- packaging/centreon-plugin-Applications-Cisco-Ssms-Restapi/deb.json
fix(packaging): manage custom instructions for debian packaging
**Fixes** MON-18822
> fix(packaging): manage custom instructions for debian packaging

- packaging/centreon-plugin-Applications-Cisco-Ssms-Restapi/deb.json
- packaging/centreon-plugin-Network-Cisco-Ssms-Restapi/deb.json
- packaging/centreon-plugin-Network-Cisco-Ssms-Restapi/pkg.json
- packaging/centreon-plugin-Network-Cisco-Ssms-Restapi/rpm.json
fix(packaging): remove centreon-plugin-Network-Cisco-Ssms-Restapi
> fix(packaging): remove centreon-plugin-Network-Cisco-Ssms-Restapi

- src/apps/microsoft/activedirectory/wsman/mode/dcdiag.pm
This pattern should work on italian OS language
> dcdiag for italian language

- src/apps/microsoft/activedirectory/local/mode/dcdiag.pm
This pattern should work on italian OS language
> dcdiag - add italian parsing

- .github/workflows/perl-vmware-vsphere.yml
fix(ci): fix directory name for unstable delivery
**Fixes** MON-19158
> fix(ci): fix directory name for unstable delivery

- src/apps/monitoring/iplabel/newtest/restapi/mode/scenarios.pm
fix options
**Fixes** MON-19046
> apps::monitoring::iplabel::newtest::restapi - mode scenarios - fix options

- src/centreon/plugins/dbi.pm
- src/centreon/plugins/http.pm
- src/centreon/plugins/multi.pm
- src/centreon/plugins/output.pm
- src/centreon/plugins/script.pm
- src/centreon/plugins/script_custom.pm
- src/centreon/plugins/script_simple.pm
- src/centreon/plugins/script_snmp.pm
- src/centreon/plugins/script_sql.pm
- src/centreon/plugins/script_wsman.pm
- src/centreon/plugins/snmp.pm
- src/centreon/plugins/ssh.pm
Some other improvements in help messages.
> Mon 16172 improve most used helps

- packaging/centreon-plugin-Network-Cambium-Cnpilot-Snmp/deb.json
- packaging/centreon-plugin-Network-Cambium-Cnpilot-Snmp/pkg.json
- packaging/centreon-plugin-Network-Cambium-Cnpilot-Snmp/rpm.json
- src/network/cambium/cnpilot/snmp/plugin.pm
Adding Interface discovery rule.
> Rebase branch and adding interfaces discovery rule

- .github/CODEOWNERS
- .github/workflows/tests-functional.yml
- tests/functional/cloud/aws/cloudtrail/countevents.sh
Update GitHub action for functional tests
> Update GitHub action

- src/cloud/azure/compute/virtualmachine/plugin.pm
Removed unexisting mode found by @itoussies
> fix: removed unexisting mode

- src/centreon/plugins/script_custom.pm
> enh: bad sentence in help message

- packaging/centreon-plugin-Applications-Tosca-Restapi/deb.json
- packaging/centreon-plugin-Applications-Tosca-Restapi/pkg.json
- packaging/centreon-plugin-Applications-Tosca-Restapi/rpm.json
- src/apps/tosca/restapi/custom/api.pm
- src/apps/tosca/restapi/mode/executionliststatus.pm
- src/apps/tosca/restapi/mode/scenariostatus.pm
- src/apps/tosca/restapi/plugin.pm
```
perl centreon_plugins.pl --plugin=apps::tosca::restapi::plugin --mode=scenario-status --hostname='myhostname' --port='80' --url-path='/rest/toscacommander' --api-username='***' --api-password='***' --workspace='MyWorkspace' --scenario-id='81121ba4-1e71-4915-ab70-9913071413f6' --warning-status='' --critical-status='%{result} !~ /Passed/' --warning-duration='' --critical-duration=''
OK: Scenario 'My Scenario' result is 'Passed' [start time:'2023-06-09T11:22:34.6762497+02:00', end time:'2023-06-09T11:22:47.9319589+02:00'], duration: 13.26 seconds | 'scenario.duration.seconds'=13.26s;;;0;
```
```
perl centreon_plugins.pl --plugin=apps::tosca::restapi::plugin --mode=execution-list-status --hostname='myhostname' --port='80' --url-path='/rest/toscacommander' --api-username='***' …
```
> new(plugin): add tosca restapi plugin

- .github/packaging/centreon-plugin.yaml.template
Roll back to xz, to handle older systems.
> fix(packaging): roll back pkg compressor to xz

- .github/workflows/tests-functional.yml
- src/cloud/aws/cloudtrail/mode/countevents.pm
- tests/functional/cloud-aws-cloudtrail.robot
- tests/functional/cloud-azure-policyinsights-policystates.robot
- tests/functional/cloud/aws/cloudtrail/test.robot
- tests/resources/mockoon/cloud-azure-policyinsights-policystates.json
Rewrite tests from bash to robot framework, and adapt the associated github action
MON-19916
> Adapt plugins tests from bash to robot framework

- .github/workflows/plugin-delivery.yml
- .github/workflows/plugins.yml
push plugin release tag
**Fixes** MON-20486
> enh(release): push plugins release tag

- src/apps/monitoring/kadiska/mode/nettracerstatistics.pm
- src/apps/monitoring/kadiska/mode/watcherstatistics.pm
> fix(plugin): app::monitoring::kadiska::nettracerstatistics - help fix

- .github/docker/Dockerfile.packaging-plugins-alma8
- .github/docker/Dockerfile.packaging-plugins-alma9
- .github/workflows/plugins-selinux.yml
- selinux/packaging/centreon-plugins-selinux.yaml
- selinux/packaging/scripts/centreon-plugins-selinux-postinstall.sh
- selinux/packaging/scripts/centreon-plugins-selinux-preremove.sh
- selinux/src/centreon-plugins.if
- selinux/src/centreon-plugins.te
feat(ci): package centreon-plugins-selinux
**Fixes** MON-20157
> feat(ci): package centreon-plugins-selinux

- .github/workflows/connector-vmware.yml
- .github/workflows/docker-builder-packaging-plugins.yml
- .github/workflows/get-environment.yml
- .github/workflows/nrpe.yml
- .github/workflows/perl-vmware-vsphere.yml
- .github/workflows/plugin-delivery.yml
- .github/workflows/plugins-selinux.yml
- .github/workflows/plugins.yml
- .github/workflows/tests-functional.yml
upgrade checkout action from v3 to v4
> enh(chore): upgrade checkout action

- src/network/juniper/common/screenos/snmp/mode/components/fan.pm
- src/network/juniper/common/screenos/snmp/mode/hardware.pm
Fix Fan status
**Fixes** MON-21583
> (plugin) network::juniper::ssg::plugin fix fan status

- src/cloud/docker/local/mode/containerusage.pm
https://github.com/centreon/centreon-plugins/pull/4683
> MON-22340 - [Plugin] - fix(docker/local): fix cache name to prevent conflict

- .github/issue_template.md
Guide the issue creators to the watch for anything else than bugs
> Change issue template

- src/hardware/printers/standard/rfc3805/mode/markersupply.pm
> fix: "other" type of marker supply was not handled

- src/hardware/server/hp/ilo/xmlapi/mode/hardware.pm
Retake #4698 to fix #4697 
**Fixes** #4697
> fix: bad status (critical instead of warning)

- .github/workflows/actionlint.yml
- .github/workflows/nrpe.yml
> feat(ci): add linting to worflow and actions files

- src/notification/email/mode/alert.pm
Check for credentials before requesting for service's graph.
And moreover allows to not retrieve graphs as it can be impossible due to architecture constraints, and because it can drastically slow down Engine as notifications are sequential in scheduling plan.
> enh(email/alert): do not retrieve service graph if no credentials

- src/apps/protocols/http/mode/collection.pm
Add [PR 4684](https://github.com/centreon/centreon-plugins/pull/4684) in this enhancement work in progress.
> [MON-22338] [Plugins] Improve the troubleshooting of HTTP Collections

- src/os/windows/snmp/mode/service.pm
> (plugin) os::windows::snmp - mode service add total counter

- .github/workflows/perl-openwsman.yml
- dependencies/perl-openwsman/perl-openwsman.yaml
Adding the perl dependency openwsman in centreon-plugins repository.
> [CTOR-151] Unable to upgrade after installing Wsman plugin on RHEL 9

- .github/workflows/perl-openwsman.yml
- dependencies/perl-openwsman/libwsman.yaml
- dependencies/perl-openwsman/perl-openwsman.yaml
- dependencies/perl-openwsman/sblim-sfcc.yaml
… (only for debian bullseye)
Adding missing packages for openwsman:
- sblim-sfcc (only for debian bullseye)
- libwsman1 (same version as perl-openwsman)
> [CTOR-151] Adding missing packages

- .github/actions/deb-delivery/action.yml
- .github/actions/rpm-delivery/action.yml
Fix to avoid multiple deliveries of the same package when there is more than 1 delivery in a github action.
> [CTOR-151] fix delivery

- .github/actions/package-nfpm/action.yml
- dependencies/perl-openwsman/libwsman.yaml
- dependencies/perl-openwsman/perl-openwsman.yaml
- dependencies/perl-openwsman/sblim-sfcc.yaml
Another fix for multiple deliveries.
> fix multiple deliveries

- .github/workflows/perl-cpan-libraries.yml
Installation problems with version 0.32 => v0.31 forced
> [CTOR-237] Fix broken dependency for vmware-connector

- .github/actions/deb-delivery-legacy/action.yml
- .github/actions/deb-delivery/action.yml
- .github/actions/package-nfpm/action.yml
- .github/actions/package/action.yml
- .github/actions/promote-to-stable/action.yml
- .github/actions/rpm-delivery-legacy/action.yml
- .github/actions/rpm-delivery/action.yml
- .github/actions/runner-docker/action.yml
- .github/dependabot.yml
- .github/workflows/actionlint.yml
- .github/workflows/connector-vmware.yml
- .github/workflows/docker-builder-packaging-plugins.yml
- .github/workflows/get-environment.yml
- .github/workflows/nrpe.yml
- .github/workflows/perl-cpan-libraries.yml
- .github/workflows/perl-crypt-argon2.yml
- .github/workflows/perl-filesys-smbclient.yml
- .github/workflows/perl-json-path.yml
- .github/workflows/perl-keepass-reader.yml
- .github/workflows/perl-libssh-session.yml
- .github/workflows/perl-net-curl.yml
- .github/workflows/perl-openwsman.yml
- .github/workflows/perl-vmware-vsphere.yml
- .github/workflows/plink.yml
- .github/workflows/plugin-delivery.yml
- .github/workflows/plugins-selinux.yml
- .github/workflows/plugins.yml
- .github/workflows/tests-functional.yml
> enh(chore): github actions hardening

- .github/workflows/tests-functional.yml
> enh(tests): snmpsimd is way too verbose and it does not help at all

- .github/dependabot.yml
- .github/workflows/actionlint.yml
> enh(ci): add consistent labels

- packaging/centreon-plugin-Notification-Email/deb.json
- packaging/centreon-plugin-Notification-Email/rpm.json
- src/notification/email/mode/alert.pm
- src/notification/email/templates/bam.pm
- src/notification/email/templates/host.pm
- src/notification/email/templates/metaservice.pm
- src/notification/email/templates/resources.pm
- src/notification/email/templates/service.pm
- src/notification/email/templates/style.pm
Reshape of email notification, with mobile, gmail, outlook compliancy
> Enhance notification look - MON-24756

- src/contrib/collection/snmp/zxtm-pool.json
- src/contrib/collection/snmp/zxtm-virtualserver.json
New snmp collection files to monitor pools a virtual servers of ZXTM devices.
https://www.circitor.fr/Mibs/Html/Z/ZXTM-MIB-SMIv2.php
> Enh collection zxtm pool

- src/centreon/common/protocols/sql/mode/sqlstring.pm
> [CTOR-241] [Plugin] [Plugin centreon-plugin-Applications-Databases-Oracle-20231215-102351.el8.noarch] Cannot load module --mode

- src/centreon/plugins/alternative/Getopt.pm
- src/centreon/plugins/templates/counter.pm
Enhance list-counter option display to JSON format.
> [CTOR-236] [Plugin] Ensure metrics list is available for MC documentation

- .github/actions/package-nfpm/action.yml
fix(ci): add distrib suffix to plugins deb packages
**Fixes** MON-35290
> fix(ci): add distrib suffix to plugins deb packages

- .github/workflows/perl-json-path.yml
enh(ci): json path version 1.0.4
> enh(ci): json path version 1.0.4

- README.md
Giving a link to the development guide and more context in general.
> enh(readme): restructuring the readme file

- .github/workflows/perl-cpan-libraries.yml
- .github/workflows/perl-crypt-argon2.yml
- .github/workflows/perl-json-path.yml
- .github/workflows/perl-libssh-session.yml
- .github/workflows/perl-net-curl.yml
- .github/workflows/plink.yml
- .github/workflows/plugins.yml
- .github/workflows/spellchecker.yml
- .github/workflows/tests-functional.yml
> chore(ci): upgrade gha

- .github/workflows/plugins.yml
> chore(ci): downgrade action

- .github/actions/package-nfpm/action.yml
- .github/workflows/nrpe.yml
- nrpe/packaging/centreon-nrpe4-daemon.yaml
- nrpe/packaging/files/nrpe4.deb.service
- nrpe/packaging/files/nrpe4.rpm.service
- nrpe/packaging/files/nrpe4.sysconfig
- nrpe/packaging/files/nrpe4_add_centreon_cmd.patch
- nrpe/packaging/scripts/centreon-nrpe4-daemon-postinstall.sh
- nrpe/packaging/scripts/centreon-nrpe4-daemon-preinstall.sh
- nrpe/packaging/scripts/centreon-nrpe4-daemon-preremove.sh
- packaging/centreon-plugin-Operatingsystems-Linux-Local/deb.json
- packaging/centreon-plugin-Operatingsystems-Linux-Local/rpm.json
We are actually building nrpe4 as centreon-nrpe3-daemon. For the sake of clarity we have to package it accordingly.
> new(pkg): build the nrpe daemon as nrpe4

- src/apps/backup/veeam/wsman/mode/vsbjobs.pm
Demonstration of the necessity to add more automated tests.
> fix(syntax): added missing curly bracket

- src/cloud/azure/integration/eventgrid/mode/events.pm
Smaaaall fix the to help message.
> fix(azure-cloud-eventgrid): fix help threshold

- .github/actions/package-nfpm/action.yml
- packaging/centreon-plugin-Hardware-Devices-Camera-Avigilon-Snmp/pkg.json
- src/hardware/devices/camera/avigilon/snmp/plugin.pm
Fix packaging snmp_standard missing
Add list-interface mode
> [CTOR-38][Plugin] Fix Packaging- New pack Avigilon camera snmp 

- .github/actions/package-nfpm/action.yml
- packaging/centreon-plugin-Hardware-Devices-Camera-Avigilon-Snmp/pkg.json
Fix packaging snmp_standard missing
Add list-interface mode
> [CTOR-38][Plugin] Fix Packaging again - New pack Avigilon camera snmp

- packaging/centreon-plugin-Virtualization-Ovirt-Api/deb.json
- packaging/centreon-plugin-Virtualization-Ovirt-Api/pkg.json
- packaging/centreon-plugin-Virtualization-Ovirt-Api/rpm.json
> [CTOR-26][Plugin] New Pack : oVirt

- .github/actions/promote-to-stable/action.yml
* minor fixes
* add support for multiple debian distributions to promote action
**Fixes** # MON-51089
> enh(promote): handle debian package promotion for multiple distributions

- packaging/centreon-plugin-Applications-RRDCached/deb.json
- packaging/centreon-plugin-Applications-RRDCached/pkg.json
- packaging/centreon-plugin-Applications-RRDCached/rpm.json
> [CTOR-514] [Plugin] New Pack RRDCached

- .github/actions/promote-to-stable/action.yml
* fix pattern used for promote upload that would cause unexpected uploads
**Fixes** #MON-51089
> fix(promote): fix pattern used for promote upload

- src/apps/monitoring/quanta/restapi/mode/webscenariosavailability.pm
Change default value in help according to the code one.
> [CTOR-566][Plugin] New pack Quanta Restapi (Fix)

- .github/actions/package-nfpm/action.yml
- packaging/centreon-plugin-Applications-RRDCached/pkg.json
- src/apps/rrdcached/custom/tcp.pm
- src/apps/rrdcached/custom/unix.pm
- src/apps/rrdcached/mode/ping.pm
- src/apps/rrdcached/mode/stats.pm
- src/apps/rrdcached/plugin.pm
- tests/resources/spellcheck/stopwords.t
- converted stats.pm to latest guidelines
- took the socket connection out of it into two custom modes
- added a PING mode
```
src/centreon_plugins.pl --plugin apps::rrdcached::plugin --custommode=tcp --mode ping --hostname 192.168.59.134
OK: response: 0 PONG 
```
```
perl pycharm/src/centreon_plugins.pl --plugin apps::rrdcached::plugin --mode ping --custommode unix 
OK: response: 0 PONG 
```
```
perl src/centreon_plugins.pl --plugin apps::rrdcached::plugin --mode stats --custommode=tcp --hostname 192.168.59.134 --critical-rrdcached-queue-length=1 --warning-rrdcached-waiting-updates=2 --verbose
WARNING: waiting updates: 3123 | 'rrdcached.queue-length'=0;;0:1;0; 'rrdcached.waiting-updates'=3123;0:2;;0;
Received data - QueueLength: 0
Received data - UpdatesReceived: 6364
Received data - …
```
> enh(plugin): refactored the RRDcached plugin

- src/apps/protocols/http/plugin.pm
> fix(plugin) Json PATH lib - CTOR-525

- packaging/centreon-plugin-Applications-TrendMicro-Iwsva/pkg.json
- src/apps/trendmicro/iwsva/snmp/mode/interfaces.pm
- src/apps/trendmicro/iwsva/snmp/plugin.pm
- tests/resources/spellcheck/stopwords.t
> fix(packaging) CTOR-591 TrendMicro - Iwsva: List-mode inaccurate

- src/apps/monitoring/loggly/restapi/custom/api.pm
- src/apps/monitoring/loggly/restapi/mode/events.pm
- src/apps/monitoring/loggly/restapi/mode/fields.pm
- src/apps/monitoring/loggly/restapi/plugin.pm
- tests/resources/spellcheck/stopwords.t
> style(plugin): adjust indentation - CTOR-586

- src/apps/trendmicro/iwsva/snmp/plugin.pm
Fix typo according pack parameters
> fix(packaging) CTOR-591 Trendmicro IWSVA packaging

- src/storage/datacore/restapi/custom/api.pm
- src/storage/datacore/restapi/mode/poolspaceusage.pm
- tests/resources/spellcheck/stopwords.t
- tests/robot/storage/datacore/restapi/storage-datacore-api.json
> CTOR-633 : plugin(storage::datacore::restapi) : Add little fixes and enhancements

- src/centreon/plugins/mqtt.pm
- tests/resources/spellcheck/stopwords.t
REFS: CTOR-374
Quick enhancement.
> enh(plugin): handle empty login/password

- src/os/windows/wsman/mode/listinterfaces.pm
Fixed the status description and removed the special char
> Update listinterfaces.pm - special char in status

- src/network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
- src/network/cisco/meraki/cloudcontroller/restapi/mode/devices.pm
- src/network/cisco/meraki/cloudcontroller/restapi/mode/listvpntunnels.pm
- src/network/cisco/meraki/cloudcontroller/restapi/mode/networks.pm
- src/network/cisco/meraki/cloudcontroller/restapi/mode/vpntunnels.pm
- src/network/cisco/meraki/cloudcontroller/restapi/plugin.pm
- tests/resources/spellcheck/stopwords.t
- tests/robot/network/cisco/meraki/cloudcontroller/restapi/meraki.mockoon.json
- tests/robot/network/cisco/meraki/cloudcontroller/restapi/vpntunnels.robot
REFS: CTOR-98
New mode developed by @garnier-quentin (#5067) + some tests
robot vpntunnels.robot
> add(mode): new vpn tunnels mode to meraki api plugin + tests

- .github/workflows/perl-cpan-libraries.yml
gorgone build can't install this lib : 
```
Error: 
Problem 1: package centreon-gorgone-24.05.0-1719230816.578bdc2.el8.noarch from @commandline requires perl(Mojo::IOLoop::Signal), but none of the providers can be installed
- conflicting requests
- nothing provides perl(Mojolicious) >= 9.22 needed by perl-Mojo-IOLoop-Signal-0.003-1.el8.noarch from centreon-plugins-23.10-stable-noarch
Problem 2: package centreon-gorgone-centreon-config-24.05.0-1719230816.578bdc2.el8.noarch from @commandline requires centreon-gorgone = 24.05.0-1719230816.578bdc2.el8, but none of the providers can be installed
- package centreon-gorgone-24.05.0-1719230816.578bdc2.el8.noarch from @commandline requires perl(Mojo::IOLoop::Signal), but none of the providers can be installed
(try to add '--skip-broken' to skip …
```
> fix(gorgone) fix Mojo::IOLoop::Signal dependency on rpm for gorgone

- .github/workflows/plugins.yml
- src/centreon/common/adic/tape/snmp/mode/hardware.pm
Handle node16 deprectiation on runners + el7 depreciation
* use alma8 docker container to package EL7 packages.
Fixes #MON-78447
* **HTTP API (SOAP, …
> use alma8 for packaging for plugins packaging

- .github/workflows/docker-builder-packaging-plugins.yml
* remove centos7 entry from docker builder matrix (since the centos7 image will not be used anymore)
**Fixes** #MON-78447
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk`) or [SNMP …
> fix(ci): remove centos7 from docker-builder matrix

- .github/workflows/docker-builder-packaging-plugins.yml
- .github/workflows/docker-builder-testing-plugins.yml
- .github/workflows/perl-cpan-libraries.yml
- .github/workflows/perl-crypt-argon2.yml
- .github/workflows/perl-json-path.yml
- .github/workflows/perl-libssh-session.yml
- .github/workflows/perl-net-curl.yml
- .github/workflows/plink.yml
- .github/workflows/plugins.yml
- .github/workflows/spellchecker.yml
> chore(deps): absorb 24.07 dependabot GitHub Actions updates

- src/network/sonus/sbc/snmp/mode/cpu.pm
- tests/resources/spellcheck/stopwords.t
CTOR-728
https://github.com/centreon/centreon-plugins/issues/4792
Test before the change
```
perl centreon_plugins.pl --plugin=network::sonus::sbc::snmp::plugin --mode=cpu --critical-core=4 --hostname=toto
```
Returns
```
Unknown option: critical-core at /centreon-plugins/src/centreon/plugins/alternative/Getopt.pm line 81. 
```
With fix it returns
```
UNKNOWN: SNMP Session: unable to create 
```
> CTOR-728 Plugin(network::sonus::sbc::snmp) - Mode(cpu) : Unknown option

- .github/workflows/perl-cpan-libraries.yml
Found missing dependencies while running tests for AWS plugins.
**Fixes** CTOR-765
> fix(library and packaging): add missing dependencies for Paws

- .github/workflows/plugins.yml
- src/centreon/plugins/dbi.pm
- tests/resources/spellcheck/stopwords.t
This PR make all plugins tests run on arm host.
**Fixes** # (CTOR-539)
Check the tests are all correclty launched, and successfully finish.
> tests(plugins): Run all tests on arm64 architecture

- .github/workflows/docker-builder-packaging-plugins.yml
- .github/workflows/docker-builder-testing-plugins.yml
- .github/workflows/perl-cpan-libraries.yml
- .github/workflows/perl-crypt-argon2.yml
- .github/workflows/perl-json-path.yml
- .github/workflows/perl-libssh-session.yml
- .github/workflows/perl-net-curl.yml
- .github/workflows/plink.yml
- .github/workflows/plugins.yml
> chore(deps): absorb 24.08 dependabot GitHub Actions updates

- packaging/centreon-plugin-Network-Backbox-Rest/deb.json
- packaging/centreon-plugin-Network-Backbox-Rest/pkg.json
- packaging/centreon-plugin-Network-Backbox-Rest/rpm.json
Adding missing packaging for Backbox
> fix(plugin): add backbox packaging

- .github/PULL_REQUEST_TEMPLATE.md
New checklist items after some surprises during the last release
> enh(pr-template): add checklist items to secure new plugins delivery

- src/storage/hp/primera/restapi/custom/api.pm
Internal PR for https://github.com/centreon/centreon-plugins/pull/5183
https://github.com/centreon/centreon-plugins/pull/5183
> Quick fix on HPE-Primera-RestAPI 

- .github/docker/packaging/Dockerfile.packaging-plugins-bookworm
- .github/docker/packaging/Dockerfile.packaging-plugins-bullseye
- .github/docker/packaging/Dockerfile.packaging-plugins-jammy
- a new one needed to build Crypt::OpenSSL::AES
- all the ones that are needed to build the .deb packages to make builds faster
> enh(dockerfiles): added new dependencies

- .github/actions/package-nfpm/action.yml
- .github/actions/parse-distrib/action.yml
- .github/actions/promote-to-stable/action.yml
- .github/workflows/perl-cpan-libraries.yml
- .github/workflows/perl-filesys-smbclient.yml
- src/database/mysql/plugin.pm
chore(packaging): update deb packages naming convention
**Fixes** MON-147080
> chore(packaging): update deb packages naming convention

- .github/workflows/perl-cpan-libraries.yml
- .github/workflows/perl-filesys-smbclient.yml
- .github/workflows/plink.yml
* update legacy packaging
Fixes #MON-50538
* **HTTP API (SOAP, Rest/Json, XML-RPC)**: …
> enh(ci): update legacy packaging 

- .github/workflows/connector-vmware.yml
- connectors/vmware/changelog
- connectors/vmware/packaging/centreon-plugin-virtualization-vmware-daemon.yaml
- connectors/vmware/src/centreon/script/centreon_vmware.pm
Refs: CTOR-984
Added missing file in packaging
> fix(vmware-daemon): add missing centreonvault.pm file to packaging

- .github/actions/promote-to-stable/action.yml
* fix an issue that would cause debian promote to use an invalid distrib pattern during debian promotion
**Fixes** #MON-150937
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk`) or [SNMP …
> fix(promote): fix promote behavior to handle new debian package naming

- as400/connector.as400.install/init-script/centreon-as400-sysconfig
- as400/packaging/centreon-as400-daemon.yaml
* set missing config noreplace flag on configuration files
* remove deprecated java option from as400 service env file
**Fixes** #MON-151152 #CTOR-1006
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk`) or [SNMP …
> fix(packaging): fix as400 packaging

- as400/changelog
- as400/connector.as400.install/init-script/centreon-as400-sysconfig
- as400/connector.as400/pom.xml
- as400/packaging/centreon-as400-daemon.yaml
- connectors/vmware/changelog
- connectors/vmware/src/centreon/script/centreon_vmware.pm
- connectors/vmware/src/centreon/script/centreonvault.pm
- connectors/vmware/src/centreon/vmware/common.pm
> Sync hotfix 20241018

- .github/workflows/as400.yml
- as400/changelog
- as400/connector.as400/pom.xml
- as400/packaging/centreon-as400-daemon.yaml
> Sync hotfix 20241021

- .github/docker/packaging/Dockerfile.packaging-plugins-java-alma8
- .github/docker/packaging/Dockerfile.packaging-plugins-java-alma9
* update java 17 install in containers
**Fixes** #MON-151570
* **HTTP API (SOAP, …
> fix(ci): update openjdk 17 install in containers

- .github/workflows/as400.yml
- .github/workflows/connector-vmware.yml
- .github/workflows/docker-builder-packaging-plugins.yml
- .github/workflows/docker-builder-testing-plugins.yml
- .github/workflows/docker-builder-unit-tests.yml
- .github/workflows/nrpe.yml
- .github/workflows/perl-cpan-libraries.yml
- .github/workflows/perl-crypt-argon2.yml
- .github/workflows/perl-filesys-smbclient.yml
- .github/workflows/perl-json-path.yml
- .github/workflows/perl-keepass-reader.yml
- .github/workflows/perl-libssh-session.yml
- .github/workflows/perl-net-curl.yml
- .github/workflows/perl-openwsman.yml
- .github/workflows/perl-vmware-vsphere.yml
- .github/workflows/plink.yml
- .github/workflows/plugins-selinux.yml
- .github/workflows/plugins.yml
* update push jobs in workflows
Fixes #MON-50538
* **HTTP API (SOAP, Rest/Json, …
> enh(ci): update push and pull jobs in workflows

- .github/actions/parse-distrib/action.yml
fix(ci): add new outputs to parse-distrib action
**Fixes** MON-78778
> fix(ci): add new outputs to parse-distrib action

- .github/actions/package-delivery/action.yml
fix(ci): fix jfrog rpm upload command
**Fixes** MON-78778
> fix(ci): fix jfrog rpm upload command

- .github/actions/package-delivery/action.yml
fix(ci): upload each package once
> fix(ci): upload each package once

- .github/scripts/test-all-plugins.py
Please include a short resume of the changes and what is the purpose of this pull request. 
Any relevant information should be added to help **reviewers** to understand what are the stakes 
of the pull request.
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c public …
> fix(tests): Change the way test-all-plugins.py identifies the directories

- src/apps/backup/commvault/commserve/restapi/mode/storagepools.pm
Applying PR #5141 - Thanks @jouleSoft 🙏🏻 
Also thanks to @gagzou for confirming the validity of the fix.
Refs: CTOR-851
> fix(commvault-storagepools): avoid division by 0

- src/os/linux/local/mode/process.pm
- tests/os/linux/local/process.robot
- tests/os/linux/local/process_bin/ps-centreon.output
- tests/os/linux/local/process_bin/ps-sap.output
- tests/resources/spellcheck/stopwords.txt
Following #5275 after branch renaming
> fix(linux-local): limit column size to avoid filter issues

- packaging/centreon-plugin-Notification-Slack/deb.json
- packaging/centreon-plugin-Notification-Slack/pkg.json
- packaging/centreon-plugin-Notification-Slack/rpm.json
Add slack notification fatpack
CTOR-1215
Install the Fatpack on a dev env and try to use it
> CTOR-1215 : Packaging(centreon-plugin-Notification-Slack) : Missing packages on plugin repository

- .github/actions/package-delivery/action.yml
fix(ci): fix release_type check in delivery action
> fix(ci): fix release_type check in delivery action

- .github/actions/package-delivery/action.yml
fix(ci): fix delivery condition
> fix(ci): fix delivery condition

- .github/workflows/perl-cpan-libraries.yml
Set version for net-mqtt-simple
> fix(ci): set version for net-mqtt-simple

- .github/actions/package-delivery/action.yml
- src/blockchain/hyperledger/exporter/plugin.pm
> test(ci): test release 1

- .github/actions/package-delivery/action.yml
- .github/workflows/plugins.yml
- src/blockchain/hyperledger/exporter/plugin.pm
> test(ci): test release 2

- .github/actions/package-delivery/action.yml
- src/blockchain/hyperledger/exporter/plugin.pm
> test(ci): test release 4

- .github/actions/package-delivery/action.yml
- .github/workflows/plugins.yml
- src/blockchain/hyperledger/exporter/plugin.pm
> test(ci): test release 5

- .github/actions/package-delivery/action.yml
- .github/workflows/plugins.yml
> test(ci): test release 6

- .github/actions/package-delivery/action.yml
- .github/workflows/plugins.yml
- src/blockchain/hyperledger/exporter/plugin.pm
> test(ci): test release 7

- .github/actions/package-delivery/action.yml
- .github/workflows/plugins.yml
- src/blockchain/hyperledger/exporter/plugin.pm
> test(ci): test release 8

- .github/actions/package-delivery/action.yml
- .github/workflows/plugins.yml
- src/blockchain/hyperledger/exporter/plugin.pm
fix(ci): fix release/hotfix pr detection
**Fixes** MON-78778
> fix(ci): fix release/hotfix pr detection

- doc/en/conf.py
Remove links to old documentation web page.
CTOR-540
> CTOR-540 : Remove links to old documentation

- .github/PULL_REQUEST_TEMPLATE.md
> CTOR-985-anonymize-user-data-for-automated-tests-purpose

- src/centreon/common/huawei/standard/snmp/mode/interfaces.pm
- src/centreon/plugins/output.pm
- src/network/aruba/cppm/snmp/mode/cpu.pm
- src/snmp_standard/mode/cpu.pm
- src/snmp_standard/mode/diskio.pm
- src/snmp_standard/mode/inodes.pm
- src/snmp_standard/mode/interfaces.pm
- src/snmp_standard/mode/listdiskspath.pm
- tests/resources/spellcheck/stopwords.txt
CTOR-962
Plugin(os::linux::snmp)
Report documentations edits in the help sections
> doc(helps sections): Correct helps sections

- src/centreon/plugins/output.pm
Fix a typo in the output.pm help section
> doc(output): fix the output.pm help section

- packaging/centreon-plugin-Network-Huawei-Snmp/pkg.json
> fix(packaging): bad path to plugin code

- packaging/centreon-plugin-Network-Huawei-Snmp/pkg.json
I must be too tired...
Refs: CTOR-13
> fix(huawei-standard): bad path to huawei common code

- src/hardware/server/lenovo/xcc/snmp/mode/components/cpu.pm
- src/hardware/server/lenovo/xcc/snmp/mode/components/health.pm
- src/hardware/server/lenovo/xcc/snmp/mode/components/memory.pm
Verbose output was: 
```
Checking disks
disk 'Anonymized 016' status is Normal [instance: 40].
disk 'Anonymized 104' status is Normal [instance: 41].
Checking raid volumes
raid volume 'Anonymized 215' status is Optimal [instance: 1].
Checking health
health 'Normal' status is Anonymized 144 [instance: 1].
health 'Normal' status is Anonymized 149 [instance: 2].
health 'Normal' status is Anonymized 127 [instance: 3].
health 'Normal' status is Anonymized 130 [instance: 4].
Checking cpu
'Normal' status is Anonymized 155 [instance: 1].
Checking memory
'Normal' status is DIMM_2 [instance: 1].
'Normal' status is DIMM_4 [instance: 2].
'Normal' status is DIMM_5 [instance: 3].
'Normal' status is DIMM_6 [instance: 4].
'Normal' status is DIMM_7 [instance: 5].
'Normal' status is DIMM_8 [instance: 6]. …
```
> fix(server-lenovo-xcc-snmp): fixed hardware verbose output

- .github/actions/package-delivery/action.yml
fix(ci): fix stable rpm promote path
> fix(ci): fix stable rpm promote path

- .github/workflows/get-environment.yml
> fix(packaging): update packaging naming scheme for plugins in unstable deliveries

- src/network/fortinet/fortigate/restapi/mode/licenses.pm
PR to build for february release
> enh(network::fortinet::fortigate::restapi): rebuild to add option and counter last-update CTOR-1126

- .github/workflows/plugins.yml
Please include a short resume of the changes and what is the purpose of this pull request. 
Any relevant information should be added to help **reviewers** to understand what are the stakes 
of the pull request.
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c public …
> fix(release): use new version scheme for plugin release tags

- .github/workflows/perl-cpan-libraries.yml
fix(packaging): fix dependecy listing for perl-cpan-libraries (https://github.com/centreon/centreon-plugins/pull/5442)
* **HTTP API (SOAP, Rest/Json, …
> fix(packaging): fix dependecy listing for perl-cpan-libraries (#5442)

- .github/workflows/perl-cpan-libraries.yml
> Release 20250202

- .github/dependabot.yml
increase the amount of gha pull requests opened by dependabot in each monthly scan + trying to prevent pull requests from other dependency sectors from being opened
Fixes # MON-147318
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk`) or …
> enh(deps): increase dependabot allowed pull request openings for github actions

- .github/workflows/actionlint.yml
- .github/workflows/docker-builder-packaging-plugins.yml
- .github/workflows/docker-builder-testing-plugins.yml
- .github/workflows/docker-builder-unit-tests.yml
- .github/workflows/perl-cpan-libraries.yml
- .github/workflows/perl-crypt-argon2.yml
- .github/workflows/perl-libssh-session.yml
- .github/workflows/perl-net-curl.yml
- .github/workflows/perl-openwsman.yml
- .github/workflows/perl-vmware-vsphere.yml
- .github/workflows/plugins.yml
enh(ci): migrate runners to arc v2
**Fixes** MON-152896
> enh(ci): migrate runners to arc v2

- .github/workflows/perl-cpan-libraries.yml
> Release 20250302

- .github/actions/parse-distrib/action.yml
- .github/workflows/perl-cpan-libraries.yml
Add the ability to specify a revision version to update cpan libs on Centreon repo.
**Fixes** CTOR-1487
> fix(cpan-libraries): Add revision to update libraries

- .github/workflows/perl-cpan-libraries.yml
* fix libssh-version naming (should be libssh-session and not liblibssh-session)
**Fixes** #CTOR-1489
* **HTTP API (SOAP, Rest/Json, XML-RPC)**: the …
> fix(packaging): handle specific case of libssh-session packaging name

- .github/workflows/perl-cpan-libraries.yml
> Release 20250303

- .github/actions/package-delivery/action.yml
- .github/actions/parse-distrib/action.yml
- .github/actions/promote-to-stable/action.yml
- .github/docker/packaging/Dockerfile.packaging-plugins-java-noble
- .github/docker/packaging/Dockerfile.packaging-plugins-noble
- .github/docker/testing/Dockerfile.testing-plugins-noble
- .github/docker/unit-tests/Dockerfile.unit-tests-noble
- .github/workflows/as400.yml
- .github/workflows/connector-vmware.yml
- .github/workflows/docker-builder-packaging-plugins.yml
- .github/workflows/docker-builder-testing-plugins.yml
- .github/workflows/docker-builder-unit-tests.yml
- .github/workflows/get-environment.yml
- .github/workflows/nrpe.yml
- .github/workflows/perl-cpan-libraries.yml
- .github/workflows/perl-filesys-smbclient.yml
- .github/workflows/perl-keepass-reader.yml
- .github/workflows/perl-openwsman.yml
- .github/workflows/perl-vmware-vsphere.yml
- .github/workflows/plugins.yml
- src/centreon/plugins/script_custom.pm
* added noble packaging support for ci containers (images and matrix)
* added noble delivery support
* enabled plugins and perl libs to be packaged for noble
> feat: add noble to ci packaging and delivery

- .github/actions/test-plugins/action.yml
- .github/docker/testing/Dockerfile.testing-plugins-alma8
- .github/docker/testing/Dockerfile.testing-plugins-alma9
- .github/docker/testing/Dockerfile.testing-plugins-bookworm
- .github/docker/testing/Dockerfile.testing-plugins-bullseye
- .github/docker/testing/Dockerfile.testing-plugins-jammy
- .github/docker/testing/Dockerfile.testing-plugins-noble
- .github/workflows/plugins.yml
Some fixes for tests to work fine on Noble images.
Refs: CTOR-1451 // but it's not related to the ticket, it was just noticed at this occasion
> fix(ci): add missing image + fix path for tests on noble

- src/centreon/common/fortinet/fortigate/snmp/mode/switchusage.pm
> fix options

- src/apps/backup/veeam/local/mode/jobstatus.pm
> fix(apps::backup::veeam::local): update jobstatus help section

- doc/en/developer/plugins_advanced.md
- doc/en/developer/sequence_diagram.md
- doc/en/developer/sequence_diagram.mmd
Enhance dev documentation about plugins
> doc(dev): add plugins sequence diagram

- src/cloud/azure/storage/storagesync/mode/filessync.pm
- src/cloud/azure/storage/storagesync/mode/recalls.pm
- src/cloud/azure/storage/storagesync/mode/serverstatus.pm
CTOR-1614
Added filter-metric help section
> enh(cloud::azure::storage::storagesync): added filter-metric help section CTOR-1614

- src/cloud/azure/storage/storagesync/mode/recalls.pm
Refs: CTOR-1614
There was an error in the help section (in addition to the format that wasn't all right).
> fix(cloud::azure::storage::storagesync): fixed thresholds options help

- src/network/stormshield/api/mode/vpntunnels.pm
> enh(network::stormshield::api): fix help section CTOR-628

- src/storage/emc/datadomain/snmp/mode/alerts.pm
> help(storage::emc::datadomain::snmp::mode::alerts): fix option description

- src/os/f5os/snmp/mode/hardware.pm
Refs:CTOR-293
update help of hardware mode
**Fixes** 
See automated tests
> doc(f5OS): fix help message

- .github/workflows/gitleaks.yml
Upgrade gitleaks action
* **HTTP API (SOAP, Rest/Json, XML-RPC)**: the documentation and some curl examples (command with -v + output) or HTTP …
> chore(ci): upgrade gitleaks action

- src/database/oracle/dbi.pm
CTOR-1634: Plugin(database::oracle) - Segmentation Fault with `glibc` Latest Version
> CTOR-1634: Plugin(database::oracle) - Segmentation Fault with `glibc` Latest Version

- .github/workflows/gitleaks.yml
- connectors/vmware/changelog
- connectors/vmware/src/centreon/script/centreon_vmware.pm
- connectors/vmware/src/centreon/vmware/common.pm
- src/database/oracle/dbi.pm
- src/os/f5os/snmp/mode/hardware.pm
Please include a short resume of the changes and what is the purpose of this pull request. 
Any relevant information should be added to help **reviewers** to understand what are the stakes 
of the pull request.
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c public …
> Release 20250501

- .github/docker/packaging/Dockerfile.packaging-plugins-java-alma8
- .github/docker/packaging/Dockerfile.packaging-plugins-java-alma9
- .github/docker/packaging/Dockerfile.packaging-plugins-java-jammy
- .github/docker/packaging/Dockerfile.packaging-plugins-java-noble
* update maven 3.8.8 to 3.8.9 in packaging dockerfiles
Fixes #MON-173182
> chore(ci): update maven from 3.8.8 to 3.8.9 in packaging dockerfiles

- packaging/centreon-plugin-Cloud-Kubernetes-Api/rpm.json
- src/cloud/kubernetes/mode/listpods.pm
- tests/cloud/kubernetes/cloud-kubernetes-list-pods.mockoon.json
- tests/cloud/kubernetes/listpods.robot
Plugin(cloud::kubernetes) - Mode(list-pods) : autodisco failure when a pod IP is empty
**Fixes** # CTOR-1644
> CTOR-1644: Mode(list-pods) : autodisco failure when a pod IP is empty

- src/apps/podman/restapi/custom/api.pm
Fixed api endpoint for container-usage 
CTOR-1794
https://github.com/centreon/centreon-plugins/issues/5644
> fix(apps::podman::restapi): fixed api endpoint for container-usage CTOR-1794

- src/centreon/plugins/mode.pm
- src/cloud/azure/custom/api.pm
- src/cloud/azure/management/costs/mode/budgets.pm
- tests/resources/spellcheck/stopwords.txt
Custom(cloud::azure::custom::api) Add option to choose cost-metric
**Fixes** # CTOR-711
> CTOR-711: Custom(cloud::azure::custom::api) Add option to choose cost-metric

- src/apps/hashicorp/vault/restapi/mode/health.pm
- tests/apps/hashicorp/vault/restapi/hashicorp-health.mockoon.json
- tests/apps/hashicorp/vault/restapi/hashicorp-health.robot
Plugin(apps::hashicorp::vault::restapi) - Mode(health)
Enhance standby mode support and add support for extra parameters
**Fixes** # CTOR-1558
> CTOR-1558: Enhance standby mode and extra parameters support

- .github/workflows/centreon-plugins-sudoers.yml
- dependencies/centreon-plugins-sudoers/centreon-plugins-sudoers.yaml
- dependencies/centreon-plugins-sudoers/sudoersCentreonPlugins
- tests/apps/nmap/cli/discovery.robot
- tests/centreon/plugins/misc.t
- tests/resources/resources.resource
integrate centreon-plugin-sudoers to centreon-plugins
Package should be installable on every supported OS.
> CTOR-1656-move-centreon-plugins-sudoers-to-centreon-plugin-repository

- src/apps/monitoring/latencetech/restapi/mode/discovery.pm
- src/apps/monitoring/latencetech/restapi/plugin.pm
- tests/apps/monitoring/latencetech/restapi/discovery.robot
- tests/apps/monitoring/latencetech/restapi/mockoon.json
New pack LatenceTech: mode discovery
Fixes CTOR-1817
Refs: CTOR-1339
> New pack LatenceTech : mode discovery

- src/apps/monitoring/latencetech/restapi/mode/radio.pm
- src/apps/monitoring/latencetech/restapi/plugin.pm
- tests/apps/monitoring/latencetech/restapi/mockoon.json
- tests/apps/monitoring/latencetech/restapi/radio.robot
New pack LatenceTech: mode radio
Fixes CTOR-1820
Refs: CTOR-1339
> New pack LatenceTech: mode radio

- connectors/vmware/packaging/debian/centreon_vmware-default
- connectors/vmware/packaging/redhat/centreon_vmware-sysconfig
centreon_vmware change defaut log severity to error
**Fixes** # CTOR 1777
> CTOR-1777 centreon_vmware change defaut log severity to error

- src/apps/monitoring/iplabel/ekara/restapi/custom/api.pm
- src/apps/monitoring/iplabel/ekara/restapi/mode/incidents.pm
- src/apps/monitoring/iplabel/ekara/restapi/mode/scenarios.pm
- tests/monitoring/iplabel/ekara/restapi/incidents.robot
- tests/monitoring/iplabel/ekara/restapi/monitoring-iplabel-ekara.json
- tests/monitoring/iplabel/ekara/restapi/scenarios.robot
Added support for authentication with X-API-KEY
**Fixes** #CTOR-1108
> Plugin(apps::monitoring::iplabel::ekara::restapi) - Custom(api) : Add a new authentication way

- .github/actions/create-jira-ticket/action.yml
- .github/actions/create-jira-ticket/nightly-ticket-template.json
- .github/workflows/plugins.yml
Please include a short resume of the changes and what is the purpose of this pull request. 
Any relevant information should be added to help **reviewers** to understand what are the stakes 
of the pull request.
**Fixes** # MON-175788
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c …
> enh(nightly-ci): split created nightly ticket by type of failure

- src/apps/monitoring/latencetech/restapi/mode/connectivity.pm
- src/apps/monitoring/latencetech/restapi/mode/forecast.pm
- src/apps/monitoring/latencetech/restapi/mode/radio.pm
- src/apps/monitoring/latencetech/restapi/mode/throughput.pm
- src/apps/monitoring/latencetech/restapi/mode/twamp.pm
- src/apps/monitoring/latencetech/restapi/plugin.pm
- tests/apps/monitoring/latencetech/restapi/mockoon.json
- tests/apps/monitoring/latencetech/restapi/twamp.robot
New pack LatenceTech: mode twamp
Fixes CTOR-1822
Refs: CTOR-1339
> New pack LatenceTech: mode twamp

- src/apps/microsoft/hyperv/2012/local/mode/scvmmdiscovery.pm
- tests/apps/microsoft/hyperv/2012/local/scvmmdiscovery.json
- tests/apps/microsoft/hyperv/2012/local/scvmmdiscovery.robot
- tests/resources/spellcheck/stopwords.txt
Refs:CTOR-1852
Fix the scvmm discovery by initialiazing the $disco_stats->{start_time} variable + add tests 
> CTOR-1852 Plugin(apps::microsoft::hyperv::2012::local) - Mode(scvmm-discovery): Fix discovery stats

- tests/resources/connector.py
> CTOR-1889 Do not try to start the perl connector if it is not installed

- src/cloud/kubernetes/custom/api.pm
Update custom/api.pm pod to include default values
**Fixes** CTOR-1837
> enh(cloud::kubernetes): update custom api pod to include default values.

- .github/workflows/perl-cpan-libraries.yml
chore(packaging): increase package revision of rpm perl cpan libraries
**Fixes** MON-185817 CTOR-1932
> chore(packaging): increase package revision of rpm perl cpan libraries

- src/storage/datacore/restapi/custom/api.pm
- src/storage/datacore/restapi/mode/alerts.pm
- src/storage/datacore/restapi/mode/monitorstatus.pm
Fix use centreon::plugin::misc
**Fixes** # CTOR-1937
> CTOR-1937 Fix use centreon::plugin::misc

- src/network/cisco/meraki/cloudcontroller/restapi/custom/api.pm
Plugin(network::cisco::meraki::cloudcontroller::restapi): check api path
**Fixes** # CTOR-1956
> Plugin(network::cisco::meraki::cloudcontroller::restapi): check api path

- .github/actions/create-jira-ticket/action.yml
- .github/docker/testing/Dockerfile.testing-plugins-alma8
- .github/docker/testing/Dockerfile.testing-plugins-alma9
- .github/docker/testing/Dockerfile.testing-plugins-bookworm
- .github/docker/testing/Dockerfile.testing-plugins-bullseye
- .github/docker/testing/Dockerfile.testing-plugins-jammy
- .github/docker/testing/Dockerfile.testing-plugins-noble
fix(ci): force usage of specific npm package versions
**Fixes** MON-187319
> fix(ci): force usage of specific npm package versions
